code template syntax fix
cc-archive/vocabulary-legacy pull request #1001
Opened 2021-10-14 16:51 UTC by Akpjunior94

## Fixes

Fixes #972 by @Akpjunior94 

## Description

Some HTML tag syntax templates are not well-formatted on the page. This pull request fixes that.

## Screenshots

Problems
![image](https://user-images.githubusercontent.com/56775903/137358875-366b38ec-3897-4ab8-9776-654f2fc42780.png)
![image](https://user-images.githubusercontent.com/56775903/137358982-9a067a92-0fe7-487b-8291-e5ba0a186270.png)

Solutions
![image](https://user-images.githubusercontent.com/56775903/137358585-31c7a64c-d24c-41eb-8c02-f55440d65e99.png)
![image](https://user-images.githubusercontent.com/56775903/137359183-526dc962-ffde-4260-b0fc-6cf49e2a02a9.png)

## Checklist
 
- [x] Added spaces where necessary.
- [x] I confirmed the project locally and confirmed there are no visible errors
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-10-14 17:01 UTC, MuluhGodson commented
Hi @Akpjunior94 
I think my assumptions and hypothesis in #1000  may be faulty. 
If what I said was correct then this PR should have triggered all the actions given that you have opened a PR on `main` and you have made changes in the `src` folder.

2021-10-14 18:15 UTC, Akpjunior94 commented
> Hi @Akpjunior94 I think my assumptions and hypothesis in #1000 may be faulty. If what I said was correct then this PR should have triggered all the actions given that you have opened a PR on `main` and you have made changes in the `src` folder.

Yes @MuluhGodson yeah It should because I made changes to the `src` and sent a PR to the `main` branch

2021-10-14 18:52 UTC, MuluhGodson commented
I think the best thing to do is update your own fork with the latest changes from the main repo. That way changes are pulled and your fork's main is current with the main repo. 
 
```bash
git checkout <commits_branch>
git merge origin/main
#solve merge conflicts 
git commit 
git push 
#pull request git push
```

<commits_branch> is the branch you did your updates in.

2021-10-14 18:59 UTC, Akpjunior94 commented
> I think the best thing to do is update your own fork with the latest changes from the main repo. That way changes are pulled and your fork's main is current with the main repo.
> 
> ```shell
> git checkout <commits_branch>
> git merge origin/main
> #solve merge conflicts 
> git commit 
> git push 
> #pull request git push
> ```
> 
> <commits_branch> is the branch you did your updates in.

Does that mean I have to close this PR do follow the above step on my vscode terminal and push back to my forked then create the PR again?

2021-10-15 10:50 UTC, brylie commented
> Does that mean I have to close this PR do follow the above step on my vscode terminal and push back to my forked then create the PR again?

@Akpjunior94, you should be able to leave your pull request open and just run the commands in your terminal. The pull request will be updated when you run `git push`.

2021-10-15 10:51 UTC, brylie commented
Sorry. I accidentally clicked "close with comment" instead of "comment".

2021-10-15 10:51 UTC, brylie requested changes
Please upgrade your npm to version 8, so we don't have so many changes to package-lock.json.

2021-10-15 10:53 UTC, brylie commented
Also, what version of `npm` do you have installed @Akpjunior94? It uses an outdated format for `package-lock.json`, which creates a lot of line changes in this pull request. PleaWould you please updater npm to version 8.?

2021-10-15 10:54 UTC, Akpjunior94 commented
> Please upgrade your npm to version 8, so we don't have so many changes to package-lock.json.

I have done that. I actually did after sending the PR yesterday. I forgot to do it before sending it. I wanted to be sure how I can go abt updating the PR.

2021-10-15 10:57 UTC, Akpjunior94 commented
> Also, what version of `npm` do you have installed @Akpjunior94? It uses an outdated format for `package-lock.json`, which creates a lot of line changes in this pull request. PleaWould you please updater npm to version 8.?

version 8.00

2021-10-15 10:57 UTC, brylie commented
OK, sounds good. Re-run the command `npm install` with the new version of `npm` and commit the changes to package-lock.json, so fewer lines are changed (if any).

2021-10-15 11:00 UTC, Akpjunior94 commented
> OK, sounds good. Re-run the command `npm install` with the new version of `npm` and commit the changes to package-lock.json, so fewer lines are changed (if any).

Okay

2021-10-15 12:15 UTC, Akpjunior94 commented
It's updated @brylie you can check the PR.

2021-10-15 12:16 UTC, brylie requested changes

2021-10-15 12:16 UTC, brylie commented on package-lock.json
> +}
Add newline at end
```suggestion
}

```

2021-10-15 12:17 UTC, Akpjunior94 commented on package-lock.json
> +}
Okay

2021-10-15 12:19 UTC, brylie requested changes

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +export const postVideo = (width,image_size,orientation) => `<div style=" max-width: ${width}px;">
Lint
```suggestion
export const postVideo = (width,image_size,orientation) => `<div style="max-width: ${width}px;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +    <div style=" max-width: 100%;">
Lint
```suggestion
    <div style="max-width: 100%;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +style=" max-width: ${width}px;">
Lint
```suggestion
style="max-width: ${width}px;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +    <div style=" max-width: 600px;">
Lint
```suggestion
    <div style="max-width: 600px;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +    <div style=" max-width: 600px;">
Lint
```suggestion
    <div style="max-width: 600px;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +    <div style=" max-width: 340px;">
Lint
```suggestion
    <div style="max-width: 340px;">
```

2021-10-15 12:19 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +    <div style=" max-width: 384px;" class="margin-normal">
Lint
```suggestion
    <div style="max-width: 384px;" class="margin-normal">
```

2021-10-15 12:19 UTC, brylie commented on src/stories/meta/gettingstarted.stories.mdx
> +    <div style=" background-color:red; height: 200px;"></div>
Lint
```suggestion
    <div style="background-color:red; height: 200px;"></div>
```

2021-10-15 12:19 UTC, brylie commented on src/stories/meta/gettingstarted.stories.mdx
> +    style="background-color: rgb(237, 89, 47); height: 200px;"
Remove floating code
```suggestion
```

2021-10-15 12:36 UTC, brylie requested changes

2021-10-15 12:36 UTC, brylie commented on src/components/cards/cards.stories.mdx
> +`<div style=" max-width: ${width}px;">
Lint
```suggestion
`<div style="max-width: ${width}px;">
```

2021-10-15 12:39 UTC, brylie requested changes

2021-10-15 12:39 UTC, brylie commented on src/stories/meta/gettingstarted.stories.mdx
> +    <div style="background-color:red; height: 200px;"></div>
Revert this change
```suggestion
    <div style="background-color: rgb(237, 89, 47); height: 200px;"></div>
```

2021-10-15 12:40 UTC, brylie commented
@Akpjunior94, please be sure to use meaningful commit messages that describe the change you are making. Where possible, add related changes under a single commit. For example, you can make all of the lint changes with a single commit.

2021-10-15 12:41 UTC, Akpjunior94 commented
> @Akpjunior94, please be sure to use meaningful commit messages that describe the change you are making. Where possible, add related changes under a single commit. For example, you can make all of the lint changes with a single commit.

Okay Noted

2021-10-15 12:45 UTC, brylie approved these changes

2021-10-15 12:45 UTC, merged

2021-10-15 12:46 UTC, brylie commented
@all-contributors please add @Akpjunior94 for code