feat: add first-time.yml action
cc-archive/vocabulary-legacy pull request #1028
Opened 2021-12-07 07:14 UTC by thuongtruong1009

## Checklist
 
- [x ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [x ] I added or updated tests for the changes I made (if applicable).
- [x ] I added or updated documentation (if applicable).
- [x ] I tried running the project locally and verified that there are no
  visible errors.

2021-12-07 07:27 UTC, brylie requested changes

2021-12-07 07:27 UTC, brylie commented on .github/workflows/first-time.yml
> +        pr-message: 'Thanks for your first Pull-request here! Be sure to follow the issue template! The notify email will be sent to you as soon as.'
> The notify email will be sent to you as soon as.

The above sentence is a fragment and might confuse people. So, we should consider rewording the issue/PR messages to contain complete sentences.

2021-12-07 07:27 UTC, brylie commented on .github/workflows/first-time.yml
> +        repo-token: ${{ secrets.GITHUB_TOKEN }}
Out of curiosity, would this possibly expose our GitHub token to the author of `actions/first-interaction`? E.g. could they possibly define a script or service that sends our GitHub token to an external location, such as by making an HTTP request, from within the `actions/first-interaction` service?

2021-12-07 07:27 UTC, brylie commented on .github/workflows/first-time.yml
> +        pr-message: Thanks for your first Pull-request here! Be sure to follow the issue template! The notify email will be sent to you as soon as.
The issue and PR messages contain sentence fragments.

2021-12-11 04:09 UTC, nimishbongale commented on .github/workflows/first-time.yml
> +        issue-message: 'Welcome to creativecommons community! Thanks so much for creating your first issue :)'
We could consider rephrasing this to something along the lines of "Welcome to the Creative Commons Open Source community. Thanks for creating your first issue! 🚀 "

2021-12-11 04:09 UTC, nimishbongale commented on .github/workflows/first-time.yml
> +        pr-message: 'Thanks so much for creating your first PR, the creativecommons community thanks you :)'
We could consider rephrasing this to something along the lines of "You have successfully raised your first PR to the CC Vocabulary repository. The Creative Commons Open Source community is grateful for your contribution! 💯"

2022-02-10 02:45 UTC, closed without merging

2022-02-10 02:47 UTC, thuongtruong1009 commented on .github/workflows/first-time.yml
> +        pr-message: 'Thanks so much for creating your first PR, the creativecommons community thanks you :)'
Hi @nimishbongale @brylie 
I make a Pull Request [1059[(https://github.com/creativecommons/vocabulary/pull/1059)
Thank you very much!