Add Logos and stories
cc-archive/vocabulary-legacy pull request #131
Opened 2020-02-20 20:45 UTC by dhruvkb

**Fixes**

Fixes #99 by @annatuma 

**Description**
Adds the logos from Figma as SVG assets and stories showing how to use the assets.

**Type of PR** 
This PR is a feature.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-02-20 20:48 UTC, kgodey requested changes

2020-02-20 20:48 UTC, kgodey commented on package.json
> +  "author": "Breno Ferreira",
could we update the author here to be `Creative Commons` since this is a collaborative project? @brenoferreira

2020-02-20 23:21 UTC, dhruvkb commented on package.json
> +  "author": "Breno Ferreira",
Made the [corresponding change](https://github.com/creativecommons/vue-vocabulary/blob/88bf79c1f0b1534db8a109c451c2316b269c099e/package.json#L5) in Vue Vocabulary.

2020-02-21 12:11 UTC, brenoferreira commented on package.json
> +  "author": "Breno Ferreira",
@kgodey yes. This is probably just reminiscent of https://github.com/brenoferreira/bulma_vocabulary

2020-02-21 13:20 UTC, brenoferreira requested changes
The white logos aren't showing up here. Not sure if the inverted background thing isn't working.

2020-02-21 13:20 UTC, brenoferreira commented on src/assets/logos/cc/wordmark.svg
> +<svg width="304" height="73" viewBox="0 0 304 73" xmlns="http://www.w3.org/2000/svg">
`logo` or `logomark` is a better name.

2020-02-21 13:20 UTC, brenoferreira commented on src/stories/logos.stories.js
> +export const CCWordmarkWhite = () => `<div style="color:white;">${wordmark}</div>`
You can use Bulma's color helpers here instead of setting the color to white explicitly https://bulma.io/documentation/modifiers/color-helpers/

2020-02-21 13:20 UTC, brenoferreira commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
Instead of adding the SVG directly in HTML, isn't it possible to do something like Bulma's use of FontAwesome?

something like:
```
<span class="icon">
  <i class="cc-lettermark"></i>
</span>
```

2020-02-21 18:58 UTC, dhruvkb commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
Using the SVG directly in HTML enables a whole array of features, most notably `currentColor` which allows the SVG to be colored using the CSS `color` property.

2020-02-21 18:59 UTC, dhruvkb commented
As for the white not appearing, you might be missing the backgrounds addon. Did you run `npm install` after checking out the branch?

2020-02-21 19:01 UTC, dhruvkb commented on src/stories/logos.stories.js
> +export const CCWordmarkWhite = () => `<div style="color:white;">${wordmark}</div>`
Oh, I'll do that in a jiffy. Sorry if I'm not aware of the finer details of Bulma.

2020-02-21 19:21 UTC, dhruvkb commented on src/assets/logos/cc/wordmark.svg
> +<svg width="304" height="73" viewBox="0 0 304 73" xmlns="http://www.w3.org/2000/svg">
Changed to `logomark` 👍!

2020-02-21 19:30 UTC, dhruvkb commented
@brenoferreira I've made a bunch of changes, please re-review.

2020-02-21 19:53 UTC, brenoferreira commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
I don't think we want to give too much freedom in changing how the logomarks are used. Ease of usage might be better in this case

2020-02-21 20:29 UTC, dhruvkb commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
So how do you suggest we implement color change to white on dark backgrounds? I only know this way to color SVGs. In fact, the new version of Font Awesome, FA5, uses the same technique. They did away with `<i>` and switched to `<svg>`.

2020-02-21 21:12 UTC, brenoferreira commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
For now we can go ahead with this. But I think `<i>` will be useful. We can create a separate issue for that

2020-02-21 21:16 UTC, dhruvkb commented on src/stories/logos.stories.js
> +CCLettermarkWhite.story = invertedBackground
I can't merge this. If you find it satisfactory, you'll have to merge it. I'll investigate how we could do it with `<i>` tags in the meantime.

2020-02-21 21:17 UTC, dhruvkb commented
I'll just resolve the merge conflict.

2020-02-21 21:21 UTC, kgodey approved these changes

2020-02-21 21:21 UTC, kgodey commented on package.json
> +  "author": "Breno Ferreira",
@dhruvkb can you make it here too?

2020-02-21 21:28 UTC, merged