Add new scss stylesheet for GithubCorner
cc-archive/vocabulary-legacy pull request #137
Opened 2020-02-23 16:57 UTC by jshreyans

**Fixes**
Fixes #130  by @jshreyans

**Description**
This PR adds a new SCSS file to the `/styles` directory specifically for the GithubCorner component from vue-vocabulary. For further context, refer to [#118](https://github.com/creativecommons/vue-vocabulary/issues/118) and [#155](https://github.com/creativecommons/vue-vocabulary/pull/155). After changes from this issue, the styles needed to be modified so that the GithubCorner component only had 2 colors and 2 positions.

**Type of PR** 
This PR is a refactor.

**Technicalities**
For styling reference, the `.styl` file that was made long back for this component (as part of vue-vocabulary) has been used. The relevant commit for that file can be found [here](https://github.com/creativecommons/vue-vocabulary/commit/5d878281204cdc41e7dc54fb2c0ad5ffc818d929#diff-fab1eda801d1c7d086198302a02433ae)

**Tests**

**Screenshots**

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-02-23 21:21 UTC, dhruvkb commented
@jshreyans the tests are failing. Could you pull `master` into the branch, or alternatively rebase this branch onto `master`? Passing the tests would give some us confidence to merge.

2020-02-23 21:28 UTC, dhruvkb requested changes
Add the story to demonstrate. You can paste the SVG from Vue Vocabulary directly into the story.

2020-02-23 21:28 UTC, dhruvkb commented on src/styles/github_corner.scss
> +  &.inverted {
Modifiers start with `is-` or `has-`. So a better class name would be `is-inverted`.

2020-02-24 03:27 UTC, jshreyans commented
> @jshreyans the tests are failing. Could you pull `master` into the branch, or alternatively rebase this branch onto `master`? Passing the tests would give some us confidence to merge.

I pulled master and the tests seem to have passed

2020-02-24 03:28 UTC, jshreyans commented on src/styles/github_corner.scss
> +  &.inverted {
Corrected

2020-02-25 14:12 UTC, jshreyans commented
> Add the story to demonstrate. You can paste the SVG from Vue Vocabulary directly into the story.

Need a little help with this. I created a story but I seem to have made some mistake. Could you just outline what all the story needs to include?

2020-02-26 10:47 UTC, dhruvkb commented
@jshreyans the story should demonstrate
- both black-on-white and white-on-black versions
- both left-aligned and right-aligned versions

2020-02-27 05:16 UTC, jshreyans commented
@dhruvkb I've added the story with the above components. Although, I'm a little doubtful whether the left corner position works fine. Because when the corner is on the left, it needs to be spun around along its axis.

2020-02-27 10:36 UTC, dhruvkb requested changes

2020-02-27 10:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +</svg>
Make this SVG an asset in the dir `src/assets/`. Would make it easier to use in Vocabulary as well as Vue Vocabulary.

2020-02-27 10:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export const GithubCorner = () => `
```suggestion
export const Default = () => `
```

2020-02-27 10:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export const GithubCornerInverted = () => `
```suggestion
export const Inverted = () => `
```

2020-02-27 10:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export const GithubCornerLeft = () => `
```suggestion
export const LeftAligned = () => `
```

2020-02-27 10:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export const GithubCornerRight = () => `
Isn't this already demonstrated by the default story?

2020-02-28 06:21 UTC, jshreyans commented on src/stories/github_corner.stories.js
> +</svg>
Done

2020-02-29 04:25 UTC, jshreyans commented on src/stories/github_corner.stories.js
> +export const GithubCornerRight = () => `
Should I remove this variation then?

2020-02-29 05:15 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export const GithubCornerRight = () => `
Yes, remove it. Only keep the distinct variants.

2020-02-29 05:19 UTC, dhruvkb requested changes
Finish by importing this SCSS file into `src/scss/vocabulary.scss`.

2020-02-29 05:19 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +  :rel="rel"
These attributes that begin with `:` are Vue props, they won't have any effect here. Remove all of them.

2020-02-29 05:19 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +  aria-label="View source on GitHub">
Can also remove this for brevity in examples. Upto you though.

2020-02-29 05:19 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +const GithubCornerSVG = '' +
```suggestion
const GitHubCornerSVG = '' +
```

2020-02-29 05:19 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +export default { title: 'GithubCorner' }
```suggestion
export default { title: 'GitHubCorner' }
```

2020-02-29 05:19 UTC, dhruvkb commented on src/styles/github_corner.scss
> +@import "./colors.scss";
Not required.

2020-02-29 05:31 UTC, jshreyans commented on src/styles/github_corner.scss
> +@import "./colors.scss";
The white and black colors are defined in this file. I thought I should use them for the sake of avoiding repetition. I'll remove it if needed.

2020-02-29 05:31 UTC, jshreyans commented on src/stories/github_corner.stories.js
> +  aria-label="View source on GitHub">
I think we should keep it there.

2020-02-29 07:36 UTC, dhruvkb commented on src/stories/github_corner.stories.js
> +  aria-label="View source on GitHub">
Cool, we'll keep it then 👍.

2020-02-29 07:36 UTC, dhruvkb commented on src/styles/github_corner.scss
> +@import "./colors.scss";
It's automatically imported when the SCSS is compiled.

2020-02-29 07:38 UTC, dhruvkb reviewed
The import for `colors.scss` is not required as the SCSS when compiled from `vocabulary.scss` automatically resolves these imports.

2020-02-29 07:38 UTC, dhruvkb commented on src/styles/github_corner.scss
> +@import "./colors.scss";
Remove it.

2020-02-29 08:03 UTC, jshreyans commented
Hadn't seen your comment to remove the right aligned variant. This commit should do it.

2020-02-29 13:12 UTC, dhruvkb approved these changes
This is good to go!

2020-02-29 13:29 UTC, merged