Add header to match figma DL
cc-archive/vocabulary-legacy pull request #145
Opened 2020-02-26 03:12 UTC by chidexebere

**Fixes**

Fixes #91 by @annatuma 

**Description**
This adds the Header (Big and Small) to Vocabulary to match the Figma DL

**Type of PR** 
This PR is a feature.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-02-27 12:37 UTC, hugosolar requested changes

2020-02-27 12:37 UTC, hugosolar commented on src/stories/header.stories.js
> +            <a href="#" class="explore-tab">Explore CC</a>
Hey @chidexebere the explore tab should be part of the global navigation. so there's no need to be in this component

2020-02-27 12:37 UTC, hugosolar commented on src/stories/header.stories.js
> +            <a href="#" class="explore-tab">Explore CC</a>
Same here. The explore tab is part of the global navigation component

2020-02-27 12:37 UTC, hugosolar commented on src/styles/header.scss
> +      padding: 0.5rem 1rem;
There are some `spaces` variables in `spaces.scss` we should use those variables

2020-02-28 00:24 UTC, chidexebere commented on src/styles/header.scss
> +      padding: 0.5rem 1rem;
Made use of spaces variables where they apply

2020-02-28 00:24 UTC, chidexebere commented on src/stories/header.stories.js
> +            <a href="#" class="explore-tab">Explore CC</a>
Removed

2020-02-28 00:25 UTC, chidexebere commented on src/stories/header.stories.js
> +            <a href="#" class="explore-tab">Explore CC</a>
Removed

2020-02-28 00:37 UTC, hugosolar requested changes
Last detail. The hover state of the navigation element should be as in figma. it's just a small color change of the selected element and the background doesn't change

<img width="374" alt="Screen Shot 2020-02-27 at 9 35 08 PM" src="https://user-images.githubusercontent.com/894708/75499623-49c1bc80-59a9-11ea-8aaf-12a6d86986ed.png">

Also, the arrow is not the same as the figma design.

2020-02-28 03:26 UTC, chidexebere commented
> Last detail. The hover state of the navigation element should be as in figma. it's just a small color change of the selected element and the background doesn't change
> 
> <img alt="Screen Shot 2020-02-27 at 9 35 08 PM" width="374" src="https://user-images.githubusercontent.com/894708/75499623-49c1bc80-59a9-11ea-8aaf-12a6d86986ed.png">
> 
> Also, the arrow is not the same as the figma design.

done

2020-03-02 18:49 UTC, chidexebere commented
> Last detail. The hover state of the navigation element should be as in figma. it's just a small color change of the selected element and the background doesn't change
> 
> <img alt="Screen Shot 2020-02-27 at 9 35 08 PM" width="374" src="https://user-images.githubusercontent.com/894708/75499623-49c1bc80-59a9-11ea-8aaf-12a6d86986ed.png">
> 
> Also, the arrow is not the same as the figma design.

fixed

2020-03-03 03:40 UTC, hugosolar requested changes

2020-03-03 03:40 UTC, hugosolar commented on src/styles/header.scss
> +    .navbar-link:visited {
You also need to specify the color of the text... there's a slight color change from dark-slate-gray to black as you can see in the image

<img width="374" alt="Screen Shot 2020-02-27 at 9 35 08 PM" src="https://user-images.githubusercontent.com/894708/75740833-86fab700-5ce7-11ea-87ed-c5e934a04114.png">

2020-03-03 19:37 UTC, chidexebere commented on src/styles/header.scss
> +    .navbar-link:visited {
fixed....its actually from light-slate-gray to black

2020-03-04 22:04 UTC, hugosolar approved these changes

2020-03-12 15:28 UTC, merged