Add licensebadge to stories
cc-archive/vocabulary-legacy pull request #146
Opened 2020-02-26 05:09 UTC by Dhruvi16

**Fixes**

Fixes #63 

**Description**

**Type of PR** 
This PR is a [feature|hotfix|refactor].

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ ] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-02-26 10:45 UTC, dhruvkb commented
@Dhruvi16 I've made some changes that not only fix the missing badges but also reorganise the assets to account for the [smaller 80x15 license badges](https://creativecommons.org/about/downloads) that you will hopefully add in the future.

2020-02-27 05:48 UTC, Dhruvi16 commented
Hey! I tried adding id too. It was not working for me then but it is now!

2020-03-01 05:25 UTC, Dhruvi16 commented
I am not sure if this is a feature!

2020-03-06 16:57 UTC, dhruvkb commented
@Dhruvi16 it is very much a feature!

2020-03-06 17:09 UTC, dhruvkb requested changes
Some changes for reducing code duplication and improving readability.

2020-03-06 17:09 UTC, dhruvkb commented on src/stories/license_badge.stories.js
> +export const BYSA = () => `<div>${bysa}</div>`
Use _ to separate words like BY_SA. That underscore changes to a space when it's rendered in the storybook.

2020-03-06 17:09 UTC, dhruvkb commented on src/stories/license_badge.stories.js
> +  '</svg>'
Make this a function like so:
```js
const licenseSVG = (size, license) => `<svg ...>
<use href="licensebadges/${size}/${license}.svg#layer1"></use>
</svg>`
```

2020-03-06 17:09 UTC, dhruvkb commented on src/stories/license_badge.stories.js
> +export const BYSASmall = () => `<div>${bysaSmall}</div>`
With the above feedback this becomes BY_SA_Small.

2020-03-08 01:11 UTC, Dhruvi16 commented on src/stories/license_badge.stories.js
> +  '</svg>'
This is great for code duplication. I should have thought about it. But this fails in the case of cc_zero and public domain svgs where the id is` #Layer1`. I will think of something and get back to you.

2020-03-08 01:18 UTC, Dhruvi16 commented on src/stories/license_badge.stories.js
> +  '</svg>'
One idea off the top of my head is to create id a variable and pass it through the parameter. Lemme know what you think about it.

2020-03-08 17:13 UTC, dhruvkb commented on src/stories/license_badge.stories.js
> +  '</svg>'
You can edit the SVGs and make the IDs same for all of them.

2020-03-10 02:04 UTC, Dhruvi16 commented
I am getting a Lint error - 
![image](https://user-images.githubusercontent.com/34674462/76272465-804ce080-62a1-11ea-8422-ded805e988a8.png)

2020-03-11 18:29 UTC, dhruvkb approved these changes

2020-03-11 18:31 UTC, merged