Integrate Figma with the storybook
cc-archive/vocabulary-legacy pull request #160
Opened 2020-03-05 18:58 UTC by Tanuj22

**Fixes**

Fixes #153  by @dhruvkb 

**Description**
[Storybook addon](https://github.com/pocka/storybook-addon-designs) added.

**Type of PR** 
This PR is a feature.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-06 16:56 UTC, dhruvkb requested changes
I'm sorry if the issue description wasn't clear, integrating the addon is not enough. Please also add the [Figma pages](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=1433%3A0) to the corresponding stories.

2020-03-06 16:56 UTC, dhruvkb commented on .storybook/main.js
> +    'storybook-addon-designs/register'
The `/register` part is not required.
```suggestion
    'storybook-addon-designs'
```

2020-03-06 18:53 UTC, Tanuj22 commented
> I'm sorry if the issue description wasn't clear, integrating the addon is not enough. Please also add the [Figma pages](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=1433%3A0) to the corresponding stories.

Sorry for that. On it.

2020-03-06 21:06 UTC, Tanuj22 commented
There are some `button` which available in big,middle and small in Figma which but vocabulary has only one. Which do I use in vocabulary?

2020-03-07 22:25 UTC, Tanuj22 commented
@dhruvkb  Please check the figma pages added.Some `buttons` and `Logos` were not available in Figma. Also some components were not seperable like in `Typography` and `GithubCorner`. Also what should I do with `Colors`? Should I put all the `Colors` in a single story? Please suggest changes for these queries? Thanks.

2020-03-08 14:54 UTC, dhruvkb approved these changes
Looks good to me, might conflict with #161.

2020-03-08 14:55 UTC, dhruvkb commented
@Tanuj22 could you please pull `master` into this branch? That's the only small thing blocking the PR.

2020-03-09 05:51 UTC, Tanuj22 commented
@dhruvkb Done

2020-03-09 18:11 UTC, dhruvkb commented
@Tanuj22 by the time I came to review, it's out of date again.

2020-03-09 18:13 UTC, Tanuj22 commented
@dhruvkb  DOne

2020-03-10 10:41 UTC, dhruvkb commented
Waiting for PR #161 to be merged. Then this will be of great help.

2020-03-11 19:34 UTC, merged