Add MDX stories for colors and typography with documentation from Figma
cc-archive/vocabulary-legacy pull request #161
Opened 2020-03-06 14:16 UTC by dhruvkb

**Description**
This PR adds documentation for Colors and Typography from Figma using MDX.

**Type of PR** 
This PR is a feature.

**Technicalities**
Moving to MDX means essentially rewriting every story. This takes time so this PR can be merged incrementally.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-10 11:54 UTC, hugosolar reviewed
It's generally ok but I don't know why, logos in `docs` mode takes a lot to load.
Also, I think we should avoid the `preview` element from stories when it's not useful. for instance:

![Screen Shot 2020-03-10 at 8 49 49 AM](https://user-images.githubusercontent.com/894708/76309841-5fd65380-62ac-11ea-9f72-6f5bae992f36.png)

This can be replaced with a markdown code block with an example of a layout. 
In order to show the rendered component I think it can be embeded inside the `mdx` file

2020-03-10 12:29 UTC, brenoferreira requested changes

2020-03-10 12:29 UTC, brenoferreira commented on src/stories/spacing.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks'
To me this looks like duplicated documentation of what's in Figma. If we're planning to integrate Figma into Storybook, I think section should explain how to use the generated `margin` and `padding` classes instead, which is what users of Vocab. will actually use

2020-03-10 12:29 UTC, brenoferreira commented on src/stories/typography.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks'
Same here with Typography as in Spacing. Some code examples here don't show which class is supposed to be used. This could be just straightforward examples of the markup and classes to use. The more verbose docs are in Figma

2020-03-10 12:29 UTC, brenoferreira commented on src/styles/typography.scss
> +$font-size-h6: 1rem; // Not in Figma, extrapolated
This could be `1.15rem` as usually body text has font size of `1rem`

2020-03-10 12:59 UTC, brenoferreira reviewed
I think much of this MDX documentation here is duplicated of Figma content. This should be more a developer focused documentation of how to use Vocabulary and its classes, how to markup stuff, etc..

2020-03-10 12:59 UTC, brenoferreira commented on src/stories/color.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks'
This doesn't have any documentation of the color classes defined in the sass file, like `.has-background-<brand-color>` and `.has-color-<brand-color>`

2020-03-10 13:54 UTC, brenoferreira commented
I added some mdx docs to the buttons that I think are better at documenting usage of Vocabulary for developers https://github.com/creativecommons/vocabulary/pull/168/files#diff-6c0fb0dd9697b028d77640f203667a0eR1

2020-03-10 14:37 UTC, dhruvkb commented
I'll add more documentation that's developer oriented.

2020-03-11 00:52 UTC, dhruvkb commented on src/styles/typography.scss
> +$font-size-h6: 1rem; // Not in Figma, extrapolated
Updated.

2020-03-11 00:53 UTC, dhruvkb commented on src/stories/typography.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks'
Noted, understood, implemented.

2020-03-11 00:53 UTC, dhruvkb commented on src/stories/spacing.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks'
Noted, understood, implemented.

2020-03-11 01:12 UTC, dhruvkb reviewed
@brenoferreira updated to include your feedback.

2020-03-11 16:59 UTC, brenoferreira approved these changes

2020-03-11 16:59 UTC, brenoferreira commented on .storybook/main.js
> +    '../src/stories/spacing.stories.mdx',
Individual story configs here aren't necessary right? `*.stories.mdx` is already set below

2020-03-11 17:09 UTC, merged

2020-03-11 17:38 UTC, dhruvkb commented on .storybook/main.js
> +    '../src/stories/spacing.stories.mdx',
Adding them individually so that they show up at the top (tokens being the most fundamental design elements).