fixed border error around button in mozilla
cc-archive/vocabulary-legacy pull request #172
Opened 2020-03-12 08:36 UTC by Vineet-Sharma29

**Fixes**
Fixes #156 by @Vineet-Sharma29

**Description**
Removed border around button in `src/styles/button.scss`

**Type of PR** 
This PR is a hotfix.

**Technicalities**
Added `::-moz-focus-inner {border: 0;}` to button class

**Tests**

**Screenshots**
![Screenshot from 2020-03-12 13-50-06](https://user-images.githubusercontent.com/35156299/76502396-f603a880-6469-11ea-9566-196242d148ee.png)

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-13 11:45 UTC, brenoferreira requested changes

2020-03-13 11:45 UTC, brenoferreira commented on src/styles/button.scss
> +  &::-moz-focus-inner {
MDN says this feature isn't recommended for usage https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-focus-inner.

2020-03-14 17:00 UTC, Vineet-Sharma29 commented on src/styles/button.scss
> +  &::-moz-focus-inner {
@brenoferreira I am unable to figure out some other way to do it.

2020-03-18 12:38 UTC, brenoferreira commented on src/styles/button.scss
> +  &::-moz-focus-inner {
No one on our team was able to reproduce this. It seems to me this probably doesn't affect many users. And since this solution isn't recommended, I'm closing this. But thanks for your contribution

2020-03-18 12:38 UTC, closed without merging