Fix the problems in the Header component
cc-archive/vocabulary-legacy pull request #176
Opened 2020-03-13 08:43 UTC by dhruvkb

**Fixes**

Fixes #174 by @dhruvkb 

**Description**

The PR fixes the broken references in `header.scss` and `header.stories.js` that were causing the build to fail.

**Type of PR** 
This PR is a hotfix.

**Technicalities**
Changes to Sass tokens and the logos story in #161 caused the header stylesheet and story to contain broken references, which in turn prevented the SCSS files from compiling and the storybook from building.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-15 01:28 UTC, hugosolar reviewed
I can't see the arrow next to the items with dropdowns.
Also, I ask Chidi to remove the "Explore CC" button because it's parte from the global header component

2020-03-15 07:50 UTC, dhruvkb commented
The existing arrow from Bulma looks like a chevron and is differen from the arrow used in Figma. That arrow needs to be imported from `creativecommons/fonts` for which we need to merge creativecommons/fonts#8 and resolve creativecommons/fonts#12.

2020-03-15 07:55 UTC, dhruvkb commented
I'll remove the explore CC button. You're right that belongs to the superheader component.

2020-03-16 12:53 UTC, brenoferreira commented
<img width="1076" alt="Screen Shot 2020-03-16 at 09 52 02" src="https://user-images.githubusercontent.com/707019/76760129-dc18dd00-676b-11ea-8502-393f4c3e9b4e.png">
The problem with using a function to render the html is that the code docs displayed don't show what we need.

2020-03-16 12:55 UTC, brenoferreira commented
<img width="682" alt="Screen Shot 2020-03-16 at 09 53 55" src="https://user-images.githubusercontent.com/707019/76760361-47fb4580-676c-11ea-9e46-e5c64a9c4edb.png">
some comments about the mobile layout

2020-03-16 13:07 UTC, brenoferreira commented on src/styles/header.scss
> +  .container {
Header with a `.container`? Why is this necessary?

2020-03-16 13:19 UTC, brenoferreira commented on src/stories/header.stories.mdx
> +              <a class="navbar-link is-arrowless">Dropdown</a>
This is supposed to have an arrow

2020-03-16 15:28 UTC, dhruvkb commented on src/stories/header.stories.mdx
> +              <a class="navbar-link is-arrowless">Dropdown</a>
The arrow is waiting for creativecommons/fonts#8 and creativecommons/fonts#12.

2020-03-17 18:37 UTC, dhruvkb commented on src/stories/header.stories.mdx
> +              <a class="navbar-link is-arrowless">Dropdown</a>
Added the arrow with 57b9c15.

2020-03-17 18:38 UTC, dhruvkb commented on src/styles/header.scss
> +  .container {
After the arrival of PR #180, this is necessary for consistency with the footer.

2020-03-17 18:45 UTC, dhruvkb commented
Using the `mdxSource` prop on the `Preview` component allows us to display any source code in the preview, so here it goes.
![Screen Shot 2020-03-18 at 00 13 57](https://user-images.githubusercontent.com/16580576/76890515-80ef0380-68ad-11ea-86b0-6a746e78bb67.png)
Beautiful 😍!

2020-03-17 19:01 UTC, dhruvkb commented
Blocked till #183 is resolved.

2020-03-17 20:31 UTC, hugosolar commented on src/styles/header.scss
> +  .container {
In most of the websites we need to center the content of the header and the whole website, so `.container`. However I think we may need a header version without container for cc search right?

2020-03-18 06:48 UTC, dhruvkb commented
@hugosolar @brenoferreira this is ready for merge.

2020-03-18 11:08 UTC, hugosolar approved these changes

2020-03-18 12:53 UTC, brenoferreira requested changes
The problems with the mobile hamburger menu still persist:

- it is not sticking to the right
- the menu doesn't open when you click it

2020-03-18 12:53 UTC, brenoferreira commented
<img width="639" alt="Screen Shot 2020-03-18 at 09 53 39" src="https://user-images.githubusercontent.com/707019/76962644-5d07de00-68fe-11ea-98d5-0d256b90d632.png">

2020-03-18 12:56 UTC, brenoferreira commented
I think you could try to implement something similar to how CC Search does the hamburger menu with a checkbox and CSS: https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/NavSection.vue#L6

2020-03-18 14:09 UTC, brenoferreira commented
About the checkbox to toggle the hamburger menu, I think that's going to be too hard to do because Bulma toggles visibility with the `.is-active` class. So I think that will require JS :(

2020-03-18 18:03 UTC, brenoferreira approved these changes

2020-03-18 18:03 UTC, merged