Unit test for color.scss
cc-archive/vocabulary-legacy pull request #182
Opened 2020-03-17 18:01 UTC by silvinabt87

**Fixes**
Partially addresses SCSS testing #165 

**Description**
This PR runs a unit test for color.scss
@each was wrapped within a @mixin in order to test it with True
npm run test

**Type of PR** 
This PR is a feature

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x]My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-18 19:40 UTC, dhruvkb requested changes

2020-03-18 19:40 UTC, dhruvkb commented on tests/tests.scss
> +@include it('creates classes based on each color') {
This test, belongs in a different file under `tests/unit/`. Let's keep this file just to import unit tests.

2020-03-18 19:40 UTC, dhruvkb commented on tests/tests.scss
> +}
All files should end with a newline. If you can, I would recommend you use an IDE (eg. WebStorm, my personal favourite) to take care of the smaller things like that.

2020-03-18 19:40 UTC, dhruvkb commented on src/styles/color.scss
> +@mixin color-classes($brand-colors: $brand-colors) {
Instead of a mixin that makes all the classes, how about one that makes classes for the color you pass to it and then you call the mixin inside the loop? That would make it easier to test the functionality of the mixin in the accompanying unit test.

2020-03-18 22:22 UTC, silvinabt87 commented on src/styles/color.scss
> +@mixin color-classes($brand-colors: $brand-colors) {
OK! Let me try it out and come back with another PR

2020-03-19 06:25 UTC, dhruvkb commented on src/styles/color.scss
> +@mixin color-classes($brand-colors: $brand-colors) {
You can update this PR itself with more commits:
<img width="576" alt="Screenshot 2020-03-19 at 11 55 33 AM" src="https://user-images.githubusercontent.com/16580576/77037961-8ac15580-69d8-11ea-855f-8740b48c6f02.png">

2020-03-19 18:30 UTC, silvinabt87 commented
I accidentally marked this Pr for review but I haven't made the changes yet.

2020-03-20 06:25 UTC, dhruvkb requested changes
The main complaint I have is against the PR removing a lot of blank lines and not meeting some of the style guide rules. The actual test and the code you added is great.

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> -
Why did you remove these blank lines?

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> +$color-error: rgb(200, 59, 30);
👍

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> -);
This is just the same...

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> +$brand-colors: ( "tomato": $color-tomato, "orange": $color-orange, "gold": $color-gold, "forest-green": $color-forest-green, "dark-turquoise": $color-dark-turquoise, "dark-slate-blue": $color-dark-sl
...as this.

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> +$brand-color in $brand-colors {
Don't break the line in the middle.
```suggestion
@each $color-namespace, $brand-color in $brand-colors {
```

2020-03-20 06:25 UTC, dhruvkb commented on tests/unit/color-test.scss
> +@include it("creates class based on color") {
Indent with 2 spaces, not 4.

2020-03-20 06:25 UTC, dhruvkb commented on tests/tests.scss
> -
Removing newlines makes code harder to read.

2020-03-20 06:25 UTC, dhruvkb commented on src/styles/color.scss
> +;
```suggestion
};
```

2020-03-20 14:35 UTC, silvinabt87 commented on src/styles/color.scss
> +;
Thanks for the feedback! Sorry, I didn't notice that happened on such a scale. I'll fix it and check what is provoking that on VSC. On the other hand, I'm working on spacing.scss and typography.scss so probably today I'll have it ready.

2020-03-20 14:45 UTC, dhruvkb commented on src/styles/color.scss
> +;
@silvinabt87 I highly recommend WebStorm if you can get a student license.

2020-03-20 14:54 UTC, silvinabt87 commented on src/styles/color.scss
> +;
OK! I'll check that out.

2020-03-21 07:52 UTC, dhruvkb commented
@silvinabt87 I'm leaving the "status:waiting" label as you haven't made the other changes yet.

2020-03-22 18:01 UTC, silvinabt87 commented
@dhruvkb I've resolved the comments and added mixins and tests for typography.scss.
Can we merge this PR? Should I continue with the same process for spacing.scss?

2020-03-23 15:10 UTC, dhruvkb commented
@silvinabt87 I'm a little swamped for a few days, please add tests for spacing along the same lines in this PR itself, now that you've already clubbed typography and color.

2020-03-24 21:59 UTC, silvinabt87 commented
@dhruvkb I've created unit tests for spacing.scss and pushed it to this PR. Let me know if it is possible to merge or if we need to make any further changes.

2020-03-26 20:43 UTC, dhruvkb approved these changes

2020-03-26 20:44 UTC, merged