Add image component
cc-archive/vocabulary-legacy pull request #208
Opened 2020-03-19 09:52 UTC by Dhruvi16

**Fixes**

Fixes #58 

**Description**

This adds an image component to the vocabulary. The image is as per DL instructions.

**Type of PR** 
This PR is a [featurer].

**Screenshots**

![image](https://user-images.githubusercontent.com/34674462/77054152-658f1000-69f5-11ea-9067-607976f0670f.png)

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-19 09:54 UTC, Dhruvi16 commented
As stated by @dhruvkb this is blocked from merging till creativecommons/fonts#8 and creativecommons/fonts#12 remain unresolved.

2020-03-19 09:55 UTC, Dhruvi16 commented
So far added the Image name label when in hover state. The icons are yet to be imported.

2020-03-27 07:00 UTC, dhruvkb requested changes
Two spaces for indentation please.

2020-03-27 07:00 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +                <p class=" padding-vertical-small padding-horizontal-normal">Image name</p>
If you sourced the image from somewhere, it would be better if you actually attributed the creator here.

2020-03-27 07:00 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +                <i class="icon cc-nc padding-right-small"></i>
Wrap them in a `<div class="has-text-black">`. All icons have white circles, so how would you implement that?

2020-03-27 07:00 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +            <img src="images/image.jpg">
`image.jpg` is too generic. Try using the title of the image as the filename. Also put them in a `demo/` directory that doesn't get collected by Webpack and add to the package size.

2020-03-27 07:00 UTC, dhruvkb commented on src/styles/vocabulary.scss
> +@import "./image.scss";
Image shouldn't lie in the `// Form` section. I think `// Patterns` would be a better section for this.

2020-03-28 03:42 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +If it is placed as a single image within the content, it should follow the grid columns.
To define a new paragraph, you'll need another newline before this.

2020-03-28 04:37 UTC, dhruvkb requested changes
- Replace the opacity change on hover with sliding in animations from the top and bottom. 
- Reduce the size of the image to something like ~396px x 250px to make it similar to Figma. 
- Pay attention to the Figma styles in fonts and spaces. 
- And also make the other minor changes I pointed out below.

2020-03-28 04:37 UTC, dhruvkb commented on src/styles/image.scss
> +    background-color: #ffffff;
The white bleeds out a little from the top and bottom edges of the icons. I'd recommend using a gradient to only cover a part of the icon.
```suggestion
    background-image: radial-gradient(circle, $color-white 60%, transparent 60%);
```

2020-03-28 04:37 UTC, dhruvkb commented on src/styles/image.scss
> +    margin-bottom: 0.5em;
The captions have a font-weight of 600.

2020-03-28 04:37 UTC, dhruvkb commented on src/styles/image.scss
> +    opacity: 0;
The icons are supposed to be bigger. `1.625rem` to be exact.

2020-03-28 04:37 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +        <i class="icon cc-nc margin-right-small"></i>
The whitespaces are adding extra space to the half `em` margin.
<img width="584" alt="Screenshot 2020-03-28 at 9 56 23 AM" src="https://user-images.githubusercontent.com/16580576/77814794-71a45d00-70da-11ea-87d8-f1be58555b68.png">

2020-03-28 04:37 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +    <p>Photo by <a href="https://en.wikipedia.org/wiki/User:Newton2">Newton2</a> / <a href="https://creativecommons.org/licenses/by/2.5/">CC BY</a></p>
```suggestion
    <p><a href="<[insert actual link here]">Broadway Tower</a> by <a href="https://en.wikipedia.org/wiki/User:Newton2">Newton2</a> / <a href="https://creativecommons.org/licenses/by/2.5/">CC BY</a></p>
```

2020-03-28 04:37 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +        <p class=" padding-vertical-small padding-horizontal-normal caption">Image name</p>
```suggestion
        <p class=" padding-vertical-small padding-horizontal-normal caption">Broadway Tower</p>
```

2020-03-28 04:37 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +  <Story name="Broadway Tower" parameters={{
```suggestion
  <Story name="Default" parameters={{
```

2020-03-28 04:37 UTC, dhruvkb commented on src/styles/image.scss
> +.image {
Being applied to a `div`, `.image` is technically a block element. `img`s are inline elements, so you'll need to change that in the class.

2020-04-02 13:44 UTC, Dhruvi16 commented
>     * Replace the opacity change on hover with sliding in animations from the top and bottom.
> 
>     * Reduce the size of the image to something like ~396px x 250px to make it similar to Figma.
> 
>     * Pay attention to the Figma styles in fonts and spaces.
> 
>     * And also make the other minor changes I pointed out below.

In the DL it is written - The image component is not restricted to a specific size; it must be used depending on the content type and its container.
If it is placed as a single image within the content, it should follow the grid columns.

So I was confused if giving a particular width and height would be restricting or not? I have the same question with icon size.

2020-04-02 13:46 UTC, Dhruvi16 commented on src/styles/image.scss
> +.image {
I do not get this. Could you please elaborate on it?
Thanks

2020-04-02 13:52 UTC, Dhruvi16 commented
Plus, I had a doubt regarding the animation of the image name section. It is at the bottom so I guess giving it an bottom to top effect would be more appropriate. Lemme know your take on this.

2020-04-02 13:55 UTC, Dhruvi16 commented on src/styles/image.scss
> +    margin-bottom: 0.5em;
Yeah, I removed it from the last version by mistake.

2020-04-02 14:29 UTC, dhruvkb commented on src/styles/image.scss
> +.image {
Give the actual image tag `img` inside the `div` a width of 100%. That will make sure it always takes up the full width of the `div` and then giving the `div` a width will automatically scale the image tag inside it. Also make the `div` display as `inline-block` which allows it to be inlined with content while also having fixed height and width.

2020-04-02 14:33 UTC, dhruvkb commented
> In the DL it is written - The image component is not restricted to a specific size; it must be used depending on the content type and its container.
> If it is placed as a single image within the content, it should follow the grid columns.
> 
> So I was confused if giving a particular width and height would be restricting or not? I have the same question with icon size.

I just wanted you to scale it down as in its present form it is too huge. Feel free to deviate from the Figma size (such as images that are vertically oriented or images that have ultrawide aspect ratios), just make them small enough so that the focus of the page is always on the element and not the image in the demo.

I'm assuming icon sizes would remain fixed as the values given in Figma, regardless of how big or small the image gets.

> Plus, I had a doubt regarding the animation of the image name section. It is at the bottom so I guess giving it an bottom to top effect would be more appropriate. Lemme know your take on this.

Yes, the image icons would slide out upwards, the caption of the image would slide out downwards.

2020-04-04 11:03 UTC, dhruvkb requested changes
You haven't really made the best use of Sass in your `.scss` file. It's plain old CSS. At the very least, nest your CSS so that the style effects do not bleed into the other components.

2020-04-04 11:14 UTC, dhruvkb requested changes

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +  -o-transition: all 0.2s linear;
Transitions are fairly standard now. No need to use vendor prefixes.

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +  transition: all 0.2s linear;
Never transition `all`. It can have unpredicatable consequences. In this case translate just the `transform` CSS property.

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +  height: 0px;
Use `transform: translateY` to hide and show. Manipulating height makes the animation look strage, af it was loading rather than moving in.

```css
transform: translateY(-100%); /* to hide */
```

```css
transform: translateY(0); /* to reveal */
```

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +.image-icons {
A lot of the properties such as `position` and `left` are common with the class `.image-details`. Club those together.

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +  border-radius: 50%;
With PR #295 merged, you can use the class `.has-background-white` on the CC license icons to achieve this effect. This won't be needed here.

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +  width: 1.625rem !important;
Since they're fonts, use `font-size` to change icon sizes, not width.

2020-04-04 11:14 UTC, dhruvkb commented on src/styles/image.scss
> +.image {
This is still to be implemented?

2020-04-04 11:14 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +If it is placed as a single image within the content, it should follow the grid columns.
So is this?

2020-04-04 11:14 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +        <i class="icon cc-nc"></i>
Try the class `.has-background-white`.

2020-04-04 13:31 UTC, Dhruvi16 commented
> You haven't really made the best use of Sass in your `.scss` file. It's plain old CSS. At the very least, nest your CSS so that the style effects do not bleed into the other components.

My apologies for this. I will update and rewrite it so I can make the best use of Sass.

2020-04-04 13:36 UTC, Dhruvi16 commented on src/stories/image.stories.mdx
> +If it is placed as a single image within the content, it should follow the grid columns.
I did add a new line before that.

2020-04-04 13:42 UTC, Dhruvi16 commented on src/styles/image.scss
> +  border-radius: 50%;
The white is bleeding out the icons here.

2020-04-06 08:33 UTC, Dhruvi16 commented on src/styles/image.scss
> +.image {
Yes! I interpreted it the wrong way.

2020-04-06 09:14 UTC, Dhruvi16 commented
> With PR #295 merged, you can use the class `.has-background-white` on the CC license icons to achieve this effect. This won't be needed here.

The white is still bleeding here so I have not made this change.

2020-04-07 20:46 UTC, dhruvkb commented
> The white is still bleeding here so I have not made this change.

I couldn't reproduce this. 
![Screen Shot 2020-04-08 at 02 15 40](https://user-images.githubusercontent.com/16580576/78717839-db283500-793e-11ea-8a53-02e2d0ecde30.png)

Maybe open an issue in [creativecommons/fonts](https://github.com/creativecommons/fonts) if you can consistently reproduce this after confirming that you're on the latest version of all packages and dependencies.

2020-04-07 21:01 UTC, dhruvkb approved these changes

2020-04-07 21:06 UTC, merged