Add storyshots
cc-archive/vocabulary-legacy pull request #210
Opened 2020-03-19 10:18 UTC by Tanuj22

**Fixes**

Fixes #165 by @dhruvkb 

**Description**
Add Shortshots 

**Type of PR**

This PR is a feature.

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ ] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-19 10:23 UTC, Tanuj22 commented
@dhruvkb I have taken the reference of [chooser](https://github.com/creativecommons/chooser) repo to configure Jest for ES6 syntax but getting the following error. What seems to cause the error?
![Screenshot from 2020-03-19 15-51-27](https://user-images.githubusercontent.com/42486853/77057190-9a9d6180-69f9-11ea-8b35-34ad0a226f57.png)

2020-03-20 06:35 UTC, dhruvkb requested changes
Is the PR taking any shots at the moment?

2020-03-20 06:35 UTC, dhruvkb commented on package.json
> +    "test": "jest",
The name "test" is already taken for running True tests. You could use a name like `shots` or similar.

2020-03-20 06:35 UTC, dhruvkb commented on package.json
> +  }
Would prefer configurations to not be in `package.json` and rather be in a separate file.

2020-03-20 06:37 UTC, dhruvkb commented on package.json
> +    "test": "jest",
Or if you could run Storyshots with the same command (while not disturbing the current setup with True), that would be cool too.

2020-03-20 06:44 UTC, Tanuj22 commented
It's not taking any shots currently. After adding `.babelrc` it was able to recognize ES6 syntax in `storybook.test.js` but not in other files. Can't seem to figure out why.

2020-03-20 06:45 UTC, Tanuj22 commented on package.json
> +  }
Okay

2020-03-20 06:46 UTC, Tanuj22 commented on package.json
> +    "test": "jest",
Doing this runs all the files with `test.js` extension.

2020-03-28 20:06 UTC, dhruvkb commented
@Tanuj22 with the merge of #226, we got `import` statements working (to some extent). Update your branch to see if you can make it work now.

2020-03-28 20:07 UTC, dhruvkb requested changes
Retry with PR #227 merged.

2020-03-30 22:47 UTC, Tanuj22 commented
@dhruvkb I tried again but still the same error. I took the reference of how its setup in one of the [example](https://github.com/storybookjs/storybook/tree/master/examples/html-kitchen-sink) in Storybook repo. Can't figure out whats missing.

2020-04-01 14:42 UTC, Tanuj22 commented
I was able to fix the issue with import statements. Now stuck with this error :/
![Screenshot from 2020-04-01 20-11-53](https://user-images.githubusercontent.com/42486853/78150544-0dc0c200-7455-11ea-8058-f3b6c8d90655.png)

2020-04-01 21:23 UTC, Tanuj22 commented
@dhruvkb Was finally able to make it work. Please have a look

2020-04-04 13:21 UTC, dhruvkb reviewed
Why do the snapshot files have so many blank lines?

2020-04-04 13:26 UTC, Tanuj22 commented
Not really sure. I guess it may have something to do with converting the MDX files by `@storybook/addon-docs/jest-transform-mdx`

2020-04-05 19:15 UTC, dhruvkb commented
@Tanuj22 can we do something about it? A lot of the files are just blanks. Doesn't make much sense to have them then.

2020-04-05 19:21 UTC, Tanuj22 commented
@dhruvkb I was also disappointed by the results. I will try to find any solution and get back to you.

2020-04-11 19:44 UTC, Tanuj22 commented
@dhruvkb I can't find a solution to this. Maybe it's best to close the PR.

2020-04-12 03:46 UTC, dhruvkb commented
Let's not close it but rather get some help from the community.

2020-05-20 17:40 UTC, dhruvkb commented
This PR has been going stale from inactivity.

2020-05-20 17:40 UTC, closed without merging