updated License_badge
cc-archive/vocabulary-legacy pull request #217
Opened 2020-03-21 07:53 UTC by megha070

**Fixes**

Fixes #185  by @dhruvkb 

**Description**
Update license_badge.stories.mdx file so as to get correct code Previews

**Type of PR**
This PR is a hotfix.

**Technicalities**
Made use of mdxsource prop so as to get correct code sample

**Tests**

**Screenshots**

**Checklist:**
 
- [ x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x ] My pull request targets the `master` branch of the repository.
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-21 07:58 UTC, dhruvkb commented
Can't merge till #209 is merged.

2020-03-21 12:09 UTC, dhruvkb commented
@megha070 this is unblocked now, but still has conflicts.

2020-03-21 12:22 UTC, megha070 commented
![image](https://user-images.githubusercontent.com/40516822/77226224-a83f1c80-6b9c-11ea-8775-6171f7a34e9f.png)
Ran it locally! It is working fine. Could you please tell me how do I resolve these?

2020-03-21 13:12 UTC, dhruvkb requested changes
This seems wrong. Check if the MDX source code appears correctly under the badges.

2020-03-21 13:12 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +<Preview mdxSource={licenseSVG("big", "by"),licenseSVG("small", "by")}>
I'm not sure you can write comma separated `mdxSource`.

2020-03-21 18:21 UTC, dhruvkb requested changes

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +import { Meta, Story, Preview } from "@storybook/addon-docs/blocks";
Don't replace `'` with `"`.

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +
Why?

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +    <div>${licenseSVG("small", "by")}</div>
This change is meaningless.

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +<Preview mdxSource={`${licenseSVG("big", "by")}\n${licenseSVG("small", "by")}`}>
Use single quotes.
```suggestion
<Preview mdxSource={`${licenseSVG('big', 'by')}\n${licenseSVG('small', 'by')}`}>
```

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +     href="@creativecommons/vocabulary/assets/license_badges/big/by.svg#layer1">
Remove the stray space.

2020-03-21 18:21 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
The above feedback applies to all stories below as well.

2020-03-24 20:31 UTC, dhruvkb requested changes

2020-03-24 20:31 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';
Drop the semicolon at the end.

2020-03-24 20:31 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +    <div>${licenseSVG('small','by')}</div>
These lines should not be appearing as changed. Make them the same as they were before.

2020-03-24 20:31 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +  <use href="@creativecommons/vocabulary/assets/license_badges/big/by.svg#layer1">
This change should be undone.

2020-03-24 20:31 UTC, dhruvkb commented on src/stories/license_badge.stories.mdx
> +  <use href="@creativecommons/vocabulary/assets/license_badges/small/by.svg#layer1">
This change should be undone.

2020-03-28 16:54 UTC, dhruvkb approved these changes

2020-03-28 16:55 UTC, merged