added github action for Pull Requests
cc-archive/vocabulary-legacy pull request #248
Opened 2020-03-25 21:48 UTC by megha070

**Fixes**

Fixes #245  by @dhruvkb 

**Description**
added Github action for Pull Requests

**Type of PR**

This PR is a feature.

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x ] My pull request targets the `master` branch of the repository.
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-03-25 21:49 UTC, megha070 commented
@dhruvkb I am not sure if this is the right way to do this, also I don't have idea how do I test this code.

2020-03-26 01:51 UTC, dhruvkb requested changes

2020-03-26 01:51 UTC, dhruvkb commented on .github/workflows/pull_request.yml
> +      uses: skx/github-action-tester@master
It might work but I wouldn't prefer using images from an unreliable source such as skx. They seem to be an individual and their action doesn't have many stars either: https://github.com/skx/github-action-tester.

2020-03-26 08:41 UTC, megha070 commented on .github/workflows/pull_request.yml
> +      uses: skx/github-action-tester@master
Will see an alternative for this!

2020-03-27 07:23 UTC, dhruvkb commented
@megha070 you cannot lift jobs from the other two issues and their PRs. They were using GitHub actions for very different purposes as compared to us. I only linked to them so that you could see how to write the GitHub Action config files.

2020-03-27 07:31 UTC, dhruvkb commented
[This post](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) has some good examples for our particular task.

2020-03-27 08:28 UTC, megha070 commented
Thank you, will refer them.

2020-03-28 13:09 UTC, dhruvkb requested changes
I'm not clear as to what the purpose of `.github/run-tests.sh` is. Also I tried the workflow locally and it doesn't seem to work.

2020-03-28 13:19 UTC, megha070 commented
I came across an article which stated that run-tests.sh file is triggered and checks are made depending on test file.

2020-03-28 13:29 UTC, dhruvkb commented
Can you link to that article?

2020-03-31 12:27 UTC, megha070 commented
https://github.com/skx/github-action-tester, Sorry for the delay. I somehow missed this.

2020-04-07 20:15 UTC, dhruvkb commented
This has been accomplished by #261.

2020-04-07 20:15 UTC, closed without merging