Added configuration yml file for github actions
cc-archive/vocabulary-legacy pull request #261
Opened 2020-03-27 15:03 UTC by hitesh1157

## Fixes

Related #245  by @dhruvkb 

## Description

Picking up from the description in the issue:
> GitHub Actions offers a free and unlimited CI package for open source repositories with features rivalling and integrations surpassing those offered by CircleCI. The goal is to move our CI pipeline from CircleCI to GitHub Actions to run tests on all branches and pull requests.

This PR contains the github actions workflow configuration yml file. The workflow executes three jobs post every push or pull request. These jobs are **lint**, **build** and **test** similar to those in CircleCI configuration.

## Technical details
NPM dependencies are cached on pre-execution of **lint** job in ~/.npm directory and retrieved on execution of subsequent jobs. [Source](https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions#example-caching-dependencies).

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-03-28 12:51 UTC, dhruvkb requested changes
This is good work. A couple of improvements though:
- the directory should be `.github/workflows/`
- the file extension should be `.yml` (I know it's wrong but that's what is used across the project)
- the reviews following this comment

2020-03-28 12:51 UTC, dhruvkb commented on .github/workflow/config.yaml
> +        CI: true
Isn't this the same as `test`?

2020-03-28 12:51 UTC, dhruvkb commented on .github/workflow/config.yaml
> +        node-version: '8.12.0'
Could do with Node v12. v8 is way too old.

2020-03-28 12:51 UTC, dhruvkb commented on .github/workflow/config.yaml
> +      uses: actions/setup-node@v1
@megha070 a good takeaway would be the use of predefined actions. See [GitHub Actions](https://github.com/actions).

2020-03-28 12:51 UTC, dhruvkb commented on .github/workflow/config.yaml
> +          ${{ runner.OS }}-
I'm not entirely sure what this does, but does running cache here preserve `node_modules/` for the tasks defined below?

2020-03-28 12:51 UTC, dhruvkb commented on .github/workflow/config.yaml
> +        CI: true
Always leave a newline at the end of a file.

2020-03-28 13:18 UTC, megha070 commented on .github/workflow/config.yaml
> +      uses: actions/setup-node@v1
Sure will go through this. Thanks a ton.
@dhruvkb and @hitesh1157

2020-03-28 13:32 UTC, hitesh1157 commented on .github/workflow/config.yaml
> +        CI: true
Indeed it is. I thought of "testing" as in testing CI workflow based on assertion of every job expected outcome and their actual result. That's what created a confusion.

But now it's clear to me.

2020-03-28 13:34 UTC, hitesh1157 commented on .github/workflow/config.yaml
> +        node-version: '8.12.0'
Any specific version you have in mind?

2020-03-28 13:40 UTC, krhitesh commented on .github/workflow/config.yaml
> +        CI: true
Done.

2020-03-28 14:10 UTC, hitesh1157 commented on .github/workflow/config.yaml
> +          ${{ runner.OS }}-
It didn't at first but after 5a75d27 it does. See: 
![Screenshot from 2020-03-28 19-39-39](https://user-images.githubusercontent.com/25616334/77824909-ec499880-712b-11ea-978e-acab013d8028.png)

2020-03-28 14:11 UTC, hitesh1157 commented on .github/workflow/config.yaml
> +        node-version: '8.12.0'
Done.

2020-03-28 15:07 UTC, hitesh1157 commented
@dhruvkb Please take a look.

2020-04-04 16:55 UTC, dhruvkb approved these changes

2020-04-04 17:06 UTC, merged

2021-07-06 15:45 UTC, brylie commented
@all-contributors please add @krhitesh for infra, test