Remove Repetitive Code
cc-archive/vocabulary-legacy pull request #265
Opened 2020-03-28 20:13 UTC by megha070

## Fixes

Fixes #185  by @dhruvkb 

## Description
Removed repetitive code from cards.stories.mdx

## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-03-28 20:15 UTC, megha070 commented
![image](https://user-images.githubusercontent.com/40516822/77832843-dacdb400-715e-11ea-9274-449316084154.png)
@dhruvkb can you please help me rectify this error

2020-03-28 20:20 UTC, dhruvkb commented
This error occurs if there is a blank line inside your story. MDX treats blank lines as paragraph breaks so it breaks your story into two parts.

2020-03-28 20:44 UTC, megha070 commented
@dhruvkb Can you please check my code, Maybe I am making some mistake in writing code? The error still persists.

2020-03-28 21:06 UTC, dhruvkb requested changes
I know your work on the PR is not done, but I'll just point this bug now itself.

2020-03-28 21:06 UTC, dhruvkb commented on src/stories/cards.stories.mdx
> +
There are a lot of differences between PostHorizontal and PostVertical. This function is not serving both purposes correctly. Closely examine the differences in the HTML of both stories.

2020-03-28 21:06 UTC, dhruvkb commented
@megha070 it's working on my computer now. Let me know if this fixes the issue on your machine as well.

2020-03-28 21:15 UTC, megha070 commented
Sure Thanks a ton.

2020-03-28 21:28 UTC, megha070 commented
Thank you so much @dhruvkb, It works on my system as well.

2020-03-28 22:29 UTC, megha070 commented
@dhruvkb Please let me know if there is scope of improvement and removing redundant code further.

2020-03-28 23:12 UTC, megha070 commented
![image](https://user-images.githubusercontent.com/40516822/77835919-97cc0a80-7177-11ea-9737-2353c5c38e3c.png)
It was working fine a while ago, but now this error show up.

2020-03-29 19:57 UTC, megha070 commented
@dhruvkb rectified it, working fine on local.

2020-04-19 04:17 UTC, dhruvkb requested changes
Please resolve conflicts.

2020-08-11 08:42 UTC, megha070 commented
@dhruvkb Could you please tell me if I need to improvise this?

2020-09-07 04:05 UTC, zackkrida commented
@dhruvkb I forgot to mention this since you missed the last sprint planning—could you revisit this PR this week? Whatever way we move forward with it, it would be nice to resolve. Thanks!

2020-09-07 04:07 UTC, dhruvkb commented
Sure, this PR always falls out of my schedule. I'll resolve this today.

2020-09-08 05:31 UTC, dhruvkb approved these changes
Although code style could use some improvement, the changes in the PR are significant to overlook those for the time being.

2020-09-08 05:33 UTC, merged