Added Dockerfile and Docker Compose configuration file
cc-archive/vocabulary-legacy pull request #271
Opened 2020-03-29 13:54 UTC by hitesh1157

## Fixes

Fixes #26  by @dhruvkb 

## Description

This PR addes the Dockerfile and docker compose file in accordance with the current state and eventually push for it to the the standard development environment for the project.

## Tests
```
# Build the docker image
docker build . -t ccvocabulary:latest

# Run via docker compose
docker-compose up
```
Visit `localhost:8080` to test. Also documentation built via `npm run build:documentation` is not served currently.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-03-29 13:57 UTC, hitesh1157 commented
@dhruvkb Please take a look.

2020-03-29 16:50 UTC, dhruvkb requested changes
You missing running the SCSS compilation service `npm run watch` in conjuction with Storybook in `docker-compose.yml`.

2020-03-29 16:50 UTC, dhruvkb commented on Dockerfile
> +FROM node:12.16.1-alpine
You can just use the [Dockerfile from `creativecommons/vue-vocabulary`](https://github.com/creativecommons/vue-vocabulary/blob/master/Dockerfile).

2020-03-29 16:50 UTC, dhruvkb commented on docker-compose.yml
> +  website:
We're serving the Storybook so that would be a better name for the service.

2020-03-29 16:50 UTC, dhruvkb commented on docker-compose.yml
> +    image: ccvocabulary:latest
Add a `restart` key.

2020-03-29 16:50 UTC, dhruvkb commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
One-off jobs like building should not be performed using Docker Compose. Docker Compose is for running persistent services.

2020-03-29 16:51 UTC, dhruvkb requested changes

2020-03-29 16:51 UTC, dhruvkb commented on docker-compose.yml
> +    image: ccvocabulary:latest
Name the image "vocabulary".

2020-03-29 16:52 UTC, dhruvkb commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
You can write a bash script that spins off a container with the "vocabulary" image and runs the build process inside it, terminating the container when done.

2020-03-30 04:52 UTC, hitesh1157 commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
Is there a need to run `build:documentation` within the container?

2020-03-30 05:02 UTC, hitesh1157 commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
> You missing running the SCSS compilation service `npm run watch` in conjuction with Storybook in `docker-compose.yml`.

Also, taking a look at `docker-compose.yml` in [vue-vocabulary](https://github.com/creativecommons/vue-vocabulary), I think `npm run storybook` also watches for file changes as well. Isn't it?

2020-03-30 05:04 UTC, hitesh1157 commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
> Is there a need to run `build:documentation` within the container?

I could just put `npm run build:documentation` inside Dockerfile in that case.

2020-03-30 05:52 UTC, dhruvkb commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
In Vue Vocabulary, Storybook autoreloads when styles change. In Vocabulary, it doesn't. So you'll have to run the watch service alongside.

If you put `npm run build:documentation` inside the container, won't that build everytime we bring up the container?

2020-03-30 07:46 UTC, hitesh1157 commented on docker-compose.yml
> +      - node_modules:/codebase/node_modules
Is it necessary to use `npm run build: documentation` in docker? What's its significance in docker if we are serving via storybook and watch command?

2020-03-31 07:42 UTC, hitesh1157 commented
@dhruvkb Please take a look

2020-04-01 16:48 UTC, dhruvkb approved these changes

2020-04-01 16:49 UTC, merged

2021-07-06 15:48 UTC, brylie commented
@all-contributors please add @krhitesh for platform, code