Ensure single source of truth for instructions
cc-archive/vocabulary-legacy pull request #272
Opened 2020-03-29 19:19 UTC by dhruvkb

## Description
Remove the hardcoded instructions with a single source of truth locating in the Storybook itself.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-03-30 19:46 UTC, brenoferreira commented on .storybook/meta/contribution.stories.mdx
> +| **Translate** | If you speak a language other than, and in addition to, English, you can help make the project accessible to your community with your words. |
Vocabulary doesn't include any localized assets. Is this necessary?

2020-03-30 19:51 UTC, brenoferreira requested changes

2020-03-30 19:51 UTC, brenoferreira commented on .storybook/meta/contribution.stories.mdx
> +```
Same git comment here

2020-03-30 19:51 UTC, brenoferreira commented on .storybook/meta/contribution.stories.mdx
> +```
I don't think we need to add a git tutorial on how to clone a repo. That's already widely available elsewhere

2020-03-30 21:28 UTC, hugosolar approved these changes

2020-03-30 21:28 UTC, hugosolar commented on .storybook/meta/contribution.stories.mdx
> +```
I'm ok with this, a lot of repos (even [bootstrap](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md) or [foundation](https://github.com/zurb/foundation-sites-6)) use it this way. Also, I think it's a good way to show contributors how exactly they should start.

2020-03-31 03:57 UTC, dhruvkb commented on .storybook/meta/contribution.stories.mdx
> +| **Translate** | If you speak a language other than, and in addition to, English, you can help make the project accessible to your community with your words. |
It's from the Vue Vocabulary days, I'll drop that.

2020-03-31 03:59 UTC, dhruvkb commented on .storybook/meta/contribution.stories.mdx
> +```
A couple of contributors have their forks gone outdated and so every PR they make is out of date with `origin/master`. I've given these commands over Slack to three people.

2020-03-31 04:03 UTC, dhruvkb commented on .storybook/meta/contribution.stories.mdx
> +```
Two contributors tried pushing directly to the base repo and got 403 errors. They didn't know about forking. These rules were written for the lowest common denominator of the contributors.

2020-03-31 12:06 UTC, brenoferreira commented on .storybook/meta/contribution.stories.mdx
> +```
I would prefer to link to the official Github documentation instead of duplicating it here. It's much more comprehensive and it's localized in a few different languages

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

2020-03-31 15:24 UTC, dhruvkb commented on .storybook/meta/contribution.stories.mdx
> +```
Addressed in 9b966c9.

2020-03-31 15:24 UTC, dhruvkb commented on .storybook/meta/contribution.stories.mdx
> +```
Addressed in 9b966c9.

2020-03-31 16:02 UTC, dhruvkb commented
@brenoferreira made your suggested changes.

2020-03-31 17:59 UTC, brenoferreira approved these changes

2020-03-31 18:44 UTC, merged