Button mdx source
cc-archive/vocabulary-legacy pull request #288
Opened 2020-03-30 15:38 UTC by jahnvigupta

## Fixes

Fixes #185 by @dhruvkb 

## Description

Reduces code and adds mdx source to Button.stories.mdx.
## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-04-04 17:45 UTC, dhruvkb requested changes

2020-04-04 17:45 UTC, dhruvkb commented on src/stories/buttons.stories.mdx
> + return `<button class="${buttonClass}" height="100px">Button</button>`
Your function doesn't produce examples as they were before, go through the old HTML and new HTML carefully to see the difference.

2020-04-04 17:45 UTC, dhruvkb commented on src/stories/buttons.stories.mdx
> +      ${buttonClass('button')}
Fix indentation.

2020-04-19 15:45 UTC, dhruvkb requested changes
@jahnvigupta have you even seen what you've written here? As far as I can tell, this file contains the same thing twice.

2020-04-19 17:49 UTC, jahnvigupta commented
@dhruvkb I am sorry, maybe I just pasted the code without removing the earlier code. Sorry for the inconvenience.

2020-08-05 14:12 UTC, dhruvkb approved these changes

2020-08-05 14:28 UTC, merged