Add the Vocabulary overview document to the storybook
cc-archive/vocabulary-legacy pull request #298
Opened 2020-04-03 21:24 UTC by dhruvkb

## Description
This PR adds the Vocabulary Overview document discussed in Google Docs as an MDX document in the Vocabulary storybook. This will increase transparency in the processes behind Vocabulary while also making it possible to trace the history of the document as it evolves with Vocabulary.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-04-05 12:56 UTC, hugosolar approved these changes

2020-04-06 12:33 UTC, brenoferreira approved these changes

2020-04-06 17:00 UTC, kgodey requested changes

2020-04-06 17:00 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +Director of product (**Anna**) is responsible for final review and sign-off on all design changes, prior to
this is a title, please capitalize Product

2020-04-06 17:00 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +Director of engineering (**Kriti**) is responsible for the technical architecture and project management of Vocabulary,
this is a title, please capitalize Engineering

2020-04-06 17:00 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +Community maintainer (**Dhruv**) is responsible for releasing new versions of Vocabulary, triaging issues, and managing
this is a title, please capitalize Maintainer

(Please do this for the rest as well, I'm not going to make comments for all of them)

2020-04-06 17:00 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +UX designer (**Francisco**) maintains the Figma Design Library, which is used for designing mockups. When experimenting
I think it would make sense to map titles to names somewhere else in the document so that we don't have to change them all over the place if we have an addition or change to who occupies what roles.

2020-04-06 17:00 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +- Francisco works with the developer to create high-fidelity mockups in Figma using Vocabulary components.
I think we should replace names with titles in this part of the doc.

2020-04-06 18:40 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +Director of product (**Anna**) is responsible for final review and sign-off on all design changes, prior to
Resolved in a61a744.

2020-04-06 18:40 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +Director of engineering (**Kriti**) is responsible for the technical architecture and project management of Vocabulary,
Resolved in a61a744.

2020-04-06 18:40 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +Community maintainer (**Dhruv**) is responsible for releasing new versions of Vocabulary, triaging issues, and managing
Resolved in a61a744.

2020-04-06 18:41 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +UX designer (**Francisco**) maintains the Figma Design Library, which is used for designing mockups. When experimenting
I made a table after the description of the roles to map who's holding what title.

2020-04-06 18:41 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +UX designer (**Francisco**) maintains the Figma Design Library, which is used for designing mockups. When experimenting
Resolved in a61a744.

2020-04-06 18:41 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +- Francisco works with the developer to create high-fidelity mockups in Figma using Vocabulary components.
Resolved in a61a744.

2020-04-06 19:22 UTC, kgodey approved these changes
Some minor text change suggestions, please fix and merge.

2020-04-06 19:22 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +and/or the **Community Manager** and makes a decision and communicates it on the
Manager --> Maintainer

2020-04-06 19:22 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +### Titles
I would call this "Roles"

2020-04-06 19:22 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +- The **UX designer** works with the developer to create high-fidelity mockups in Figma using Vocabulary components.
designer --> Designer

2020-04-06 19:22 UTC, kgodey commented on .storybook/meta/overview.stories.mdx
> +- The **UX designer** adds any new components used in the mockup to the Design Library.
designer --> Designer

2020-04-06 19:51 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +and/or the **Community Manager** and makes a decision and communicates it on the
Typo, fixed in fe168a6.

2020-04-06 21:22 UTC, merged