Setup CD using GitHub actions
cc-archive/vocabulary-legacy pull request #321
Opened 2020-04-16 14:51 UTC by SaurabhAgarwala

## Fixes

Fixes #121 by @dhruvkb 

## Description
This PR adds a new workflow for Continuous Deployment using Github Actions which will push the updated packages to npm when a new release is published.

## Technical details

Please note that the NPM Authentication Token has to be stored as a GitHub secret by the name `NPM_TOKEN` for this workflow to complete successfully

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-04-16 15:47 UTC, dhruvkb requested changes
We don't need to repeat the CI workflow here. The setup, build and deploy jobs should suffice.

2020-04-16 15:51 UTC, dhruvkb commented
@kgodey could you [add the secret](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets) for NPM_TOKEN in Settings for all three repos?

2020-04-16 17:15 UTC, dhruvkb requested changes

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +    types: [published]
Lists are specified with `-` in YML

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +    types: [published]
```suggestion
    types: 
    - published
```

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +        run: npm install --no-audit
De-indent by 2 spaces.
```
key:
- val
- val
```

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +
End files with a single newline.

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +      run: npm run build
Sorry for not noticing this before but this is also not required because building is already a step in deployment.

2020-04-16 17:15 UTC, dhruvkb commented on .github/workflows/cd.yml
> +      run: npm run build
And if there is a single task, setup also becomes pointless.

2020-04-16 17:24 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +    types: [published]
I just checked, actually, both are valid ways for specifying the type of events that will trigger the workflow. And in the [official documentation](https://help.github.com/en/actions/reference/events-that-trigger-workflows) they have followed this convention. So shall I still replace it?

2020-04-16 17:39 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +
I think just the End of File symbol is getting rendered separately. The file ends on line 86 only. I have checked it in my local editor as well.

2020-04-16 18:16 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +      run: npm run build
Yes, I agree now. I was also thinking about it while coding this, but then I saw the [ci.yml](https://github.com/creativecommons/vocabulary/blob/master/.github/workflows/ci.yml) file and saw it repeated. But I just realized that there it makes sense as the `setup` job will help in caching and also if the `setup` job itself fails, then other jobs won't run only.

Also, I am removing the caching part as I just [found](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) that cache can only be accessed in workflows triggered by `push` and `pull_request` events and not in `release` event.

2020-04-17 00:47 UTC, dhruvkb commented on .github/workflows/cd.yml
> +    types: [published]
Just for consistency with the other lists we have used, please do change it.

2020-04-17 00:50 UTC, dhruvkb commented on .github/workflows/cd.yml
> +      run: npm run build
Setup was meant to
- act as a fail-fast incase there was a problem with npm dependencies
- cache dependencies for the other three tasks
If there as just one task, these use-cases become irrelevant.

2020-04-17 07:56 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +    types: [published]
Sure, I will change it now

2020-04-17 11:10 UTC, dhruvkb requested changes

2020-04-17 11:10 UTC, dhruvkb commented on .github/workflows/cd.yml
> +        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Publishing to `npm` requires a couple more steps. See [`deploy.sh`](https://github.com/creativecommons/vocabulary/blob/master/deploy.sh). You should run the script itself in this step.

2020-04-17 12:45 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Ok. Actually I was following [this](https://help.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) and these steps were not there. But, I will update the PR now. Thanks for pointing out.

Also, once this PR is approved, I will update the other one with the required changes.

2020-04-17 15:01 UTC, dhruvkb approved these changes
From the looks of it, it appears that it would work as expected. Just waiting for the `NPM_TOKEN` to be added and then we can test it.

2020-04-21 18:56 UTC, kgodey commented
@dhruvkb I added the token.

2020-04-22 10:01 UTC, merged