Add icons to Footer and change text
cc-archive/vocabulary-legacy pull request #340
Opened 2020-04-23 15:29 UTC by krysal

## Fixes

Fixes #334 by @panchovm and #339 by @makkoncept

## Description
Add missing icons for social networks and attribution. Also change text of icons authorship.

## Technical details

## Screenshots
![footer-updated](https://user-images.githubusercontent.com/9145885/80117368-1d639000-8555-11ea-9d79-a258e630cd42.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-04-24 05:52 UTC, dhruvkb approved these changes
@krysal can you please also update the snapshot for the Footer?

2020-04-24 21:15 UTC, krysal commented
Sure, so are the changes on Footer ok?

2020-04-27 13:59 UTC, krysal commented
@dhruvkb snapshot updated. I reduced the screenshot area to just the footer element, as suggested in #328.
Lastly, I believe there should be a break of line <br> between the email and the phone number to avoid what happens on wide screens, see screenshots:
![footer](https://user-images.githubusercontent.com/9145885/80380021-f36bdf80-886c-11ea-99fd-a99f00ecc445.png)
![Captura de pantalla de 2020-04-27 09-30-35](https://user-images.githubusercontent.com/9145885/80380077-0aaacd00-886d-11ea-949e-1b64ab44625e.png)

2020-05-02 04:17 UTC, dhruvkb requested changes
> Lastly, I believe there should be a break of line between the email and the phone number to avoid what happens on wide screens

Yes. Good find @krysal! Please update this in the code and the screenshots.

2020-05-03 01:18 UTC, krysal commented
@dhruvkb Done. To update the snapshot, I have to change the file permissions in my local environment; otherwise I get a `permission denied` error as in `vocabulary-ci / Snapshot tests`, not sure what is the right way to do it.

2020-05-20 17:58 UTC, dhruvkb commented on tests/snapshot/footer.test.js
> +    expect(image).toMatchImageSnapshot({
These were unnecessary.

2020-05-20 18:21 UTC, dhruvkb approved these changes

2020-05-20 18:22 UTC, merged