Specify registry-url and scope in CD workflow
cc-archive/vocabulary-legacy pull request #362
Opened 2020-05-11 19:42 UTC by SaurabhAgarwala

## Fixes

Fixes #349 by @SaurabhAgarwala 

## Description

The CD workflow currently present is failing. On looking into the possible solutions for the problem, specifying the `registry-url` and the `scope` may solve the problem. This PR adds both of these parameters.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-11 19:43 UTC, SaurabhAgarwala commented
Please review it @brenoferreira @dhruvkb

2020-05-21 13:48 UTC, dhruvkb commented on .github/workflows/cd.yml
> +        scope: creativecommons
Are these needed? As far as I can tell from the [`action.yml` file](https://github.com/actions/setup-node/blob/master/action.yml), both are optional fields.

2020-05-21 13:49 UTC, dhruvkb commented on .github/workflows/cd.yml
> +        scope: creativecommons
We're not using a scoped registry, `@creativecommons/vocabulary` is hosted on the public `npm` registry.

2020-05-21 19:15 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +        scope: creativecommons
I looked into many examples for CD, and in all of them I found the `registry-url` specified. Also, as specified in the link shared by you, I think this field will be requried in our case for authenticating and reading from `env.NODE_AUTH_TOKEN`. From what I understand, it is optional in cases when we don't need to set up the registry for auth in the project-level `.npmrc` file.

2020-05-21 19:24 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +        scope: creativecommons
> We're not using a scoped registry, `@creativecommons/vocabulary` is hosted on the public `npm` registry.

Please correct me if I am wrong. From what I understand from this [npm documentation](https://docs.npmjs.com/using-npm/scope.html), scopes are needed for grouping the packages of an organization. And as we refer this Vocabulary project in npm as `@creativecommons/vocabulary` (both in [URL](https://www.npmjs.com/package/@creativecommons/vocabulary) and while installing it) so this means `creativecommons` will be it's scope name. Also, I find [another package](https://www.npmjs.com/package/vocabulary) in npm by the same name as vocabulary, which I doesn't have any scope as it directly referred to as `vocabulary` both in it's URL as well as while installing.

2020-05-21 20:16 UTC, SaurabhAgarwala commented on .github/workflows/cd.yml
> +        scope: creativecommons
I am not being able to find any other possible reason for the error currently, so if we can just try it and see if it works. If it doesn't work even after this, then I will look into it further.

2020-05-23 18:51 UTC, dhruvkb approved these changes

2020-05-23 18:51 UTC, dhruvkb commented on .github/workflows/cd.yml
> +        scope: creativecommons
It makes sense, we'll merge it before the next release is about to come out.

2020-05-27 11:56 UTC, dhruvkb requested changes
@SaurabhAgarwala on further thought, can you move it to `creativecommons/fonts`? It's a much lower risk repository so we can make multiple iterations there.

2020-05-27 17:16 UTC, SaurabhAgarwala commented
> @SaurabhAgarwala on further thought, can you move it to `creativecommons/fonts`? It's a much lower risk repository so we can make multiple iterations there.

Yeah, definitely @dhruvkb. That's a great suggestion. I will make the corresponding changes in the `fonts` repo soon, and make a PR for it.

2020-05-28 14:09 UTC, dhruvkb commented
Blocked while we test creativecommons/fonts#83 as a resolution of creativecommons/fonts#82.

2020-05-29 14:15 UTC, SaurabhAgarwala commented
@dhruvkb I have made the required changes

2020-05-29 16:02 UTC, dhruvkb approved these changes
Should work like creativecommons/fonts#86.

2020-05-29 16:05 UTC, merged