Svg update
cc-archive/vocabulary-legacy pull request #366
Opened 2020-05-13 18:03 UTC by kushaggarwal

## Fixes

Fixes #360 by @panchovm 

## Description

This PR aims at the updation of the current svg for various CC products

## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-16 09:09 UTC, kushaggarwal commented
Hello @dhruvkb 
I have updated all the product logos for the products mentioned in the figma design library
As per the old products there are certain other styles in which those were present earlier like certificates colorful
So, shall I remove all the related mdx stories from the current file
Thank you

2020-05-17 04:00 UTC, dhruvkb commented
Yes @kushaggarwal, remove the stories that have become irrelevant.

2020-05-19 15:22 UTC, kushaggarwal commented
Hello @dhruvkb 
Please find the updated logos for CC Products in the above linked pull request
Thank you

2020-05-20 17:36 UTC, dhruvkb requested changes
Some very minor changes and this is good to go.

2020-05-20 17:36 UTC, dhruvkb commented on src/assets/logos/products/state_of_the_commons.svg
> +</g>
@kushaggarwal a little bit of formatting such as indentation would help a lot here.

2020-05-20 17:36 UTC, dhruvkb commented on src/stories/logos.stories.mdx
Please remove inverted versions of lettermark and letterheart.

2020-05-20 17:36 UTC, dhruvkb commented on src/stories/logos.stories.mdx
Use the `plainText` function for them as well.

2020-05-21 13:41 UTC, dhruvkb requested changes
Also update the code pertaining to the CC Legal Database logo.

2020-05-21 15:10 UTC, kushaggarwal commented
Okay @dhruvkb 
Will update the following

2020-05-23 07:37 UTC, kushaggarwal commented
Hello @dhruvkb 
Please find the above changes related to CC Legal, Lettermark and Letterheart
Thanks

2020-05-23 14:40 UTC, dhruvkb approved these changes

2020-05-23 14:44 UTC, merged