Don't let the title in the image component to flow on multiple lines
cc-archive/vocabulary-legacy pull request #379
Opened 2020-05-15 13:57 UTC by LarrySul

## Fixes

![image stories](https://user-images.githubusercontent.com/29729601/82057992-092a3300-96bc-11ea-93df-ae71abe5da80.JPG)

Fixes #375  by @makkoncept 

## Description
If the title of the image is long enough, then it is displayed on multiple lines. This would not look very aesthetic for the images that are narrow and short.

## Alternative Solution
One alternative is to change the text-overflow to ellipsis. 

## Technical details

## Tests

## Screenshots

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-21 14:28 UTC, dhruvkb requested changes
A good way to approach this would involve:
- adding a class `is-ellipsised` in the SCSS file with the `text-overflow` property
- documenting the use of the class in the MDX story with an additional example

2020-05-21 14:28 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +      <div class="image-title" style="text-overflow: ellipsis">
It is generally considered bad practice to put styles in the HTML.

2020-05-21 17:13 UTC, LarrySul commented
@dhruvkb thanks for pointing out the change , implemented it already

2020-05-23 15:09 UTC, dhruvkb approved these changes

2020-05-23 15:16 UTC, merged