Text style and icon size are incorrect in Header component
cc-archive/vocabulary-legacy pull request #382
Opened 2020-05-15 15:54 UTC by LarrySul

## Fixes

![header-scss](https://user-images.githubusercontent.com/29729601/82070176-43033580-96cc-11ea-8ead-bb33dad57c54.JPG)

Fixes #374  by @panchovm 

## Description
The text style and its hover state, and the icon size don't follow the Design Library definition.

## Expected behavior

1. Text style should be font-size 16px, line-height 24px and letter spacing 2%.
2. During hover state, the text color changes from DarkGray to DarkSlateGray without an underline.
3. The icon size should be within 15px square.

## Technical details

## Tests

## Screenshots

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-28 22:07 UTC, dhruvkb requested changes

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +
Changes pertaining to the header should be placed inside the `.navbar` block below so that they don't affect other components.

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +  font-size: 15px;
Icons, by, default obey font-size rule of the parents and hardcoding the size should not be required.

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +  color: darkslategray;
Use color token `$color-dark-slate-gray`.

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +      font-size: 16px;
Never hardcode font-sizes. Use the corresponding size token from `typography.scss`.

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +      line-height:  24px;
Line height should be a fraction of the font-size and never an absolute pixel value. In this case
```
24px / 16px = 1.5
```
so
```suggestion
      line-height:  1.5;
```
should be right property.

2020-05-28 22:07 UTC, dhruvkb commented on src/styles/header.scss
> +      line-height:  24px;
@panchovm correct me if I'm wrong but in places where text doesn't span multiple lines, line height has no effect and we shouldn't be needing that property imo.

2020-05-29 15:39 UTC, LarrySul commented on src/styles/header.scss
> +  font-size: 15px;
noted

2020-05-29 15:40 UTC, LarrySul commented on src/styles/header.scss
> +  color: darkslategray;
done

2020-05-29 16:48 UTC, LarrySul commented on src/styles/header.scss
> +
alright @dhruvkb

2020-08-12 15:38 UTC, zackkrida approved these changes
hi @LarrySul thank you for this! the header looks much nicer without the underline. thanks for helping vocabulary match our Design Language better 🎉

2020-08-12 15:38 UTC, merged