Add breadcrumb story
cc-archive/vocabulary-legacy pull request #386
Opened 2020-05-16 07:47 UTC by Dhruvi16

## Fixes

Fixes #385  by @Dhruvi16 

## Description

## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-16 15:10 UTC, Dhruvi16 commented
I am not sure about the icon I used as the item separator, @hugosolar @dhruvkb could you please help me figure that out?
Thanks

2020-05-16 16:31 UTC, dhruvkb commented
@Dhruvi16 I think we can use either the chevron or the caret from [the icon font](https://cc-fonts.netlify.app/?path=/docs/vocabulary-icons--page#arrows). @panchovm can help us decide.

2020-05-18 13:56 UTC, panchovm commented
The component should have the icon, I am using `chevron-right`. I will add the component to the Design Library.

2020-05-20 17:20 UTC, dhruvkb requested changes
While most of these comments will seem nitpicking, please note that this is just to imbibe in you the code style that is being followed in the project.

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +
Change to a single line.

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +
Change to a single line.

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +  font-size: 13px;
Prefer using tokens such as `$font-size-caption`.

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +  line-height: 19px;
Use line heights as fraction of font-size so 19/13 = 1.4615384615.
```suggestion
  line-height: 1.4615384615;
```

@panchovm this is not the same as the other line heights which all use a constant ratio. Is that intentional?

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +  };
Scopes are never ended with semicolons.

2020-05-20 17:20 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +
Remove stray newlines at the start and end of blocks.

2020-05-20 17:20 UTC, dhruvkb commented on src/stories/breadcrumb.stories.mdx
> +export const Breadcrumb = () => `
Functions must follow lowerCamelCase.

2020-05-20 17:20 UTC, dhruvkb commented on src/stories/breadcrumb.stories.mdx
> +</Preview>
- If there is only one story, name it Default. 
- Pay close attention to line breaks and indentation.

```suggestion
<Preview mdxSource={breadcrumb()}>
  <Story name="Default" parameters={{
    design: figmaConfig('6368%3A9')
  }}>{
    breadcrumb()
  }</Story>
</Preview>
```

2020-05-21 05:53 UTC, Dhruvi16 commented on src/styles/breadcrumb.scss
> +  font-size: 13px;
I used caption but it gave me a different result than expected. Like font-weight was not same.

2020-05-21 05:55 UTC, Dhruvi16 commented on src/stories/breadcrumb.stories.mdx
> +</Preview>
Can you suggest any particular extension that can do this for me or the one you use for maintaining indentation?
Thanks in advance

2020-05-21 05:59 UTC, Dhruvi16 commented on src/styles/breadcrumb.scss
> +  font-size: 13px;
![image](https://user-images.githubusercontent.com/34674462/82528410-4c6e2100-9b56-11ea-9c40-66f8269396ad.png)

2020-05-21 13:28 UTC, dhruvkb commented on src/styles/breadcrumb.scss
> +  font-size: 13px;
$font-size-caption is just a font-size.
```scss
font-size: $font-size-caption;
```

2020-05-21 13:30 UTC, dhruvkb commented on src/stories/breadcrumb.stories.mdx
> +</Preview>
I use [WebStorm](https://www.jetbrains.com/webstorm/) as my IDE (paid software, free version if you have an .edu or .ac email address from your institute) and simultaneously keep an eye out for this manually too. You can setup similar tools in Visual Studio Code too.

2020-05-21 16:04 UTC, Dhruvi16 commented on src/styles/breadcrumb.scss
> +  line-height: 19px;
If that helps -
font-family: Source Sans Pro;
font-style: normal;
font-weight: 600;
font-size: 13px;
line-height: 19px;
This is in the design library.

2020-05-24 10:15 UTC, dhruvkb approved these changes

2020-05-24 10:21 UTC, merged