fix: changed underline color on hover
cc-archive/vocabulary-legacy pull request #389
Opened 2020-05-17 10:23 UTC by Dishebh

## Fixes

Fixes #371  by @panchovm 

## Description

Changed the underline color (on hover) of links to `color-tomato`

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-17 17:07 UTC, Dishebh commented
@dhruvkb @panchovm pls review. Thanks!

2020-05-28 21:30 UTC, dhruvkb reviewed
Can't review until we get some clarification.

2020-05-28 21:30 UTC, dhruvkb commented on src/styles/typography.scss
> +  text-decoration-color: $color-tomato;
Waiting for a reply on https://github.com/creativecommons/vocabulary/issues/371#issuecomment-635618597 so that we can fix the problem at the source.

2020-05-28 21:52 UTC, dhruvkb requested changes
The text-color of anchor tags becoming black is the core issue here. @panchovm's clarification means that the links should remain the same color as they were before, with just an underline added underneath them.

2020-05-28 21:52 UTC, dhruvkb commented on src/styles/typography.scss
> +  text-decoration-color: $color-tomato;
Now that we have that reply, this fix is not correct.

2020-08-14 17:14 UTC, zackkrida commented
Hi @Dishebh, what we really want here if for the color of `<a>` tags to be `$color-tomato` on hover. The underline will inherit that color. Please update or close this pr; thanks so much!

2020-08-14 23:27 UTC, zackkrida approved these changes
perfect, thanks!

2020-08-20 17:07 UTC, merged