Fix dynamic height for global menu
cc-archive/vocabulary-legacy pull request #413
Opened 2020-05-25 15:41 UTC by hugosolar

## Description
I've been dealing with this issue with the global menu, I modify the markup a little bit in order to get a dynamic height on the global menu. This is needed to adapt the menu to different screen resolutions

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-25 16:22 UTC, brenoferreira requested changes

2020-05-25 16:22 UTC, brenoferreira commented on src/styles/global_header.scss
> +  z-index: 90;
Does it need to be this high?

2020-05-25 16:22 UTC, brenoferreira commented on src/styles/global_header.scss
> +      max-height: 1000px;
This seems a bit arbitrary. Why 1000px? It's also in `px` not in `rem`

2020-05-25 16:22 UTC, brenoferreira commented on src/styles/global_header.scss
> +      .product-list {
Is it not possible to use the Bulma grid for this?

2020-05-25 16:26 UTC, hugosolar commented on src/styles/global_header.scss
> +      .product-list {
I can have more control over the responsive transform with css grid that's why I used it

2020-05-25 16:26 UTC, hugosolar commented on src/styles/global_header.scss
> +      max-height: 1000px;
It's an arbitrary long height, this makes the trick for height transition works on height modification. it can be in rem as well... I'll add it in rem

2020-05-25 16:28 UTC, hugosolar commented on src/styles/global_header.scss
> +  z-index: 90;
It works from 31, but I would like to be sure that stays always on top. I'll leave it on 90 for now

2020-05-26 17:26 UTC, brenoferreira approved these changes

2020-05-26 17:54 UTC, merged