Explain the usage of CC lettermark and logomark
cc-archive/vocabulary-legacy pull request #418
Opened 2020-05-27 16:50 UTC by kushaggarwal

## Fixes

Fixes #407 by @dhruvkb 

## Description

This PR aims at the addition of explanation for the icons present for CC Lettermark and Letterheart with there logos

## Technical details

## Tests

## Screenshots

![Screenshot 2020-05-27 at 10 18 20 PM](https://user-images.githubusercontent.com/44523552/83049082-3d143980-a068-11ea-80e2-758e544ea9a9.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-27 23:33 UTC, dhruvkb requested changes
There's a better way to do this.

2020-05-27 23:33 UTC, dhruvkb commented on src/stories/main_logos.stories.mdx
> +export const letterheartSvg = `<p>The icon for CC Letterheart can also found under icons for embedding in other places like buttons</p>
Since this is MDX we write documentation directly in the text. You can leave the `letterheartSvg` as it is and just write the documentation under the `<Preview>`.

2020-05-27 23:33 UTC, dhruvkb commented on src/stories/main_logos.stories.mdx
> +export const letterheartSvg = `<p>The icon for CC Letterheart can also found under icons for embedding in other places like buttons</p>
See the [Button story](https://github.com/creativecommons/vocabulary/blob/master/src/stories/buttons.stories.mdx) for example.

2020-05-28 17:55 UTC, kushaggarwal commented on src/stories/main_logos.stories.mdx
> +export const letterheartSvg = `<p>The icon for CC Letterheart can also found under icons for embedding in other places like buttons</p>
Okay @dhruvkb will follow accordingly

2020-05-31 16:32 UTC, kushaggarwal commented
Hello @dhruvkb 
Apologies for the delay
Please find the above pull request for the changes mentioned above
Thanks

2020-06-01 03:12 UTC, dhruvkb approved these changes

2020-06-01 03:13 UTC, merged