Add rounded image to the vocabulary.
cc-archive/vocabulary-legacy pull request #420
Opened 2020-05-27 19:57 UTC by Dhruvi16

## Fixes

Fixes #388 by @Dhruvi16 

## Description

Adds rounded image that is used in the new designs.

## Technical details

Adds a simple class for the effects.

## Screenshots

![image](https://user-images.githubusercontent.com/34674462/83066223-56c27a80-a082-11ea-8805-cb365bb2ab0c.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-05-28 12:29 UTC, hugosolar reviewed
just one comment added but it looks good!

2020-05-28 12:29 UTC, hugosolar commented on src/styles/image.scss
> +  min-width: 60px;
Why do you think it's necessary to set a min-width?

2020-05-28 12:59 UTC, hugosolar reviewed
Also, do you think it's neccessary to use the SVG from DL? or maybe for keeping the visual consistency in storybook you may want to use the same image of the "image component"

2020-05-28 13:51 UTC, Dhruvi16 commented on src/styles/image.scss
> +  min-width: 60px;
According to the DL description, this component can have a minimum size of 60px square. So I added it.

2020-05-28 13:52 UTC, Dhruvi16 commented
> Also, do you think it's neccessary to use the SVG from DL? or maybe for keeping the visual consistency in storybook you may want to use the same image of the "image component"

I am not sure if it is necessary to use a new SVG. But I guess it makes sense to maintain visual consistency.

2020-05-28 14:01 UTC, dhruvkb requested changes
If we do agree to branch it to a new component, can we also support profile pictures that don't have a picture with some initials? Like Figma does:
<img width="169" alt="Screenshot 2020-05-28 at 7 30 56 PM" src="https://user-images.githubusercontent.com/16580576/83151097-c33c8880-a119-11ea-910e-520fc01dbdbf.png">

2020-05-28 14:01 UTC, dhruvkb commented on src/assets/demo/profile.svg
> +<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
Format code according to the SVG style guide or better yet, use a square PNG to match real world use-cases.

2020-05-28 14:01 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +</Preview>
Correct me if I'm wrong but I thought in the Slack conversation we concluded that a profile picture was fundamentally different from the other Image component and so it belonged to a separate story and a separate class.

2020-05-28 14:01 UTC, dhruvkb commented on src/stories/image.stories.mdx
> +</Preview>
This gives the impression that you can add a rounding on the other kind of image as well, which is not true.

2020-05-28 14:01 UTC, dhruvkb commented on src/styles/image.scss
> +  border-radius: 50%;
Use a very large number instead of 50%.
```suggestion
  border-radius: 999px;
```
Using percentage values generates ellipses if the underlying image has different height and width.

2020-05-28 14:01 UTC, dhruvkb commented on src/styles/image.scss
> +  border: solid 3px;
For my edification, is a pixel-value correct here? This will mean that the border will be the same number of pixels regardless of the size of the image, which could be what we want, just make sure it is.

2020-05-28 14:01 UTC, dhruvkb commented on src/styles/image.scss
> +  border-color: $color-dark-slate-gray;
Just as a tip, you could use `border: 3px solid $color-dark-slate-gray;`. It's shorter and more readable.

2020-05-30 07:26 UTC, Dhruvi16 commented on src/stories/image.stories.mdx
> +</Preview>
You are correct! I ignored the DL structure and added changes according to the discussion going on here. It is a different component and I will update it ASAP.

2020-05-30 07:30 UTC, Dhruvi16 commented on src/assets/demo/profile.svg
> +<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
Should I use the same demo image used for the image component?

2020-05-30 08:22 UTC, Dhruvi16 commented
> Also, do you think it's neccessary to use the SVG from DL? or maybe for keeping the visual consistency in storybook you may want to use the same image of the "image component"

I am not sure if it is necessary to use a new SVG. But I guess it makes sense to maintain visual consistency.

> If we do agree to branch it to a new component, can we also support profile pictures that don't have a picture with some initials? Like Figma does:
> <img alt="Screenshot 2020-05-28 at 7 30 56 PM" width="169" src="https://user-images.githubusercontent.com/16580576/83151097-c33c8880-a119-11ea-910e-520fc01dbdbf.png">

As fas as I know the profile images without any picture has the icon as per CCOS mockups -
https://www.figma.com/file/mttcugI1UxvCJRKE5sdpbO/Mockups?node-id=968%3A52

2020-05-30 08:46 UTC, dhruvkb commented on src/styles/image.scss
> +  border-radius: 50%;
I was wrong about this. Sorry.

2020-05-30 21:45 UTC, dhruvkb commented on src/styles/image.scss
> +  min-width: 60px;
Even then, use `em` unit.

2020-06-07 14:53 UTC, hugosolar requested changes

2020-06-07 14:53 UTC, hugosolar commented on src/stories/profile_image.stories.mdx
> +    <figure class="image is-square">
maybe you can add a wrapper container because I was watching the component in a big screen and it looks like this
![Screen Shot 2020-06-07 at 10 50 11 AM](https://user-images.githubusercontent.com/894708/83972189-c586ab80-a8ac-11ea-8d5d-ffcabb4e5dca.png)

2020-06-07 14:53 UTC, hugosolar commented on src/stories/profile_image.stories.mdx
> +    <figure class="image is-square">
it would be just for displaying purpose on storybook
```css
<div style="width: 200px;">
  <figure class="image is-square">
     <img class="profile" src="demo/profile.jpg">
  </figure>
</div>
```

2020-06-07 14:59 UTC, dhruvkb commented on src/stories/profile_image.stories.mdx
> +    <figure class="image is-square">
Should be fixed in 5a0bccd.

2020-06-07 15:01 UTC, hugosolar approved these changes

2020-06-07 15:02 UTC, dhruvkb commented
@Dhruvi16 for the sake of speed, I made some changes to the code. Listing them here for your reference:
- Removed blank lines left by old commits in 1ab9dec
- Fixed some punctuation in 0a0bf6b
- Addressed the scaling problem and replaced with a brighter image to show the border clearly in 5a0bccd

Please note these changes and try to keep them in mind in future PRs!

2020-06-07 15:02 UTC, dhruvkb approved these changes

2020-06-07 15:03 UTC, dhruvkb commented on src/styles/profile_image.scss
> +  .profile {
When defining classes scope them as much as possible so that they don't have far reaching effects.

2020-06-07 15:05 UTC, dhruvkb commented on src/assets/demo/profile.svg
> +<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
Replaced with a brighter image.

2020-06-07 15:05 UTC, merged