Add project index card
cc-archive/vocabulary-legacy pull request #422
Opened 2020-05-30 07:24 UTC by Dhruvi16

## Fixes

Fixes #394 by @Dhruvi16 

## Description

Adds project index card to the vocabulary.

## Screenshots

![image](https://user-images.githubusercontent.com/34674462/83322359-951f8b80-a274-11ea-9683-511ea5a37bda.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-07 18:16 UTC, dhruvkb requested changes

2020-06-07 18:16 UTC, dhruvkb commented on src/styles/card.scss
> +        &.project-index {
👍 Appreciate you building the entire component using `@extend`. Helps DRY-ing the codebase. Also kudos for keeping the 4-space indentation (although I would appreciate changing the file to 2-space indentation in a different PR).

2020-06-07 18:16 UTC, dhruvkb commented on src/styles/card.scss
> +                font-weight: bold;
This changes the title for all cards. Are you sure this matches Figma?

2020-06-07 18:16 UTC, dhruvkb commented on src/stories/cards.stories.mdx
> +  <Story name="Project Index" parameters={{
```suggestion
  <Story name="Project index" parameters={{
```

2020-06-07 18:16 UTC, dhruvkb commented on src/stories/cards.stories.mdx
> +    <div style="width: 400px;">
I'd rather see `<style>...</style>` in the story than `style="..."`.
```suggestion
    <style>
      .project-index {
        width: 400px;
      }
    </style>  
    <div class="project-index">
```

2020-06-07 18:26 UTC, Dhruvi16 commented on src/styles/card.scss
> +                font-weight: bold;
![image](https://user-images.githubusercontent.com/34674462/83976865-75dec900-a91a-11ea-81ab-d1dd56d2765b.png)
![image](https://user-images.githubusercontent.com/34674462/83976877-88590280-a91a-11ea-848d-66fad9b5a436.png)

Yes I am sure.

2020-06-07 18:38 UTC, Dhruvi16 commented on src/styles/card.scss
> +                font-weight: bold;
But I guess I should do that in a different PR, right?

2020-06-07 19:01 UTC, hugosolar approved these changes

2020-06-13 18:02 UTC, dhruvkb commented on src/styles/card.scss
> +                font-weight: bold;
No, this is fine.

2020-06-13 18:08 UTC, dhruvkb requested changes
The 'Visit site' link seems a little misaligned with the other content. Admittedly it's a problem with the 'Button' component so you could choose to solve it separately but please open an issue about this.

<img width="408" alt="Screenshot 2020-06-13 at 11 36 15 PM" src="https://user-images.githubusercontent.com/16580576/84575953-b765ed00-adce-11ea-98bf-7daf41c6ac45.png">

2020-06-13 20:12 UTC, dhruvkb requested changes

2020-06-13 20:12 UTC, dhruvkb commented on src/styles/card.scss
> +                    i {
If the element has a class, use that as the selector.

2020-06-13 20:12 UTC, dhruvkb commented on src/styles/card.scss
> +                    i {
Applies to all element selectors in the PR.

2020-06-13 20:41 UTC, dhruvkb approved these changes

2020-06-13 20:46 UTC, merged