Add TOC component
cc-archive/vocabulary-legacy pull request #435
Opened 2020-06-04 13:21 UTC by Dhruvi16

## Fixes

Fixes #429 by @Dhruvi16 

## Description

This adds Table of Content component according to DL.

## Screenshots

![image](https://user-images.githubusercontent.com/34674462/83761786-63ebf480-a694-11ea-8069-31f54ce0ea2d.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-07 14:33 UTC, hugosolar requested changes
Sames as vertical navigation. Can we avoid the dot being underlined?
![Screen Shot 2020-06-07 at 10 30 17 AM](https://user-images.githubusercontent.com/894708/83971613-4b552780-a8aa-11ea-846f-0f03ab382411.png)

2020-06-07 14:33 UTC, hugosolar commented on src/styles/table_of_content.scss
> +$menu-item-color: $color-tomato;
we may check this variables doesn't overlap with the side navigation, and if they're the same, there's no need to specify that more than once.

2020-06-07 17:39 UTC, Dhruvi16 commented on src/styles/table_of_content.scss
> +$menu-item-color: $color-tomato;
Removing this makes the link of color dark-slate-gray so I am removing this.

2020-06-07 17:48 UTC, Dhruvi16 commented
> Sames as vertical navigation. Can we avoid the dot being underlined?
> ![Screen Shot 2020-06-07 at 10 30 17 AM](https://user-images.githubusercontent.com/894708/83971613-4b552780-a8aa-11ea-846f-0f03ab382411.png)

You are right. Actually hover state has no underline according to Figma so removing text-decoration from the whole link.

2020-06-07 18:07 UTC, dhruvkb approved these changes
Minor changes to be made.

2020-06-07 18:07 UTC, dhruvkb commented on src/stories/table_of_content.stories.mdx
> +<Meta title="Patterns/Table of Content" />
Please change to 'Table of contents'.

2020-06-07 18:07 UTC, dhruvkb commented on src/stories/table_of_content.stories.mdx
> +<Meta title="Patterns/Table of Content" />
Include file names. The class name `.toc` is fine.

2020-06-07 18:07 UTC, dhruvkb commented on src/styles/table_of_content.scss
> +$menu-item-color: $color-tomato;
Yes, since the files are all imported together in `vocabulary.scss`, redefining a variable in multiple files leaves only the last definition (breaking all other components).

2020-06-07 18:58 UTC, hugosolar commented on src/styles/table_of_contents.scss
>    max-width: 276px;
Please use relative units (e.g rem)
also, I don't think we should set a max-width because that's shoud be determined by the container

2020-06-08 12:55 UTC, hugosolar approved these changes

2020-06-08 12:58 UTC, merged