Add pagination component
cc-archive/vocabulary-legacy pull request #441
Opened 2020-06-05 21:08 UTC by Dhruvi16

## Fixes

Fixes #431 by @Dhruvi16 

## Description

This adds pagination components

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-05 21:12 UTC, Dhruvi16 commented
I have certain doubts regarding this - The font used in the component is h4(vocabulary) but I had to rewrite it in the scss file because I could not overwrite the color. 
Next in `.inactive` - `background-color: $color-dark-gray` did not work but `@extend .has-background-grey-dark;`did IDK why?

2020-06-07 14:41 UTC, hugosolar requested changes

2020-06-07 14:41 UTC, hugosolar commented on src/styles/pagination.scss
> +.common {
This is a pretty general class, I think we should place it inside the pagination element scope
```css
.pagination {
  .pagination-list {
    .common {
     ...
    }
  }
}

2020-06-07 14:41 UTC, hugosolar commented on src/styles/pagination.scss
> +.inactive {
Same here... outside the element scope it could be any `.inactive` element and may overlap with other styles

This is a pretty general class, I think we should place it inside the pagination element scope
```css
.pagination {
  .pagination-list {
    .inactive {
     ...
    }
  }
}

2020-06-07 15:15 UTC, dhruvkb requested changes

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +}
Pay a little more attention to newlines at EOF.

2020-06-07 15:15 UTC, dhruvkb commented on src/stories/pagination.stories.mdx
> +</nav>
Making functions is not that useful if you're just using them once. Could've written the markup directly inside the `<Story>...</Story>` tags

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +}
Don't style tags outside scope. This will affect every `<a>` on the entire website which is dangerous.

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +  font-family: Roboto Condensed;
Don't use font-family names. Use their SCSS variable names from the `typography.scss` file which allows us to switch fonts in the future, if needed, from a central location.

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +  line-height: 1.875em;
Line heights are expressed as a fraction of font-size. So `1.875em` should just be written as `1.875`.

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +    border-radius: 0em;
Units are not needed if the value is zero. Just use `0`.

2020-06-07 15:15 UTC, dhruvkb commented on src/styles/pagination.scss
> +      @extend .has-background-grey-lighter;
Appreciate the extensive use of `@extend` :+1:!

2020-06-07 17:57 UTC, dhruvkb commented on src/styles/pagination.scss
> +      @extend .has-background-grey-lighter;
@Dhruvi16 you removed them?

2020-06-07 17:59 UTC, dhruvkb commented on src/styles/pagination.scss
> +  font-family: Roboto Condensed;
@Dhruvi16 stylesheets are supposed to use `$family-alternative` (which is a name-free alias for `$family-roboto-condensed`).

2020-06-07 18:09 UTC, Dhruvi16 commented on src/styles/pagination.scss
> +      @extend .has-background-grey-lighter;
The bulma class .has-background-grey-lighter applies class - `backgorund-color: grey-lighter !important` which prevents the change of background on hover so I had to remove them.

2020-06-07 18:09 UTC, Dhruvi16 commented on src/styles/pagination.scss
> +  font-family: Roboto Condensed;
Oh oops! I will update it.

2020-06-07 18:17 UTC, dhruvkb commented on src/styles/pagination.scss
> +      @extend .has-background-grey-lighter;
Okay!

2020-06-07 18:17 UTC, dhruvkb approved these changes
LGTM

2020-06-07 18:54 UTC, hugosolar approved these changes

2020-06-08 12:54 UTC, merged