Add blog entry card
cc-archive/vocabulary-legacy pull request #446
Opened 2020-06-08 12:33 UTC by Dhruvi16

## Fixes

Fixes #393 by @Dhruvi16 

## Description

This adds blog entry card to the library.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-08 13:48 UTC, hugosolar requested changes

2020-06-08 13:48 UTC, hugosolar commented on src/styles/card.scss
> +    &.blog-entry {
I think it would be better if we use the padding in the container, so the elements inside stay aligned and have equal spaces from all sides
![Screen Shot 2020-06-08 at 9 42 33 AM](https://user-images.githubusercontent.com/894708/84037402-8ae44800-a96c-11ea-8ef0-917f07bd94f7.png)

2020-06-08 13:48 UTC, hugosolar commented on src/styles/card.scss
> +    &.blog-entry {
or maybe try to add padding from the left side.
Also, I would use padding instead margin to the top image

2020-06-09 10:47 UTC, Dhruvi16 commented on src/styles/card.scss
> +    &.blog-entry {
I have updated the component. Actually there was no outer padding or margin and background in the DL.

2020-06-10 19:10 UTC, hugosolar commented on src/styles/card.scss
> +    &.blog-entry {
Ok, but we're assuming that component would be used just on that context which makes it less extensive.
let's leave it like this and if we need a modification we can do it later

2020-06-10 19:10 UTC, hugosolar commented on src/stories/cards.stories.mdx
> +      <article class="card entry-post vertical background">
What's the point of the `.background` class?

2020-06-10 20:00 UTC, hugosolar approved these changes

2020-06-13 17:11 UTC, dhruvkb approved these changes
LGTM

2020-06-13 17:15 UTC, merged