Add table of progress component.
cc-archive/vocabulary-legacy pull request #447
Opened 2020-06-09 17:24 UTC by Dhruvi16

## Fixes

Fixes #430 by @Dhruvi16 

## Description

Adds Table of progress component.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-10 18:52 UTC, hugosolar requested changes

2020-06-10 18:52 UTC, hugosolar commented on src/styles/table_of_progress.scss
> +  .is-active {
I have this minor visibility issue on firefox (I can't see it on Chrome). You can see how the line overlaps on the active element

![Screen Shot 2020-06-10 at 2 08 54 PM](https://user-images.githubusercontent.com/894708/84302821-f0c70000-ab23-11ea-9d5d-30583fabc216.png)

this can be fixed, setting the element to `position: relative;`

2020-06-10 19:42 UTC, Dhruvi16 commented on src/styles/table_of_progress.scss
> +  .is-active {
I am unable to reproduce this issue on firefox (75.0) but I will add `position: relative;` to `.is-active`

2020-06-10 19:58 UTC, hugosolar commented on src/styles/table_of_progress.scss
> +  .is-active {
Mine it's 77 hehe

2020-06-10 19:59 UTC, hugosolar approved these changes

2020-06-13 17:39 UTC, dhruvkb requested changes
I understand the reason for choosing `.top` and the symmetry this has with 'Table of Contents' or `.toc`.

2020-06-13 17:39 UTC, dhruvkb commented on src/styles/table_of_progress.scss
> +.top {
`.top` seems like something that could easily be used as another class meaning top (as in up ^).

2020-06-13 17:59 UTC, dhruvkb requested changes

2020-06-13 17:59 UTC, dhruvkb commented on src/stories/table_of_progress.stories.mdx
> +        <li>
If you give each `li` a class of `.step`, you can change the inner span classes to `.number` and `.name`.

2020-06-13 17:59 UTC, dhruvkb commented on src/stories/table_of_progress.stories.mdx
> +        <span class="connector"><span>
Can this connector be replaced with `li.step:not(:last_of_type)::after`?

2020-06-13 17:59 UTC, dhruvkb commented on src/stories/table_of_progress.stories.mdx
> +        <span class="connector"><span>
Components that are purely stylistic should not exist in the HTML markup.

2020-06-13 17:59 UTC, dhruvkb commented on src/stories/table_of_progress.stories.mdx
> +The table of progress was created to indicate steps inside a page. The component works with links for each step to navigate through all steps. At the same time, the active step must change based on w
Can we wrap at 80 chars?

2020-06-13 19:39 UTC, dhruvkb approved these changes

2020-06-13 19:41 UTC, merged