Remove overlapping variables from table of content.
cc-archive/vocabulary-legacy pull request #449
Opened 2020-06-09 20:41 UTC by Dhruvi16

## Description

Removes overlapping variables in Table of Content component. The same variables with same value are declared in Sidebar menu so repeating them in TAble of content was unnecessary.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-10 19:13 UTC, hugosolar commented on src/stories/table_of_contents.stories.mdx
> -              <li><a class="inactive-link"><i class="icon circle-filled"></i>Child section</a></li>
This `.inactive-link` class was removed because there isn't an "inactive" state of links right?

2020-06-10 19:46 UTC, Dhruvi16 commented on src/stories/table_of_contents.stories.mdx
> -              <li><a class="inactive-link"><i class="icon circle-filled"></i>Child section</a></li>
Yes. It was added by me earlier but it was not required.

2020-06-10 20:01 UTC, hugosolar approved these changes

2020-06-13 18:21 UTC, dhruvkb requested changes
This review also applies to `.side-navigation` in `sidebar_menu.scss`.

2020-06-13 18:21 UTC, dhruvkb commented on src/styles/table_of_contents.scss
>    i {
If this is for the `i.icon` element, use the class `.icon` here.

2020-06-13 18:21 UTC, dhruvkb commented on src/styles/table_of_contents.scss
>  .toc {
For consistency with `.table-of-progress`, rename this to `.table-of-contents`.

2020-06-13 19:47 UTC, dhruvkb approved these changes

2020-06-13 19:50 UTC, merged