Configured Dependabot
cc-archive/vocabulary-legacy pull request #452
Opened 2020-06-11 19:37 UTC by nimishbongale

## Fixes
Fixes #451 by @nimishbongale and @dhruvkb 

## Description
Adds a `.github/dependabot.yml` file to configure dependabot.
The confguration was successful in my fork 

* https://github.com/nimishbongale/vocabulary/runs/763009948

## Screenshots

![dependabot](https://user-images.githubusercontent.com/43414361/84431351-cae74b80-ac48-11ea-9033-f4b32390acb6.PNG)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-12 02:49 UTC, dhruvkb requested changes
It's good to merge barring except for a couple of minor changes. Do you think comments would help?

2020-06-12 02:49 UTC, dhruvkb commented on .github/dependabot.yml
> +  - package-ecosystem: "npm"
Our YML files ([exhibit A](https://github.com/creativecommons/vocabulary/blob/master/docker-compose.yml) and [exhibit B](https://github.com/creativecommons/vocabulary/blob/master/.cc-metadata.yml)) have used single-quotes in their string.

2020-06-12 02:49 UTC, dhruvkb commented on .github/dependabot.yml
> +version: 2
Leave a line after version. Looks cleaner imo.

2020-06-13 06:56 UTC, nimishbongale commented
> It's good to merge barring except for a couple of minor changes. Do you think comments would help?

Yeah, although I did feel the .yml file was pretty self-explanatory. I'd be fine either way, surely makes it more reader friendly.

2020-06-13 06:57 UTC, nimishbongale commented on .github/dependabot.yml
> +version: 2
Alright!

2020-06-13 06:59 UTC, nimishbongale commented on .github/dependabot.yml
> +  - package-ecosystem: "npm"
Right. Will change!

2020-06-13 07:14 UTC, nimishbongale commented on .github/dependabot.yml
> +version: 2
Done.

2020-06-13 08:59 UTC, dhruvkb approved these changes

2020-06-13 08:59 UTC, dhruvkb commented on .github/dependabot.yml
> +# This is the current version of the github native dependabot
```suggestion
# This is the current version of the GitHub-native Dependabot
```

2020-06-13 11:00 UTC, merged