A minimal notification component addition
cc-archive/vocabulary-legacy pull request #470
Opened 2020-06-16 08:56 UTC by kushaggarwal

## Fixes

Fixes #466 by @makkoncept

## Description

This PR aims at the addition of a minimal notification component in the current storybook components in reference to the CC Search extension mockup 

## Technical details

The implementation for the same follows the same structure as of the previously mentioned components

## Tests

## Screenshots

![Screenshot 2020-06-16 at 2 20 59 PM](https://user-images.githubusercontent.com/44523552/84753767-10a36b80-afdd-11ea-9f54-95494461377b.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-07-15 13:15 UTC, hugosolar requested changes
Also, I would change the name to something more like `compact` or `clean` 
doesn't seem to be very clear right now.

![Screen Shot 2020-07-15 at 9 12 18 AM](https://user-images.githubusercontent.com/894708/87549068-59515180-c67b-11ea-8582-dfd17efb136f.png)

2020-07-15 13:15 UTC, hugosolar commented on src/styles/notification.scss
> +    border-radius: 0.25rem;
there's no need to add a `0` to the value

2020-07-15 13:15 UTC, hugosolar commented on src/styles/notification.scss
> +        box-shadow: 0.5rem 0.5rem 0 rgba($color-black, 0.06);
same here. there's no need to add a `0`

2020-07-15 13:15 UTC, hugosolar commented on src/styles/notification.scss
> +  &.minimal {
following bulma's naming convention I'll use something like `.is-minimal`

2020-07-15 13:15 UTC, hugosolar commented on src/styles/notification.scss
> +      width: 35%;
I'll avoid setting a width. It should stick into its container, it's more flexible in my opinion

2020-07-15 13:15 UTC, hugosolar commented on src/styles/notification.scss
> +      background-color: $color-light-success;
I'll keep the background separated using the [background color classes](https://cc-vocabulary.netlify.app/?path=/docs/tokens-color--figma)

2020-07-16 16:27 UTC, kushaggarwal commented
Hello @hugosolar 
Will update the following changes
Thank you

2020-07-28 23:52 UTC, kushaggarwal commented
Hello @hugosolar 
Apology for the delay 
Please find the above changes 
Thank you

2020-07-29 21:05 UTC, hugosolar requested changes

2020-07-29 21:05 UTC, hugosolar commented on src/stories/notification.stories.mdx
> +  <Story name="Notification">{`
I still think we need a name like "Compact" or "Minimal" and not "Notification" because sounds a little bit vague to me

2020-07-29 21:05 UTC, hugosolar commented on src/styles/header.scss
> +.colorIstomato {
Why is this color set here?
we have classes for colors [here](https://cc-vocabulary.netlify.app/iframe.html?id=tokens-color--helpers&viewMode=docs#usage)
Also, I don't see the point of this, cause you're making a PR for notification component

2020-08-07 13:08 UTC, hugosolar commented
Closing this PR in favor of #569 
@kushaggarwal Thank you very much for your contribution!

2020-08-07 13:08 UTC, closed without merging