Fix footer style according to Design Library
cc-archive/vocabulary-legacy pull request #485
Opened 2020-06-18 22:32 UTC by krysal

## Fixes

Fixes #484 by @krysal 

## Description
Change styles mentioned in the issue.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-08-05 15:35 UTC, dhruvkb requested changes

2020-08-05 15:35 UTC, dhruvkb commented on src/stories/footer.stories.mdx
> +                <label for="email" class="is-sr-only"></label>
If you have a label for screen-readers, please also add the text that the screen-reader should read.
```suggestion
                <label for="email" class="is-sr-only">Email to subscribe</label>
```

2020-08-05 15:35 UTC, dhruvkb commented on src/styles/footer.scss
> +          }
Indentation is a bit off.

2020-08-05 15:36 UTC, dhruvkb commented
Sorry for the late review @krysal.

2020-08-05 15:39 UTC, krysal commented on src/stories/footer.stories.mdx
> +                <label for="email" class="is-sr-only"></label>
Ups, of course, I forgot it, my bad.

2020-08-05 15:43 UTC, krysal commented on src/styles/footer.scss
> +          }
I see no problem here, it's two spaces like the rest of the file, how should it be?

2020-08-05 15:46 UTC, krysal commented on src/styles/footer.scss
> +          }
Oh, I already noticed the whole block has an extra indentation, fixing.

2020-08-05 16:07 UTC, krysal commented
It's okay! I applied the required corrections.

2020-08-12 15:18 UTC, dhruvkb approved these changes

2020-08-12 15:18 UTC, merged