Update Inputs with Name and Description
cc-archive/vocabulary-legacy pull request #522
Opened 2020-07-18 13:48 UTC by rochisha0

## Fixes

Related to #520  by @zackkrida 

## Description
It is the first PR related to the issue, I have created 3 new previews for the same

## Technical details

## Tests

## Screenshots

It currently looks like this
![image](https://user-images.githubusercontent.com/45593458/87853833-406ec780-c92b-11ea-90ec-bdfeeaa542c1.png)
![image](https://user-images.githubusercontent.com/45593458/87853849-554b5b00-c92b-11ea-9d0f-a7a00cb7dd94.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-07-18 13:49 UTC, rochisha0 commented
@zackkrida Please suggest changes and suitable story names for the particular stories.

2020-07-20 06:02 UTC, dhruvkb requested changes

2020-07-20 06:02 UTC, dhruvkb commented on src/stories/input.stories.mdx
> +  <Story name="Normal2" height="200px" parameters={{
Using descriptive story names is fine.
```suggestion
  <Story name="Normal (+ name, description)" height="200px" parameters={{
```

2020-07-20 06:02 UTC, dhruvkb commented on src/stories/input.stories.mdx
> +<b>Input Name <b>
Use of `<b>` is discouraged, try `<strong>`.

2020-07-20 06:02 UTC, dhruvkb commented on src/stories/input.stories.mdx
> +  <br>
Use `<div>`s instead of `<br>` as line breaks. I understand there are bad usages of `<br>` in the existing stories, but let's start the change somewhere.

2020-07-20 09:29 UTC, rochisha0 commented
Thanks, @dhruvkb! I will make the necessary changes soon.

2020-07-20 12:59 UTC, zackkrida requested changes
Hi @rochisha0 thank you for this PR. Just a few small items to clean up and we can merge!

- [ ] Please fix the story names as suggested by @dhruvkb 
- [ ] Please use the following html tags to structure the inputs:
<img width="357" alt="Screen Shot 2020-07-20 at 8 49 54 AM" src="https://user-images.githubusercontent.com/6351754/87939691-6ea4f200-ca66-11ea-84a6-0424f8c8011b.png">

for spacing the `<label>` and `<p>` tags correctly above the input, I recommend some of the spacing classes from vocabulary. In the mockup the name, description, and input all have 8px between them, so you could use the `.margin-bottom-small` class for that.

Let me know if you have questions—thank you!

2020-07-20 18:29 UTC, rochisha0 commented
Hey! @zackkrida I'm unable to locate vocabulary/bulma. Please guide me on that.

2020-07-20 18:35 UTC, zackkrida commented
@rochisha0 you can use that margin class I suggested without importing or adding any libraries. I just meant that the margin class comes from vocabulary, which is built on top of the bulma library.

2020-07-21 13:49 UTC, zackkrida requested changes
This looks great! One last edit—the 'medium' and 'large' name + description need to be larger:

- use `.body-big` on the medium `<p>` and `<label>`
- use `.body-bigger` on the large `<p>` and `<label>`

2020-07-21 15:10 UTC, rochisha0 commented
@zackkrida Done!

2020-07-21 15:12 UTC, zackkrida approved these changes
🎉 thank you!

2020-07-21 21:45 UTC, merged