fixed typos and grammatical errors
cc-archive/vocabulary-legacy pull request #568
Opened 2020-08-05 17:54 UTC by palak199

## Fixes

Fixes #567 that I opened

2020-08-06 10:05 UTC, dhruvkb requested changes
Looks good except one change!

2020-08-06 10:05 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +create a cohesive brand identity for CC, which will improve both user experience and drive more awareness of our work
I don't agree, the word 'both' here applies to "improve user experience" and "drive more awareness" so it should precede both of those phrases.

2020-08-06 10:50 UTC, palak199 commented on .storybook/meta/overview.stories.mdx
> +create a cohesive brand identity for CC, which will improve both user experience and drive more awareness of our work
@dhruvkb I have placed it preceding two both of the phases. Rest if you still find it inappropriate, my apologies, i ll change it and submit again.

2020-08-07 10:50 UTC, palak199 commented on .storybook/meta/overview.stories.mdx
> +create a cohesive brand identity for CC, which will improve both user experience and drive more awareness of our work
@dhruvkb so should I modify it to what it was before ?

2020-08-07 11:18 UTC, dhruvkb commented on .storybook/meta/overview.stories.mdx
> +create a cohesive brand identity for CC, which will improve both user experience and drive more awareness of our work
Yeah, I still feel that the old one was more accurate. Please switch it back.

2020-08-09 10:09 UTC, Dhruvi16 approved these changes

2020-08-09 17:52 UTC, dhruvkb approved these changes

2020-08-09 17:52 UTC, merged