Add responsive table.
cc-archive/vocabulary-legacy pull request #582
Opened 2020-08-11 13:16 UTC by Dhruvi16

## Fixes

Fixes #525 by @Dhruvi16 

## Description

This PR adds a responsive table.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-08-11 13:18 UTC, Dhruvi16 commented
So far I have this -
![image](https://user-images.githubusercontent.com/34674462/89901705-1c896380-dc03-11ea-85ef-bf62094c49f2.png)

There are a few problems with this -
1. The data is aligned right.
2. There is a bottom border in the header part.

2020-08-11 13:19 UTC, Dhruvi16 commented
I was unable to fix the above problems, some tips will be nice. 
Thanks

2020-08-12 15:20 UTC, zackkrida requested changes

2020-08-12 15:20 UTC, zackkrida commented on src/stories/tables.stories.mdx
> +          <th>Total seats</ththe>
`</ththe>` looks like a typo

2020-08-12 15:20 UTC, zackkrida commented on src/stories/tables.stories.mdx
> +        <td data-content="Total seats" class="number-cell">7</td>
😻 i LOVE how you implemented this. Awesome!

2020-08-12 15:20 UTC, zackkrida commented on src/styles/table.scss
> +	td:nth-of-type(n):before { content: attr(data-content); }
🔥 Great

2020-08-12 16:11 UTC, Dhruvi16 commented on src/stories/tables.stories.mdx
> +        <td data-content="Total seats" class="number-cell">7</td>
I think I should change it to `data-label` because that makes more sense. What do you think?

2020-08-12 16:14 UTC, Dhruvi16 commented on src/stories/tables.stories.mdx
> +        <td data-content="Total seats" class="number-cell">7</td>
And it was @dhruvkb's idea so thanks to him.

2020-08-12 16:46 UTC, zackkrida commented on src/stories/tables.stories.mdx
> +        <td data-content="Total seats" class="number-cell">7</td>
`data-label` probable makes sense!

2020-08-12 16:47 UTC, Dhruvi16 commented
I also have one doubt that merging this will break the existing tables in different projects because `data-label` will be missing there.

2020-08-12 16:48 UTC, zackkrida commented
@Dhruvi16 I found two more issues:

1. Can you update _all_ table stories in vocabulary to have the `data-label`s?The 2nd table example is missing them.
2. The table rows need some border-radius and bottom margin between them:

<img width="383" alt="Screen Shot 2020-08-12 at 12 46 01 PM" src="https://user-images.githubusercontent.com/6351754/90043465-23af8080-dc9a-11ea-8964-13817febab23.png">

2020-08-12 16:57 UTC, Dhruvi16 commented
Okay! I recognize my mistake here but we discussed about having two types of responsive designs right?

2020-08-12 17:02 UTC, zackkrida commented
@Dhruvi16 you're right, probably need a new top-level css class like `.is-responsive` or something for the tables that will have the `data-label` styles. Without that class it will use the "old"/overflow responsive styles

2020-08-12 17:13 UTC, Dhruvi16 commented
you are right! I will update it.

2020-08-13 14:26 UTC, Dhruvi16 commented
I think I have fixed all the problems.

2020-08-13 14:52 UTC, zackkrida approved these changes
This is great, thanks @Dhruvi16

2020-08-13 14:52 UTC, merged