Unified README.md, updated build process
cc-archive/vocabulary-legacy pull request #649
Opened 2020-09-10 17:53 UTC by nimishbongale

## Fixes
Fixes #646 by @nimishbongale 

## Description
- Update the `packages/<package-name>/deploy.sh` to include the main `README.md` instead of the ones present in the packages
- Delete the local package README's
- Update the main `README.md` with information on how to get our repository up and running on a local system (considering we could have potential hacktoberfest contributors)

I will update the link to the vocabulary logo in the main `README.md` once we decide what finally needs to be done with the in-package `readme_assets` (open PR's for the same exist) 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-09-10 18:19 UTC, zackkrida commented
Looks great. My thoughts would be the following:

- Rename `packages/vocabulary/readme_assets/vocabulary_logo.svg` to `logo.svg` and move to the project root.
- Remove all `readme_assets` directories
- Update root `README.md` logo url to `https://raw.githubusercontent.com/creativecommons/vocabulary/master/logo.svg?sanitize=true`
- Update the `brandImage` in `packages/fonts/.storybook/theme.js` to `https://raw.githubusercontent.com/creativecommons/vocabulary/master/logo.svg?sanitize=true` (fine for now since we're deprecating that storybook installation soon anyway)

2020-09-10 18:22 UTC, zackkrida commented
Ooh one more thing @nimishbongale, could you change the storybook port for each package so they can run at the same time with the root `npm run storybook` script? Right now they all try to run on `8080` so the script fails.

2020-09-10 18:26 UTC, nimishbongale commented
> Ooh one more thing @nimishbongale, could you change the storybook port for each package so they can run at the same time with the root `npm run storybook` script? Right now they all try to run on `8080` so the script fails.

Yes, this is something I noticed too. @dhruvkb mentioned it possibly takes consecutive ports, but it didn't happen so on my system. 

I'll update them in the following manner:

1. **Fonts** should run on `8080`
2. **Vocabulary** should run on `8081`
3. **Vue-Vocabulary** should run on `8082`

2020-09-11 04:53 UTC, dhruvkb requested changes

2020-09-11 04:53 UTC, dhruvkb commented on README.md
> +You would need to have [nodejs](https://nodejs.org/en/) and [npm](https://www.npmjs.com/)/[yarn](https://yarnpkg.com/) installed.
Not Yarn. While Yarn will still work, since we use `package-lock.json`, npm is the preferred package manager.

2020-09-11 04:53 UTC, dhruvkb commented on README.md
> +To run this repository locally:
The phrase "run this repository" is not very clear. You could say "run the storybooks for all packages in the repository" for example.

2020-09-11 04:53 UTC, dhruvkb commented on packages/fonts/deploy.sh
> +cp ../../README.md dist/
Can use [`sed`](https://linux.die.net/man/1/sed) to customise the installation paragraph for each repo.

2020-09-11 04:55 UTC, dhruvkb reviewed
Just to confirm, does this fix the broken logo? Asking because it doesn't look like you moved `readme_assets` out into the root directory.

2020-09-11 05:11 UTC, zackkrida commented
@dhruvkb @nimishbongale i don't think the port and logo path changes are done yet, but I _do_ think they make sense as part of this PR.

2020-09-11 05:18 UTC, nimishbongale commented on README.md
> +You would need to have [nodejs](https://nodejs.org/en/) and [npm](https://www.npmjs.com/)/[yarn](https://yarnpkg.com/) installed.
Alright, will remove yarn.

2020-09-11 05:19 UTC, nimishbongale commented on README.md
> +To run this repository locally:
Okay, will rephrase it!

2020-09-11 05:19 UTC, nimishbongale commented on packages/fonts/deploy.sh
> +cp ../../README.md dist/
I'll look into it!

2020-09-11 05:24 UTC, nimishbongale commented
> Just to confirm, does this fix the broken logo? Asking because it doesn't look like you moved `readme_assets` out into the root directory.

The broken logo was a part of the in-package `README.md,` which ceases to exist anymore.

The `readme_assets` would need to be deleted from the individual packages, and moved to the root. This was sort of being done in a separate PR (external contributor), but yes, it wasn't merged due to other reasons. 

I'll add in more commits to this PR resolving everything.

2020-09-11 05:30 UTC, dhruvkb commented
Just make sure to use the absolute URL to the logo (`https://raw.githubusercontent.com/...`) instead of a relative URL so that the image displays properly on `npm`.

2020-09-11 19:02 UTC, nimishbongale commented on packages/fonts/deploy.sh
> +cp ../../README.md dist/
@dhruvkb afaik, this command would do the copying file operation via sed

`sed -n 'p' "../../README.md" > "dist/README.md"`

Do you want me to opt for `sed` instead of `cpy`? For all our other `cpy` commands as well?

2020-09-11 19:33 UTC, nimishbongale commented
@dhruvkb @zackkrida 

I've resolved all the issues we had talked about earlier. One noteworthy thing to mention would be the fact that if we browse to [https://cc-vue-vocabulary.netlify.app](https://cc-vue-vocabulary.netlify.app) it wouldn't open as expected. I did check the console and there were some errors. Tried running `vue-vocabulary` locally, but even then I faced the same issue.

The solution that fixed the issue was a simple update of `storybookjs` to `6.0.21`. I've added this as well into the PR.

Recent changes in this stage of the PR:

- The vocabulary logo now sits inside a `readme_assets` folder inside the root.
- The in-package `readme_assets` folders have been removed along with their contents.
- The `README.md` has been modified slightly. 
- The logo link in the `README.md` now sits updated.
- The storybooks now run on 3 different ports, in parallel. (Fonts->8080, Vocabulary->8081, Vue-Vocabulary->8082)

2020-09-11 19:43 UTC, zackkrida approved these changes
Thanks for fixing vue-vocabulary too, we'll wait for Dhruv's review and get this merged!

2020-09-11 19:46 UTC, nimishbongale commented
> * Update the `brandImage` in `packages/fonts/.storybook/theme.js` to `https://raw.githubusercontent.com/creativecommons/vocabulary/master/logo.svg?sanitize=true` (fine for now since we're deprecating that storybook installation soon anyway)

@zackkrida 

This hasn't been done yet, but I'm guessing its okay for now? The `brandImage` is currently being fetched from `@creativecommons/vocabulary/assets/logos/products/vocabulary.svg`.

2020-09-11 19:53 UTC, zackkrida commented
@nimishbongale it can wait, but i see the brand image as: 

https://github.com/creativecommons/vocabulary/blob/0dfc58d0cd8c3fd47e52b90a8bfda603d837045a/packages/fonts/.storybook/theme.js#L30

2020-09-11 20:01 UTC, nimishbongale commented
> @nimishbongale it can wait, but i see the brand image as:
> 
> https://github.com/creativecommons/vocabulary/blob/0dfc58d0cd8c3fd47e52b90a8bfda603d837045a/packages/fonts/.storybook/theme.js#L30

My bad. I was looking at the wrong package's brandImage!

It could be changed. My take on this would be to leave it for now until we finally need to bid adieu to the fonts netlify site! 😢😃

2020-09-11 23:10 UTC, dhruvkb requested changes

2020-09-11 23:10 UTC, dhruvkb commented on README.md
> +You would need to have [nodejs](https://nodejs.org/en/) and [npm](https://www.npmjs.com/) installed.
When in doubt, see the ['About' page](https://nodejs.org/en/about/).
```suggestion
You would need to have [Node.js](https://nodejs.org/en/) and [npm](https://www.npmjs.com/) installed.
```

2020-09-11 23:10 UTC, dhruvkb commented on packages/fonts/deploy.sh
> +cp ../../README.md dist/
No I just suggested that with `sed` you can have [this part](https://github.com/creativecommons/vocabulary/pull/649/files#diff-04c6e90faac2675aa89e2176d2eec7d8R60-R67) individually tailored to each package.

2020-09-11 23:10 UTC, dhruvkb commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
Some of these might be deprecated or converged (like Notes, for example which is gone in favour of Docs, and Knobs which is superseded by Controls). Here's a [list of the latest addons](https://storybook.js.org/addons).

2020-09-11 23:10 UTC, dhruvkb commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
We can however work on this a part of #630.

2020-09-12 04:59 UTC, nimishbongale commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
Got you. I just updated storybook, and the rest followed. But hey, vue-vocabulary works as expected now! I guess we can leave the dependency bump as a part of the PR anyways?

2020-09-12 05:02 UTC, nimishbongale commented on packages/fonts/deploy.sh
> +cp ../../README.md dist/
Ahh right. Maybe this can be worked on as a part of a separate issue as well?

2020-09-12 05:06 UTC, dhruvkb commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
Just remove the deprecated packages if you can.

2020-09-12 05:10 UTC, nimishbongale commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
It should't break anything hopefully? I'll run it locally just to be sure, but yes.

2020-09-12 06:27 UTC, nimishbongale commented on packages/vue-vocabulary/package.json
> +    "@storybook/vue": "^6.0.21",
It did break one import, but now that stands fixed.

2020-09-12 09:32 UTC, dhruvkb requested changes

2020-09-12 09:32 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
I don't think this is how Controls works, the [`README.md`](https://www.npmjs.com/package/@storybook/addon-controls) have no mention of `withKnobs`.

2020-09-12 09:33 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
Everything else is perfect 👌

2020-09-12 10:42 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
@dhruvkb 

I had a look into the docs, and then into our source code. Turns out that the way to migrate is not just a simple replacement, and it would require quite some overhaul of old code. I further noticed that `addon-knobs` is imported and used in quite a few files, so it would basically be a rewrite of multiple files in our repo. 

I felt it needed another PR to be dealt with. Would be happy to deal with it as a separate issue!

If I just remove the deprecated `addon-knobs` then the code certainly breaks, so I'm guessing we would need a serious migration from knobs to controls.

2020-09-12 10:44 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
Also, our other packages may also need the same migration to be done on them.

2020-09-12 10:45 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
Let's keep knobs then. Please create a separate issue for the migration.

2020-09-12 12:25 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/preview.js
> +import { withKnobs } from '@storybook/addon-controls'
Roger that.

2020-09-12 14:40 UTC, dhruvkb approved these changes
We had a lot of back and forth on this, but I think this is perfect now.

2020-09-12 14:44 UTC, merged