[Fonts] add new icon bars
cc-archive/vocabulary-legacy pull request #657
Opened 2020-09-11 17:53 UTC by rochisha0

## Fixes

Fixes #640  by @panchovm 

## Description

I've added bars icon to the fonts.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-09-12 09:41 UTC, dhruvkb requested changes

2020-09-12 09:41 UTC, dhruvkb commented on packages/fonts/src/stories/vocabulary_icons.stories.mdx
> +  </IconItem>
Put this below flag as it comes after flag in the order.

2020-09-12 09:41 UTC, dhruvkb commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
Code `ea0b` is followed by `ea0c`. Please reconsult [the docs](https://cc-fonts.netlify.app/?path=/docs/fonts-contribution--page).

2020-09-12 10:57 UTC, rochisha0 commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@dhruvkb Should I keep this with after `caret` then?

2020-09-18 21:04 UTC, zackkrida requested changes

2020-09-18 21:04 UTC, zackkrida commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@rochisha0 you could move it after `caret` _or_ change the code to `ea0c` and keep it in the current position.

2020-09-18 21:04 UTC, zackkrida commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@rochisha0 wherever you move it, make sure the stories are in the same order as this file. Thank you!

2020-09-19 08:53 UTC, rochisha0 commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@zackkrida Done with the changes!

2020-09-20 06:26 UTC, dhruvkb requested changes, later dismissed

2020-09-20 06:26 UTC, dhruvkb commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@zackkrida @rochisha0 using the code `\e90c` breaks this as the `e9**` series is used for pointers.
<img width="318" alt="Screenshot 2020-09-20 at 11 54 34 AM" src="https://user-images.githubusercontent.com/16580576/93705094-0fcc2980-fb38-11ea-9240-ac9a596579be.png">

2020-09-21 20:21 UTC, zackkrida commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@rochisha0 i gave you bad advice; i hadn't read this section of the docs myself 😅 

so bars should belong to the `Symbols` section, so should go after `exclamation-circle` using the `/ea13` codepoint. Does that sound okay @dhruvkb?

2020-09-22 03:32 UTC, dhruvkb commented on packages/fonts/src/styles/vocabulary_icons.scss
> +  "bars": "\e90c",
@zackkrida I just recalled our SVG icons discussion which, when implemented, renders the issue of codepoints moot altogether. I've opened a new issue for that and we can probably just go with this PR as it is.

2020-09-22 15:48 UTC, zackkrida commented
Hi @rochisha0 thanks for this! We're actually going to simplify the fonts package and switch to svgs instead of an icon font, so we're going to merge your pr, but it will be the last icon added to the icon font 😅 and we'll keep it at the `\e90c` codepoint.

Moving forward, it will be much simpler to add new icons.

2020-09-22 15:48 UTC, merged

2020-09-22 16:01 UTC, rochisha0 commented
@zackkrida , not sure if I was able to follow your discussion but it seems like a good change. Thanks!

2020-09-22 16:44 UTC, zackkrida commented
😄 

@rochisha0 basically, right now fonts uses an 'icon font'. We are going to switch to providing users `.svg` files and svg code snippets that they can copy and paste.

If you were still confused about code point stuff, I'd say, forget about it! Haha