Update header component
cc-archive/vocabulary-legacy pull request #697
Opened 2020-09-29 07:28 UTC by chidexebere

## Fixes

Fixes #620  by @panchovm 

## Description
This updates the header and the global header component as specified in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=591%3A94).

This also adds a combined header story showing how the global header and default header can be used together.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-02 17:17 UTC, zackkrida commented
Hi @chidexebere I will review today and add the correct button. Thank you! :)

2020-10-05 19:54 UTC, zackkrida commented
Hi @chidexebere, this is really great work! Thanks for doing it. I think there's only one issue we need to tackle—the placement of the global header "Explore CC" tab. I have an idea but would be curious/open to your thoughts.

I _think_ we need to attach the "Explore CC" tab and the global header to the DOM separately. If we inject the "Explore CC" tab _inside_ the `.navbar-start` section, that will fix these kind of view problems:

<img width="1374" alt="Screen Shot 2020-10-05 at 8 39 48 AM" src="https://user-images.githubusercontent.com/6351754/95125076-22299400-06f0-11eb-8b80-bb31d0f0757f.png">
<img width="1701" alt="Screen Shot 2020-10-05 at 8 39 42 AM" src="https://user-images.githubusercontent.com/6351754/95125081-23f35780-06f0-11eb-9642-39766e23139c.png">
<img width="2508" alt="Screen Shot 2020-10-05 at 8 39 30 AM" src="https://user-images.githubusercontent.com/6351754/95125089-248bee00-06f0-11eb-8945-6c574f95e6b8.png">

Doing this would _also_ allow us to have local + donate fully right-aligned when there's no global header with something like `grid-auto-flow: row;`

Let me know what you think and if you're interested in fixing this. If not I can try, up to you.

2020-10-05 19:55 UTC, zackkrida approved these changes
Approved, and will merge without it if necessary, but I'd like to figure out improving the "explore cc" tab placement.

2020-10-07 21:04 UTC, chidexebere commented
> Hi @chidexebere, this is really great work! Thanks for doing it. I think there's only one issue we need to tackle—the placement of the global header "Explore CC" tab. I have an idea but would be curious/open to your thoughts.
> 
> I _think_ we need to attach the "Explore CC" tab and the global header to the DOM separately. If we inject the "Explore CC" tab _inside_ the `.navbar-start` section, that will fix these kind of view problems:
> 
> <img alt="Screen Shot 2020-10-05 at 8 39 48 AM" width="1374" src="https://user-images.githubusercontent.com/6351754/95125076-22299400-06f0-11eb-8b80-bb31d0f0757f.png">
> 
> <img alt="Screen Shot 2020-10-05 at 8 39 42 AM" width="1701" src="https://user-images.githubusercontent.com/6351754/95125081-23f35780-06f0-11eb-9642-39766e23139c.png">
> 
> <img alt="Screen Shot 2020-10-05 at 8 39 30 AM" width="2000" src="https://user-images.githubusercontent.com/6351754/95125089-248bee00-06f0-11eb-8945-6c574f95e6b8.png">
> 
> Doing this would _also_ allow us to have local + donate fully right-aligned when there's no global header with something like `grid-auto-flow: row;`
> 
> Let me know what you think and if you're interested in fixing this. If not I can try, up to you.

apologies for the late reply. Yes I think this might work. I will look at fixing it

2020-10-13 01:13 UTC, zackkrida requested changes
Fantastic work @chidexebere !

2020-10-13 01:13 UTC, zackkrida commented on packages/vocabulary/src/styles/header.scss
> +          grid-gap: $space-normal;
```suggestion
          display: flex;
          column-gap: $space-normal;
```

2020-10-13 01:13 UTC, zackkrida commented on packages/vocabulary/src/styles/header.scss
> +          grid-gap: $space-normal;
I would actually recommend flexbox here—so we can better support additional buttons in this row in the future. Also, it improves the appearance when the global header isn't present.

2020-10-13 01:14 UTC, zackkrida commented on packages/vocabulary/src/styles/header.scss
> +          grid-gap: $space-normal;
<img width="1045" alt="Screen Shot 2020-10-12 at 3 10 28 PM" src="https://user-images.githubusercontent.com/6351754/95804144-938fb680-0c9d-11eb-92e8-e4065db27539.png">

2020-10-21 05:34 UTC, zackkrida commented
@chidexebere Apologies for the delay on reviewing this! Looks great. My only note is that I think the menu items should be right-aligned (`.navbar-end .main-nav` should have `justify-content: flex-end` on desktop)


@panchovm could you review for feedback on spacing, sizing, etc.?

- [Preview Link](https://deploy-preview-697--cc-vocabulary.netlify.app/?path=/story/patterns-combined-header--interactive)

2020-10-21 20:40 UTC, panchovm requested changes
The following styles are incorrect:
# Desktop
1. **Locale:** For the header, locale component has a different background color and font size. Top margin must be `8px`.
2. **Donate button:** The background color is not correct and font size should be `12px`. Top margin must be `8px`.
3. **Explore CC:** The font-weight is incorrect.
4. **Main nav:** The font-size is incorrect. The¡ section must be aligned to right and have a top and bottom margin of `32px`.

# Mobile
1. **Menu (overall):** It should have a padding-bottom of `32px`.
2. **Dropdown item:** By default, child items should be hidden.
3. **Child item:** The text style is incorrect, it has a different font-family
4. **Explore CC:** I can't see the content of this tab.

It is crucial to follow the mockup definitions since this component is used in all CC sites.

2020-10-21 20:41 UTC, panchovm commented
I forgot to add that I notice a white border while seeing the preview on my laptop and phone. Maybe it's a Netlify issue or a front-end implementation.

2020-10-29 18:36 UTC, chidexebere commented
> @chidexebere Apologies for the delay on reviewing this! Looks great. My only note is that I think the menu items should be right-aligned (`.navbar-end .main-nav` should have `justify-content: flex-end` on desktop)
> 
> @panchovm could you review for feedback on spacing, sizing, etc.?
> 
> * [Preview Link](https://deploy-preview-697--cc-vocabulary.netlify.app/?path=/story/patterns-combined-header--interactive)

2020-10-29 18:37 UTC, zackkrida commented
@chidexebere did you mean to close this?

2020-10-29 18:38 UTC, chidexebere commented
> @chidexebere did you mean to close this?

now , was a mistake....please can you undo this. i cant undo it

2020-10-29 19:09 UTC, chidexebere commented
> The following styles are incorrect:
> 
> # Desktop
> 1. **Locale:** For the header, locale component has a different background color and font size. Top margin must be `8px`. (Fixed)
> 2. **Donate button:** The background color is not correct and font size should be `12px`. Top margin must be `8px`. (Fixed)
> 3. **Explore CC:** The font-weight is incorrect.(fixed)
> 4. **Main nav:** The font-size is incorrect. The¡ section must be aligned to right and have a top and bottom margin of `32px`. (fixed)
> 
> # Mobile
> 1. **Menu (overall):** It should have a padding-bottom of `32px`. (fixed)
> 2. **Dropdown item:** By default, child items should be hidden. (that is the default for an active navbar-dropdown on mobile but I added a hide class to fix this)
> 3. **Child item:** The text style is incorrect, it has a different font-family (fixed)
> 4. **Explore CC:** I can't see the content of this tab. (It has to be done with JavaScript adding the "is-active" class to the clicked tab with an onClick event. But you can test this by moving the "is-active" class from menu tab to the explore tab. You have to do the same under the tabs-content.)
> 
> It is crucial to follow the mockup definitions since this component is used in all CC sites.

2020-10-29 19:12 UTC, chidexebere commented
> I forgot to add that I notice a white border while seeing the preview on my laptop and phone. Maybe it's a Netlify issue or a front-end implementation.

 I think this is from storybook but I think a screen-shot will better explain

2020-11-03 06:21 UTC, obulat commented on packages/vocabulary/src/scripts/global_header.js
> +    const exploreButton = h('a', ['explore-button'], [document.createTextNode(NAVIGATION_TAB_TEXT)
Can we actually make it a `button`? This will be much more semantic, with no need for blank href, and clicking 'space' will also trigger a click event. The height will need some adjustments, but they shouldn't take long. Also, I didn't see `:focus` styles on locale and `explore cc` buttons.

2020-11-09 08:45 UTC, chidexebere commented on packages/vocabulary/src/scripts/global_header.js
> +    const exploreButton = h('a', ['explore-button'], [document.createTextNode(NAVIGATION_TAB_TEXT)
Apologies for the late reply (I have been ill). The exploreButton/opentab are buttons now. For the `:focus` styles, I think its because #752  is not merged yet.

2020-11-09 17:01 UTC, zackkrida commented on packages/vocabulary/src/scripts/global_header.js
> +    const exploreButton = h('a', ['explore-button'], [document.createTextNode(NAVIGATION_TAB_TEXT)
Okay @chidexebere and @hugosolar I'm going to mark this as resolved. We will merge in #752 after this PR, but in the same vocabulary release.

2020-11-13 07:12 UTC, zackkrida commented
@chidexebere It only took us a month and a half 😆, but this is finally ready! I added some focus states to the locale chooser and explore tab:

![focus-states](https://user-images.githubusercontent.com/6351754/99039612-bb3b9e00-252b-11eb-978f-dea4d91e748a.gif)

A huge **thank you** for taking this on and doing such a nice job.

2020-11-13 07:13 UTC, zackkrida approved these changes

2020-11-13 07:13 UTC, merged