Add Footer component to vue-vocabulary
cc-archive/vocabulary-legacy pull request #710
Opened 2020-10-06 05:26 UTC by akmadian

## Fixes

Fixes #689 by @zackkrida 

## Description

Adds the Footer component to vue-vocabulary.

## Technical details

This still needs some work RE adding props and vue-ifying the component.

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-06 06:47 UTC, dhruvkb requested changes
Before going into a deeper review, can we import the logos from Vocabulary instead of duplicating the assets in Vue Vocabulary as well?

2020-10-06 08:19 UTC, akmadian commented
@dhruvkb done! I don't know why I didn't think of that myself, good catch : )

2020-10-06 08:37 UTC, dhruvkb reviewed
This does look like it's leaning towards style B as per the discussion in #642, although I'm not sure if we had decisively chosen style A (since the issue is still open).

2020-10-07 14:25 UTC, zackkrida requested changes
Hi @akmadian this is a great start. As @dhruvkb implied, we do want to go with a 'child component' approach over an array prop for the menu links. You can see some discussion on this decision [here](https://github.com/creativecommons/vocabulary/issues/642) and an example implementation in the [original ticket](https://github.com/creativecommons/vocabulary/issues/689).

Some reasons for doing so:

- A child component approach. _can_ be compatible with an array data structure too, so it's more flexible. Example:
```vue
<template>
	<Parent>
		<Child v-for="child in myRandomArray" :href="child.href">
	</Parent>
</template>
```
- It's easier to extend in the future, especially with optional config per-item. Also allows for links that use scoped slots. Example:

```vue
<template>
	<Parent>
		<Child :is="MyCustomLink" href="/cool" :v-slot="{ active }" />
			<CheckmarkIcon v-if="active" /> Cool Page
		</Child>
		<Child is="a" href="https://othersite.com/great" onClick="doExtraAnalyticsThing" />
		<Child is="router-link" to="/my-page" />
	</Parent>
</template>
```

2020-10-07 14:25 UTC, zackkrida commented on packages/vue-vocabulary/.storybook/order.js
> +  'Patterns': [],
Great, thanks for doing this

2020-10-07 20:24 UTC, akmadian commented
Ahhh gotcha, I didn't catch that thread, will get started on that soon : )

2020-10-11 05:20 UTC, obulat commented
I just wanted to add a point about responsiveness: currently, the footer breaks on tablet screens because the rightmost column doesn't fit, and overflows its container:
![FooterProblem](https://user-images.githubusercontent.com/15233243/95670983-7cb46b80-0b9a-11eb-8066-b6bc306cb671.jpg)

I hadn't found any designs for footer on smaller screens, @panchovm, do we have them?.

2020-10-11 06:38 UTC, nimishbongale commented
I'm not sure about the designs, but here's how the footer looks on smaller screens in the vocabulary `docs` site I'm building:

![context](https://user-images.githubusercontent.com/43414361/95671820-b2684d00-0bb8-11eb-8b8f-968799f7a48f.PNG)

Maybe the same behaviour is expected off of the Vue-Vocabulary Footer component.

At `769x412`, the `opensource.creativecommons.org` footer breaks as well I guess:

![context5](https://user-images.githubusercontent.com/43414361/95671970-51417900-0bba-11eb-9448-2ebd7358a5cc.PNG)

Here's the expected behaviour imo:

![context4](https://user-images.githubusercontent.com/43414361/95671927-fc056780-0bb9-11eb-88f8-5bb31cbc4082.PNG)

2020-10-13 20:38 UTC, fcoveram commented
I am currently working on the footer's responsiveness and today [I added the mobile version](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24&viewport=-412%2C204%2C0.27819550037384033). I expect to add the other breakpoints in the following days. Thanks for bringing this @obulat @nimishbongale

2020-10-14 14:56 UTC, fcoveram commented
I just created a ticket (#725) to add the responsive versions of footer. The [Design Library page](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24&viewport=-73%2C237%2C0.23559321463108063) is updated.

2020-10-20 19:19 UTC, akmadian commented
I got side tracked by school, I'll work on implementing the child component approach today

2020-10-20 19:37 UTC, panchovm commented
Hi @akmadian 😊 nice to see you again

2021-09-15 07:30 UTC, closed without merging