implementation of dark mode in individual packages
cc-archive/vocabulary-legacy pull request #723
Opened 2020-10-13 17:35 UTC by neeraj-2

## Fixes

Fixes #699 by @nimishbongale 

## Description
Implements toggling b/w Dark mode and Light mode in the 3 storybooks `Fonts`, `Vocabulary` and `Vue-Vocabulary` 

## Demo:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/56186425/95816634-33505180-0d3d-11eb-94c5-037930904f67.gif)

![sun icon](https://user-images.githubusercontent.com/56186425/95873297-68849000-0d8d-11eb-809f-d70e5c9f7ead.png)
![moonicon](https://user-images.githubusercontent.com/56186425/95873310-6d494400-0d8d-11eb-9249-eecf6deefbb2.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>
![Uploading image.png…]()

2020-10-13 17:55 UTC, nimishbongale requested changes
Great work @neeraj-2 ! 🚀 

Couple of things:

1. Maybe it would be good idea if the storybooks started out on a light theme, and then upon button click toggling to the dark mode. Let the light mode be the default mode.

2. Is it possible to reposition that toggle button to the end of the tab bar?

Also @neeraj-2 you can go ahead and raise a normal PR after this. The build passes, and the changes I've suggested can be incorporated by you in the normal PR.

2020-10-13 17:55 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +})
Can we add a newline here? Looks cleaner imo. Formatting wise.

2020-10-13 17:55 UTC, nimishbongale commented on packages/vocabulary/.storybook/manager.js
> +})
Here as well.

2020-10-13 17:55 UTC, nimishbongale commented on packages/fonts/package.json
> +    "storybook-dark-mode": "^1.0.3",
👍

2020-10-13 17:55 UTC, nimishbongale commented on packages/vocabulary/package.json
> +    "storybook-dark-mode": "^1.0.3",
👍

2020-10-13 17:55 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +})
Here as well.

2020-10-13 17:55 UTC, nimishbongale commented on packages/vue-vocabulary/package.json
> +    "storybook-dark-mode": "^1.0.3",
👍

2020-10-13 18:12 UTC, neeraj-2 commented on packages/fonts/.storybook/manager.js
> +})
After the 7th line, right?

2020-10-13 18:16 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +})
After 8th.

There's a convention to have an endline at the end of file.

2020-10-13 18:19 UTC, neeraj-2 commented on packages/fonts/.storybook/manager.js
> +})
Sure 👍

2020-10-13 18:22 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +})
You'd need to do that for some other files as well. I've commented wherever the change needs to be done.

2020-10-13 18:38 UTC, neeraj-2 commented
> Great work @neeraj-2 ! 🚀
> 
> Couple of things:
> 
> 1. Maybe it would be good idea if the storybooks started out on a light theme, and then upon button click toggling to the dark mode. Let the light mode be the default one.
> 2. Is it possible to reposition that toggle button to the end of the tab bar?
> 
> Also @neeraj-2 you can go ahead and raise a normal PR after this. The build passes, and the changes I've suggested can be incorporated by you in the normal PR.

I will try to make the light theme as default, but I don't know if it is possible to reposition that toggle button to the end of the tab bar?

2020-10-13 18:41 UTC, nimishbongale commented
> I will try to make the light theme as default, but I don't know if it is possible to reposition that toggle button to the end of the tab bar?

- https://raw.githubusercontent.com/hipstersmoothie/storybook-dark-mode/master/example.gif

If you look closely here, they have it at the end of the tab bar.

2020-10-14 04:38 UTC, neeraj-2 commented
> > Great work @neeraj-2 ! 🚀
> > Couple of things:
> > 
> > 1. Maybe it would be good idea if the storybooks started out on a light theme, and then upon button click toggling to the dark mode. Let the light mode be the default one.
> > 2. Is it possible to reposition that toggle button to the end of the tab bar?
> > 
> > Also @neeraj-2 you can go ahead and raise a normal PR after this. The build passes, and the changes I've suggested can be incorporated by you in the normal PR.
> 
> I will try to make the light theme as default, but I don't know if it is possible to reposition that toggle button to the end of the tab bar?

 @nimishbongale I found that the initial theme is set to light , but if some user set dark theme and reload it, then the theme would be the dark one. Implies, whatever the theme user has selected, after reload we will get that theme only. So do we want that even after any reload whatever the theme earlier, still the theme should be light one?

2020-10-14 04:55 UTC, nimishbongale commented
@neeraj-2 I'm saying I'd want the defaukt

2020-10-14 04:58 UTC, nimishbongale commented
@neeraj-2 I'm saying that if a user hasn't selected dark mode initially, it should open in light mode. Then the users choice will be preferred.

2020-10-14 05:02 UTC, neeraj-2 commented
> @neeraj-2 I'm saying that if a user hasn't selected dark mode initially, it should open in light mode. Then the users choice will be preferred.
Great then, it is the behavior in the previous commits. Now the only requirement is to reposition the tab bar.So, I am focussing on that

2020-10-14 05:21 UTC, nimishbongale commented
> Great then, it is the behavior in the previous commits. Now the only requirement is to reposition the tab bar.So, I am focussing on that

@neeraj-2 

I'm not sure if the default behaviour is that way.

Head over [here](https://deploy-preview-723--cc-vocabulary.netlify.app/) (perhaps in incognito) to see your live code running. It by default opens the storybook in dark mode. I'd suggest it to open in light mode, then transition depending on user input.

2020-10-15 09:30 UTC, neeraj-2 commented
> > Great then, it is the behavior in the previous commits. Now the only requirement is to reposition the tab bar.So, I am focussing on that
> 
> @neeraj-2
> 
> I'm not sure if the default behaviour is that way.
> 
> Head over [here](https://deploy-preview-723--cc-vocabulary.netlify.app/) (perhaps in incognito) to see your live code running. It by default opens the storybook in dark mode. I'd suggest it to open in light mode, then transition depending on user input.

@nimishbongale 
I opened the link in incognito, I found, it opened the storybook in light mode. Is this not the case with you. Is this something related to the browser? Btw I am using `Google chrome`

2020-10-18 04:37 UTC, nimishbongale commented
Okay I'm not entirely sure why that happens, but I'm guessing it takes the default theme that is set in my chrome browser. I have dark mode enabled everywhere.

Okay @neeraj-2 you can go ahead and raise a normal PR with the changes as suggested. Let's get this merged 🚀

2020-10-18 04:37 UTC, closed without merging

2020-10-18 07:11 UTC, neeraj-2 commented
> Okay I'm not entirely sure why that happens, but I'm guessing it takes the default theme that is set in my chrome browser. I have dark mode enabled everywhere.
> 
> Okay @neeraj-2 you can go ahead and raise a normal PR with the changes as suggested. Let's get this merged 🚀

Sure @nimishbongale 👍