Vue header
cc-archive/vocabulary-legacy pull request #724
Opened 2020-10-14 13:39 UTC by obulat

## Fixes

Fixes #642 by @zackkrida 

## Description

This PR currently simply creates the skeleton of Vue Header component as described in the option A in the linked issue.

## Technical details

I renamed the component to VHeader because the Vue Essential style rule recommends multi-word component names to prevent naming conflicts in the future (especially since 'header' is an html element). Which prefix to choose ('V' or 'Vocab' or something else) is still subject to be discussed, though.

### TODO:
- Add Vocabulary styles
- Make it possible to have router-link as a MenuItem
- Review accessibility and keyboard accessibility, especially to MenuDropdown
???

## Tests

## Screenshots

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-14 23:13 UTC, zackkrida commented
I am fine with the `V` prefix!

For `Add vocabulary styles`, the problem is a silly one. The `<nav></nav>` element is missing the css class `.navbar` 😄 I pushed the fix.

2020-10-14 23:14 UTC, zackkrida commented
> Make it possible to have router-link as a MenuItem

This will help you! https://vuejs.org/v2/api/#is

2020-10-15 14:28 UTC, obulat commented
> > Make it possible to have router-link as a MenuItem
> 
> This will help you! https://vuejs.org/v2/api/#is

I've added the dynamic component for MenuItem, but I get this error when I have 'router-link' as a tag: 

![RouterLinkError](https://user-images.githubusercontent.com/15233243/96143205-bac1d000-0eb7-11eb-92ea-e4dc54dc2e55.png)
Because 'router-link' is unrecognized, I cannot interact with it in the storybook, either (using tab/click). This error is the reason I asked about adding 'vue-router' to 'vue-vocabulary'.

2020-10-19 17:55 UTC, obulat commented on packages/vue-vocabulary/package.json
> +    "bulma": "^0.9.1",
Isn't Bulma supposed to be as a vocabulary dependency?

2020-10-21 03:39 UTC, zackkrida requested changes
Great start Olga. If you want, we could try some pair programming later this week to go through any questions you have. Thanks!

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/.storybook/meta/usage.stories.mdx
> +  <VHeader app-name="My App"/>
This implementation should look like **Example A** here: https://github.com/creativecommons/vocabulary/issues/642

```vue
  <Header size="compact">
    <template v-slot:logo>
	  <CCSearchLogoSVG /> <!-- This could be an imported SVG for example -->
    </template>
    <template v-slot:menu-items>
      <MenuItem is="a" href="/whatever" label="Item One" /> <!-- is will be 'a' by default -->
      <MenuItem href="/whatever" label="Item Two" />
      <MenuDropdown label="Item Three">
        <MenuItem href="/whatever" label="Item A One" />
        <MenuItem href="/whatever" label="Item A Two" />
      </MenuDropdown>
    </template>
  </Header>
```

The `MenuItems` here are just example/dummy links, so feel free to change their labels or links.

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/library/components.json
> +  "patterns": ["Footer", "VHeader", "Locale"]
Good. I am comfortable with the `V` prefix for now.

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/package.json
> +    "bulma": "^0.9.1",
Yes, it looks like this line can be removed.

```suggestion

```

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/src/patterns/VHeader/MenuDropdown.vue
> +      <slot />
```suggestion
      <slot default />
```

Not necessary, but I appreciate that it gives extra clarity.

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/src/patterns/VHeader/MenuItem.vue
> +    },
This prop can be renamed to `is` for simplicity's sake. It does not need to be validated; the idea is that _any_ arbitrary component can be rendered. So the `label` and `href` props can be removed. 

Basically, vocabulary _doesn't and shouldn't_ need to know what kind of component is being rendered. It should stick the `.navbar-item` class on it, and that's it. The "external link" logic should also be removed.

Here's a simple example, via a `zack-button` component: https://codesandbox.io/s/jovial-lederberg-fnugg?file=/src/zack-button.vue

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/src/patterns/VHeader/VHeader.vue
> +            <MenuItem tag="a" href="/whatever" label="Item Two" />
- This _actual_ component shouldn't contain any `MenuItem` or `MenuDropdown`. They should be used when people _implement_ the component

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/src/patterns/VHeader/VHeader.vue
> +            <CCSearchLogo />
I like defaulting to the cc logo here. Good idea.

2020-10-21 03:39 UTC, zackkrida commented on packages/vue-vocabulary/src/patterns/VHeader/VHeader.vue
> +  // TODO: move these to Vocabulary css
👍 I like this approach. Implement overrides here first, then migrate to vocabulary later.

2020-11-05 18:50 UTC, nimishbongale commented
@obulat

This would actually be great to have as a part of Vue-Vocabulary, because I'd need it for the landing site as well! 😃

2020-11-16 20:46 UTC, merged