Updatinng colors
cc-archive/vocabulary-legacy pull request #733
Opened 2020-10-16 06:48 UTC by rochisha0

## Fixes

Fixes #729 by @panchovm 

## Description

It adds new colors (soft brand colors) and updates the existing ones (interaction and brand)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-16 07:32 UTC, dhruvkb requested changes
Please consistently use a single line format or a multiline format. Mixing both is not good.

2020-10-16 17:46 UTC, zackkrida requested changes
Almost donee, just need to remove the variable for `$color-brighter-dark-slate-blue`

2020-10-16 17:46 UTC, zackkrida commented on packages/vocabulary/src/styles/color.scss
>  $color-brighter-dark-slate-blue: rgb(16, 102, 231); // Also used for interaction
```suggestion
```

Please remove this line!

2020-10-16 17:52 UTC, rochisha0 commented on packages/vocabulary/src/styles/color.scss
>  $color-brighter-dark-slate-blue: rgb(16, 102, 231); // Also used for interaction
The color is being used in `button.css`.

2020-10-16 17:55 UTC, dhruvkb requested changes

2020-10-16 17:55 UTC, dhruvkb commented on packages/vocabulary/src/stories/color.stories.mdx
> +    colors={["rgb(0, 168, 3)"]}
The issue of some colours written in a single line and some not has not been resolved yet.

2020-10-16 18:18 UTC, rochisha0 commented on packages/vocabulary/src/stories/color.stories.mdx
> +    colors={["rgb(0, 168, 3)"]}
Done!

2020-10-16 19:00 UTC, zackkrida commented on packages/vocabulary/src/styles/color.scss
>  $color-brighter-dark-slate-blue: rgb(16, 102, 231); // Also used for interaction
Oh, that's right! Thank you for this reminder. I'm going to talk to @panchovm about this.

2020-10-16 19:07 UTC, zackkrida requested changes
Okay, `BrighterDarkSlateBlue` will remain as an _interaction_ color, but be removed from the brand colors. 

@rochisha0 thank your for your attention to detail, which brought this problem to my attention.

2020-10-16 19:07 UTC, zackkrida commented on packages/vocabulary/src/stories/color.stories.mdx
> -  />
Please re-add this (and make it one line for @dhruvkb 😄)

2020-10-16 19:07 UTC, zackkrida commented on packages/vocabulary/src/styles/color.scss
>  $color-brighter-dark-slate-blue: rgb(16, 102, 231); // Also used for interaction
@rochisha0 Please move this color to the `interaction` section of colors lower in the file. Thanks!

2020-10-17 04:22 UTC, rochisha0 commented on packages/vocabulary/src/styles/color.scss
>  $color-brighter-dark-slate-blue: rgb(16, 102, 231); // Also used for interaction
Done! @zackkrida

2020-10-17 04:22 UTC, rochisha0 commented on packages/vocabulary/src/stories/color.stories.mdx
> -  />
Done!

2020-10-19 20:31 UTC, panchovm commented
This ticket (#737) is related to changes indicated here

2020-10-20 13:48 UTC, rochisha0 commented
I have updated the PR as per issue #737

2020-10-21 05:53 UTC, zackkrida approved these changes
✅ 

@dhruvkb I am going to let the inconsistent single-line `ColorItem`s slide, as it is caused by prettier's line width. While we don't _officially_ have prettier enabled yet I am okay with following that rule for now.

2020-10-21 05:53 UTC, merged