Implementation of storybook-darkmode-addon
cc-archive/vocabulary-legacy pull request #739
Opened 2020-10-20 12:00 UTC by neeraj-2

## Fixes

Fixes #699 by @nimishbongale 

## Description
Implements toggling b/w Dark mode and Light mode in the 3 storybooks `Fonts`, `Vocabulary` and `Vue-Vocabulary` 

## Demo:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/56186425/95816634-33505180-0d3d-11eb-94c5-037930904f67.gif)

![sun icon](https://user-images.githubusercontent.com/56186425/95873297-68849000-0d8d-11eb-809f-d70e5c9f7ead.png)
![moonicon](https://user-images.githubusercontent.com/56186425/95873310-6d494400-0d8d-11eb-9249-eecf6deefbb2.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-20 17:55 UTC, nimishbongale requested changes
Great work!

Just a few final things:

1. The colors must be maintained from the original light theme that we have. 
2. On closer inspection, looks like the vocabulary logo on the left seems to have been overridden with the default storybook logo.
3. If you're unable to move the toggle `addon-tab` to the rightmost location, it's fine for now I suppose.

2020-10-20 17:55 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +  theme:themes.light
Does this override the current light theme that we have running?

2020-10-20 19:46 UTC, neeraj-2 commented on packages/fonts/.storybook/manager.js
> +  theme:themes.light
@nimishbongale , you are right . I think we should not even need to import '@storybook/theming', because., it is nothing to do with the dark theme. So, I am going to change it with the './theme' that was already in use so that we can maintain our  colors from the original light theme

2020-10-20 21:15 UTC, dhruvkb requested changes
Addons should be registered in `.storybook/main.js` as shown in the [Installation section](https://github.com/hipstersmoothie/storybook-dark-mode#installation).

2020-10-20 21:38 UTC, neeraj-2 commented
> Addons should be registered in `.storybook/main.js` as shown in the [Installation section](https://github.com/hipstersmoothie/storybook-dark-mode#installation).

thanks, @dhruvkb. So should I change the main.js file for each package as well

2020-10-21 04:21 UTC, dhruvkb commented
Yes @neeraj-2 you should update the `main.js` file in all three packages.

2020-10-21 05:29 UTC, nimishbongale requested changes
To change it the way we possibly want it, we'd have to look at the `hipstersmoothie/storybook-dark-mode` docs:

Configuration
Configure the dark and light mode by adding the following to your .storybook/preview.js file:

```javascript
export parameters = {
  darkMode: {
    // Override the default dark theme with a custom these
    dark: { ...themes.dark },
    // Override the default light theme with our custom theme
    light: { ...themes.normal }
  }
};
```
This would give us complete access to modify the theme as we want to.

2020-10-21 05:29 UTC, nimishbongale commented on packages/vocabulary/.storybook/manager.js
>    theme
This would add the previous theme, but the colours still won't be carried forward I think. They will still be pulled from the default theme that storybook provides.

2020-10-27 04:52 UTC, nimishbongale requested changes
Looks good @neeraj-2! Some minute changes only. Let's have this merged 🚀

2020-10-27 04:52 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Newline here

2020-10-27 04:52 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/themes/dark-theme.js
> +})
Here as well

2020-10-27 04:52 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Here too!

2020-10-27 04:52 UTC, nimishbongale commented on packages/vocabulary/.storybook/themes/dark-theme.js
> +})
Here as well

2020-10-27 04:52 UTC, nimishbongale commented on packages/vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Here as well

2020-10-27 04:52 UTC, nimishbongale commented on packages/fonts/.storybook/themes/dark-theme.js
> +})
Here too!

2020-10-27 04:54 UTC, nimishbongale commented on packages/fonts/.storybook/manager.js
> +import 'storybook-dark-mode/register'
```suggestion
import 'storybook-dark-mode/register'

```

2020-10-27 04:54 UTC, nimishbongale commented on packages/fonts/.storybook/themes/dark-theme.js
> +})
```suggestion
})

```

2020-10-27 04:55 UTC, nimishbongale commented on packages/vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
```suggestion
import 'storybook-dark-mode/register'

```

2020-10-27 04:55 UTC, nimishbongale commented on packages/vocabulary/.storybook/themes/dark-theme.js
> +})
```suggestion
})

```

2020-10-27 04:55 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
```suggestion
import 'storybook-dark-mode/register'

```

2020-10-27 04:56 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/themes/dark-theme.js
> +})
```suggestion
})

```

2020-10-27 05:11 UTC, neeraj-2 commented
> Looks good @neeraj-2! Some minute changes only. Let's have this merged 🚀

Sorry for this formatting problem again.I remember you suggested the same standard formatting in my previous PR

2020-10-27 05:48 UTC, nimishbongale commented
@neeraj-2

I'll add in a few changes after you are done. Don't worry about the formatting 👍

2020-10-27 05:53 UTC, neeraj-2 commented
> @neeraj-2
> 
> I'll add in a few changes after you are done. Don't worry about the formatting 👍

Thanks, @nimishbongale, don't know but something went wrong in the vocabulary/main.js file😒

2020-10-27 11:10 UTC, nimishbongale commented
#### What this PR does

1. Bumps up fonts to latest storybook version. It was badly in need of a bump anyways!
2. Adds storybook dark mode to all our 3 storybooks. The deploy previews should be sufficient to have a look at them.
3. Fixes some code structuring/formatting issues.

2020-10-27 13:37 UTC, neeraj-2 commented
> #### What this PR does
> 1. Bumps up `fonts` to latest storybook version. It was badly in need of a bump anyways!
> 2. Adds storybook dark mode to all our 3 storybooks. The deploy previews should be sufficient to have a look at them.
> 3. Fixes some code structuring/formatting issues.

Finally, the checks passed 😊.Thanks,@nimishbongale

2020-10-28 05:53 UTC, dhruvkb requested changes
Instead of defining the colors in the dark theme all over again, please extend both dark and light theme dictionaries from a common base.

```js
const base = {
  colorPrimary: '',
  colorSecondary: '',
  ...
}

const light = {
  base: 'light',
  ...base
}

const dark = {
  base: 'dark',
  ...base
}
```

2020-11-02 06:23 UTC, dhruvkb requested changes

2020-11-02 06:23 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/theme.js
> +    brandImage: 'https://svgshare.com/i/Qq2.svg',
Put this image with our logos itself. Don't host it on a third party site.

2020-11-02 06:23 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/theme.js
> +    barBg: 'rgb(255, 255, 255)',
Change these to a grayscale palette as well, similar to the values in the dark theme.

2020-11-02 06:23 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/theme.js
> +const lighttheme = create({
Camel-case for JS.
```suggestion
const lightTheme = create({
```

2020-11-02 06:23 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/theme.js
> +const darktheme = create({
Camel-case for JS.
```suggestion
const darkTheme = create({
```

2020-11-02 06:23 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Is this change required? I think removing the `manager.js` file would suffice.

2020-11-02 06:28 UTC, dhruvkb requested changes

2020-11-02 06:28 UTC, dhruvkb commented on packages/fonts/.storybook/preview.js
> +import { lighttheme,darktheme } from './theme'
```suggestion
import { lighttheme, darktheme } from './theme'
```

2020-11-02 06:28 UTC, dhruvkb commented on packages/fonts/.storybook/preview.js
> +    ]},
Use a formatter, can't close an array and the enclosing dictionary on the same line.

2020-11-02 06:28 UTC, dhruvkb commented on packages/fonts/.storybook/preview.js
> +    },
Remove trailing commas.

2020-11-02 06:28 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/theme.js
> +}
Default when defining using `export const` as you have done in the other theme files.

2020-11-02 06:28 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/preview.js
> +
```js
import { x, y } from './file'
```
is the cleaner, and more tree-shakeable, format.

2020-11-02 07:14 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/theme.js
> +const lighttheme = create({
Alright, understood!

2020-11-02 07:15 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
I tried doing that, but the addon doesn't work otherwise.

2020-11-02 07:15 UTC, nimishbongale commented on packages/fonts/.storybook/preview.js
> +    ]},
Alright, done!

2020-11-02 07:16 UTC, nimishbongale commented
@dhruvkb 

I'm still largely not done with this PR. I'll take all your suggestions into account though!

2020-11-02 09:05 UTC, dhruvkb commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Weird that they don't mention this in the `README.md`/docs for the addon.

2020-11-02 09:07 UTC, dhruvkb commented
@nimishbongale change this into a draft PR if you're still working on it and don't want to be disturbed by reviews while at work.

2020-11-02 09:44 UTC, nimishbongale commented
I'm nearly done! Thanks for the review (so later it'd be as perfect as possible)

I'll request a review once I'm done.

2020-11-02 10:48 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
Yeah true. I'll give it a try again, let's see!

I vaguely remembering it to not be working without that, but maybe it was due to some other reason.

2020-11-02 13:09 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/theme.js
> +    barBg: 'rgb(255, 255, 255)',
Is the change made correct? I'm not sure I get the grayscale palette part.

2020-11-02 13:10 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/manager.js
> +import 'storybook-dark-mode/register'
You were right @dhruvkb. I've gone ahead and removed the `manager.js` files.

2020-11-02 18:02 UTC, zackkrida approved these changes

2020-11-02 18:02 UTC, zackkrida commented on packages/fonts/.storybook/preview.js
> +        ...darkTheme
Very minor suggestion here—this is an unnecessary use of spread:

```
import myCoolObj from "my-fake-library"

let newCoolObj = myCoolObj
let coolNewObj = {...coolNewObj}
```

Keep in mind for other projects, these two lines don't do _exactly_ the same thing, but will work in this case.

2020-11-02 19:07 UTC, nimishbongale commented on packages/fonts/.storybook/preview.js
> +        ...darkTheme
> Keep in mind for other projects, these two lines don't do _exactly_ the same thing, but will work in this case.

Ooohhh okay! Learnt something new! Here's what the official docs mentions:

```javascript
export parameters = {
  darkMode: {
    // Override the default dark theme
    dark: { ...themes.dark },
    // Override the default light theme
    light: { ...themes.normal }
  }
};
```
I just went ahead and replaced the themes part 😅 

Maybe I'm missing something?

2020-11-04 17:18 UTC, zackkrida commented on packages/fonts/.storybook/preview.js
> +        ...darkTheme
It's fine, we can leave it as is.

2020-11-23 11:01 UTC, dhruvkb requested changes
Please don't modify files other than those directly related to the PR. This PR reformats many stories which should have been a separate PR solely concerned with refactoring.

2020-11-23 13:17 UTC, nimishbongale commented
> Please don't modify files other than those directly related to the issue. This PR reformats many stories which should have been a separate PR solely concerned with refactoring.

Those changes weren't consciously done by me 🤔 wonder why they even showed up!

I think PR #803 implicitly addresses this; where @obulat mentions her IDE added the linting changes.

2020-11-23 17:24 UTC, nimishbongale commented
I think there's a need to just raise a fresh PR instead of the current one as there are too many conflicts occurring (and I also think I made some errors while committing). The branch that we are working on here is also heavily outdated.  

@neeraj-2 thank you for your contribution! I'll raise a fresh PR and tag you there.

2020-11-23 17:24 UTC, closed without merging