[Feat] Issue #738 - Add @storybook/addon-a11y for Accessibility Testing
cc-archive/vocabulary-legacy pull request #740
Opened 2020-10-21 03:35 UTC by mcastre

## Fixes
Fixes [#738](https://github.com/creativecommons/vocabulary/issues/738) by @Dhruvi16 

## Description
Adds @storybook/addon-a11y Storybook plugin in packages/vocabulary

## Technical details
Currently, the a11y addon is set to all stories in the Vocabulary package. To disable the addon for a specific story, you can add to the `parameters` in the `<Meta>` tag to disable it. 
Example:
`<Meta title="Navigation/Breadcrumb" parameters={{ a11y: { disable: true } }/>`

## Tests
All unit tests passed.

## Screenshots
Example of a passing Accessibility test on a Story:
![image](https://user-images.githubusercontent.com/5702024/96670040-16f77a80-1324-11eb-8dac-d12008f2cf43.png)

Example of a failing Accessibility test:
![image](https://user-images.githubusercontent.com/5702024/96670110-37bfd000-1324-11eb-8ea5-7df1874609bd.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-21 04:31 UTC, dhruvkb requested changes
1. Don't install any packages in root `package.json`.
2. Please also install the addon in the Vue Vocabulary storybook.

2020-10-21 04:31 UTC, dhruvkb commented on package.json
> +  },
These aren't valid changes as we follow a two-space indentation rule in the project.

2020-10-21 14:42 UTC, mcastre commented on package.json
> +  },
@Dhruvi16 sorry that was not on purpose. Will revert

2020-10-21 18:26 UTC, mcastre commented
@Dhruvi16 @dhruvkb PR has been updated with requested changes.

2020-10-22 05:45 UTC, Dhruvi16 commented on package.json
> +  "packages": [
These changes should not reflect in your PR.

2020-10-22 17:25 UTC, mcastre commented on package.json
> +  "packages": [
I was asked to revert my changes to this file, even though it resolved the spacing issues

2020-10-22 17:35 UTC, zackkrida approved these changes

2020-10-22 17:35 UTC, zackkrida commented
Thank you @mcastre, I'm going to keep the spacing fixes you made to the root `package.json`.

2020-10-22 17:36 UTC, zackkrida approved these changes

2020-10-22 17:36 UTC, merged