readme-customisation for individual packages
cc-archive/vocabulary-legacy pull request #746
Opened 2020-10-26 21:13 UTC by neeraj-2

## Fixes

Related to #736 by @nimishbongale 

## Description

It updates readme for individual packages.

## Technical details

I have used the `sed` command that replaces **fonts** to name of the package, from the root `Readme `.

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-27 02:37 UTC, dhruvkb requested changes
We want to use `sed` to [find and replace](https://linuxize.com/post/how-to-use-sed-to-find-and-replace-string-in-files/#find-and-replace-string-with-sed) text in the `README.md` file.

2020-10-27 02:37 UTC, dhruvkb commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
File names are case-sensitive on Linux, i.e. `README.md`.

2020-10-27 02:38 UTC, dhruvkb commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
Also you would be using the `-i` flag on the `sed` command.

2020-10-27 02:39 UTC, dhruvkb commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
All modifications to the `README.md` file should be performed **before** publishing the package.

2020-10-27 02:41 UTC, dhruvkb commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
Not sure what `/say/` is in `/say/s/fonts/vocabulary`.

2020-10-27 02:42 UTC, dhruvkb commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
You cannot combine commands with "and" in Bash. Just write them one after the other.

2020-10-27 13:32 UTC, neeraj-2 commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
> File names are case-sensitive on Linux, i.e. `README.md`.

Ok,i will take care of it.





> All modifications to the `README.md` file should be performed **before** publishing the package.

So exactly after which line we should run this command?

> Not sure what `/say/` is in `/say/s/fonts/vocabulary`.

Here, I am trying to replace fonts with vocabulary in that particular line which contains` say`.Can u suggest some alternative?

> You cannot combine commands with "and" in Bash. Just write them one after the other.

Ok, I will take care of it

thanks, @dhruvkb, I would make the required changes as you mentioned.  Also, there is a doubt as `sed` does not work on Windows OS.So what is the alternative?
            Btw I also thought that we can have **README** for the individual package and just in deploy.sh file, rather than copying **README** from the root we can just copy **README** for the package itself. In that case, we will not require to run any other command.
            Looking forward for your suggestions.

2020-10-27 14:01 UTC, nimishbongale commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
@neeraj-2 

`sed` will work on your Git bash. Just type in `sed` and see if it gives the relevant help page. Be assured it will work in a similar manner in the linux bash.

The point here is that this entire repository is something called a `monorepo`, or in other terms one repository containing all the packages. We can't have individual `README.md` in the packages anymore, as it's just one entity at the end of the day. However, our packages are 3 _different npm packages_ requiring their own README's.

2020-10-27 14:09 UTC, neeraj-2 commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
> @neeraj-2
> 
> `sed` will work on your MINGW Git bash. Just type in `sed` and see if it gives the relevant man page. Be assured it will work in a similar manner on the linux bash.
> 
> The point here is that this entire repository is something called a `monorepo`, or in other terms one repository containing all the packages. We can't have individual `README.md` in the packages anymore, as it's just one entity. However, our packages are 3 _different npm packages_ requiring their own README's when we publish.

ok @nimishbongale .But when we should run it exactly as I did after publishing which is the wrong ig.

2020-10-27 14:12 UTC, nimishbongale commented on packages/vocabulary/deploy.sh
> +sed  -e '/say/s/fonts/vocabulary/' Readme.md and  sed -e '/cd/s/fonts/vocabulary/' Readme.md
The workflow would be something like;

Copy `README.md` from root -> Use sed to make the necessary changes -> ... ->Publish to npm 

https://github.com/creativecommons/vocabulary/blob/b7eb16e62e472612a1a69a5fa6f10d9fa4074c6c/packages/fonts/deploy.sh#L15

It would lie just after this line I mentioned.

2020-11-04 17:13 UTC, zackkrida commented
@nimishbongale Please re-review or complete this; thanks!

2020-11-08 06:24 UTC, nimishbongale commented on packages/vocabulary/deploy.sh
> +sed -i -e 's/say, fonts/here, vocabulary/' -e 's/cd packages\/fonts/cd packages\/vocabulary/' dist/README.md
I think this command does it!

2020-11-08 11:26 UTC, neeraj-2 commented on packages/vocabulary/deploy.sh
> +sed -i -e 's/say, fonts/here, vocabulary/' -e 's/cd packages\/fonts/cd packages\/vocabulary/' dist/README.md
thanks, @nimishbongale, LGTM 😊.

2020-11-14 05:28 UTC, nimishbongale commented
@zackkrida 

I think this PR is good to be merged. (and I guess it needs to be done before our next release so that the changes reflect in the npm readme's)

2020-11-16 01:08 UTC, zackkrida approved these changes
Great!

2020-11-16 01:09 UTC, merged