GSoD mid-internship major PR (Vocabulary Site v1) :rocket:
cc-archive/vocabulary-legacy pull request #747
Opened 2020-10-27 17:48 UTC by nimishbongale

## Description
Finally! It's out! (Caution: Major PR with lots of changes! 😄)

This PR adds the new **Vocabulary Site v1** which was built as a part of my GSoD'20 work.

Find the VueJS site in the `docs` folder.

## Technical details

The site is currently live on [https://cc-vocab-draft.surge.sh](https://cc-vocab-draft.surge.sh)

## Screenshots

![final-snap](https://user-images.githubusercontent.com/43414361/97341081-9f3cc900-18aa-11eb-89cc-c691cc911696.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-27 20:40 UTC, kgodey commented
Nice work @nimishbongale! @panchovm should probably review this too.

2020-10-28 13:58 UTC, panchovm approved these changes

2020-10-28 13:59 UTC, panchovm commented
Thanks for this work @nimishbongale

2020-10-29 04:30 UTC, Dhruvi16 commented
This looks awesome @nimishbongale 🎊

2020-10-29 04:31 UTC, Dhruvi16 approved these changes

2020-10-29 21:55 UTC, zackkrida requested changes
Great work @nimishbongale, a few things:

- The `vocabulary, a monorepo?' section, please remove the pointer cursor styles that makes those numbered items seem like links.
- @panchovm The black sections use the regular font in all-caps, I haven't seen this anywhere else. Does this fit the style guide?
- I'd like to see a max-width (or the `.container` class) on the contents of the black and white sections. They get _very_ stretched on large screens:
<img width="1523" alt="2020-10-29-39" src="https://user-images.githubusercontent.com/6351754/97636609-75d08a00-19dd-11eb-97eb-7bd5fff0c558.png">
- The images in the black sections overlap their containers; I'd rather see them with more padding

2020-10-30 03:35 UTC, nimishbongale commented
Alright @zackkrida. I'll make the necessary changes. Thanks for reviewing! 😄

2020-10-30 08:33 UTC, nimishbongale commented
> * I'd like to see a max-width (or the `.container` class) on the contents of the black and white sections. They get _very_ stretched on large screens:

@zackkrida 

I can set the max-width to some arbitrarily large value, but what do you think a suitable breakpoint should be?

Also, should I apply the `container` class to all the components we have? Some of them have it applied, while some don't.

2020-10-30 08:45 UTC, dhruvkb commented
@nimishbongale the `.container` class itself has the max-width set for various breakpoints.

2020-10-30 10:23 UTC, nimishbongale commented
Perfect. Sounds good!

2020-10-30 11:51 UTC, nimishbongale commented
Is this (roughly) the expected behaviour at large screen sizes?

![screencapture-localhost-8080-2020-10-30-17_02_28](https://user-images.githubusercontent.com/43414361/97700944-a3e3c600-1ad2-11eb-98c8-8f99036e2a26.png)

(The site has also been redeployed to view: [https://cc-vocab-draft.surge.sh](https://cc-vocab-draft.surge.sh) )

2020-10-30 12:44 UTC, panchovm commented
Yes! @zackkrida thanks for noticing it. There is a mix of headings using different styles. `H1` and `H2` must use the Heading 1A and Heading 2A, respectively.

2020-10-30 16:21 UTC, zackkrida commented
@nimishbongale i would try using the container class on a div inside the black backgrounds, so the black bg will be 100% wide but the content will be constrained.

2020-10-30 16:28 UTC, nimishbongale commented
I'm not 100% sure about this, but does a `notification-container` apply similar styles as a normal `container`?

2020-10-30 17:45 UTC, zackkrida commented
@nimishbongale You're using the notification classes in a way they're not really intended to be used. They're not well-suited for page layout. I would suggest something more like this:

https://codesandbox.io/s/ecstatic-ganguly-5t2g9?file=/src/App.vue

<img width="1523" alt="2020-10-30-41" src="https://user-images.githubusercontent.com/6351754/97739452-f3e76c00-1a83-11eb-8e95-66d6d4b1f815.png">

You can learn more about bulma's _column_ classes here: https://bulma.io/documentation/columns/options/

2020-10-30 17:56 UTC, nimishbongale commented
@zackkrida 

Ahha. Okay! I just looked for the most appropriate component! 😄 

Thank you!

2020-10-30 17:57 UTC, zackkrida commented
@nimishbongale I'm not the biggest bulma fan—it's hard to tell what best practices are from their docs! No worries 😅

2020-10-30 20:19 UTC, nimishbongale commented
@zackkrida 

I hope I've got it right this time! 😄

There's still some other work I've found that needs to be done (image assets cleanup, for starters). I'll keep pushing changes as & when they get reviewed.

2020-11-13 07:17 UTC, zackkrida commented
Hi @nimishbongale, apologies for the delay in fully reviewing this! Anytime we create a new web property, there's a little more thought put into reviewing content, audience, and design. We'd like to simplify this site significantly. Here are some notes:

## Design + Copy Changes

- [ ] Hero Section Edits:
  - [ ] Switch the hero section to match the styles on https://opensource.creativecommons.org/ you can skip the image: just have a plain white background
  - [ ] Replace "Design, Develop & Build with Creative Commons' very own design system!" with "Vocabulary is a cohesive design system and component library used on all Creative Commons web properties. The code is freely available to anyone and everyone to inspect, modify & use for their own purposes."
  - [ ] Add an installation code snippet `<p><code class="body-big margin-top-bigger is-inline-block">npm install @creativecommons/vocabulary</code></p>` below the new copy
  - Switch to two buttons:
	  - [ ] Go to Storybook (the unified one)
  	- [ ] Go to GitHub
- [ ] Remove "Our Mission" block, replace it with the 'package-group' section (that has a block for each package and "Visit npmjs" links)
- [ ] Give the "Why Vocabulary?" section the black background styles
- [ ] Move the stats blocks below this new header section
- [ ] Remove all other sections (sorry about this, I know you worked hard on the release carousel!)
- [ ] Change the navigation from jump links to the following external links:
  - [ ] [Release Notes](https://github.com/creativecommons/vocabulary/releases)
  - [ ] [Documentation](https://cc-vocabulary.netlify.app/)
  - [ ] [GitHub](https://github.com/creativecommons/vocabulary)
- [ ] Fix "Github" to "GitHub" in footer

2020-11-13 07:26 UTC, nimishbongale commented
Okay that's a lot of changes haha! 😄 Although I did expect them to be fair 🤔 

I did think the release carousel was a neat little thing to have. But yeah, maybe not! I'll get to working on them right away! 

Thanks for the review @zackkrida 👍

2020-11-13 11:27 UTC, nimishbongale commented
> Change the navigation from jump links to the following external links:
 Release Notes
 Documentation
 GitHub

In the footer? Or in the header?

2020-11-13 17:37 UTC, nimishbongale commented
Here's how it looks now:

(I haven't committed/deployed anything yet)

![screencapture-localhost-8080-2020-11-13-23_02_41](https://user-images.githubusercontent.com/43414361/99102824-a41caf00-2604-11eb-9ce8-fa1f98c83c77.png)

I'm yet to add some colors (I think the site looks bland as is, definitely could do with some color). I'm just afraid the site has too less content to show. But maybe the simpler the better!

2020-11-13 18:24 UTC, zackkrida commented
@nimishbongale I think it's great progress. 

- [ ] Add the word "GitHub" before the GitHub logo in the header menu
- [ ] Here is a header mockup I made, to add some color and consistency:
<img width="1444" alt="Screen Shot 2020-11-13 at 8 14 12 AM" src="https://user-images.githubusercontent.com/6351754/99106424-4f3b5300-2588-11eb-8d72-6a7032647c2d.png">
- [ ] Please remove the black monorepo section and add something like this above the 3 packages: 
<img width="1444" alt="Screen Shot 2020-11-13 at 8 20 35 AM" src="https://user-images.githubusercontent.com/6351754/99107190-8cecab80-2589-11eb-9bc5-b0874e0ca21d.png">


Those additions might provide enough color, for now! Thank you.

2020-11-14 01:26 UTC, zackkrida commented on docs/src/components/Hero.vue
> +            <p class="title is-1 has-text-gray">WELCOME TO THE DESIGN SYSTEM OF CREATIVE COMMONS OPEN SOURCE.</p><br>
One note: You should never write text all-caps in HTML, always use `text-transform: uppercase`. There's an important reason for this: Some screen readers will read all-caps as acronyms! So every. single. letter. will be read out loud.

2020-11-14 01:26 UTC, zackkrida commented on docs/src/components/Hero.vue
> +                <button class="button">VISIT GITHUB<center><br><i class="icon github"></i></center></button>
One note: You should never write text all-caps in HTML, always use `text-transform: uppercase`. There's an important reason for this: Some screen readers will read all-caps as acronyms! So every. single. letter. will be read out loud.

2020-11-14 01:27 UTC, nimishbongale commented on docs/src/components/Hero.vue
> +                <button class="button">VISIT GITHUB<center><br><i class="icon github"></i></center></button>
Ahha. Cool! I'll fix. Thanks!

2020-11-14 02:58 UTC, nimishbongale commented on docs/src/components/Hero.vue
> +            <p class="title is-1 has-text-gray">WELCOME TO THE DESIGN SYSTEM OF CREATIVE COMMONS OPEN SOURCE.</p><br>
Turns out the `title` class applies it by default. Wonder why I was inserting text in caps 🤔

2020-11-14 05:25 UTC, nimishbongale commented
@zackkrida 

How does this look now?

I've redeployed on [https://cc-vocab-draft.surge.sh](https://cc-vocab-draft.surge.sh) as well.

![screencapture-localhost-8080-2020-11-14-10_51_28](https://user-images.githubusercontent.com/43414361/99140393-bb40b880-2667-11eb-91fa-cb4cb8d255ed.png)

2020-11-16 01:10 UTC, zackkrida commented
@nimishbongale it looks **great**! Thanks for iterating on the design so quickly. 

One last thing... please add the `small` class to the buttons in the hero, so they match the os site, and add a max-width to the 'subtitle' block in the hero, something like this:

```css
width: 500px;
max-width: 100%;
```

2020-11-16 11:49 UTC, nimishbongale commented
@zackkrida 

I've added the necessary styles. I guess we could do with some sort of an image on the right hand side? I don't really know, it's just a thought! 😄 

![screencapture-cc-vocab-draft-web-app-2020-11-16-17_19_02](https://user-images.githubusercontent.com/43414361/99249309-eaa22180-282f-11eb-8ff2-83f8ab4e2ab4.png)

2020-11-16 15:20 UTC, zackkrida commented
> I guess we could do with some sort of an image on the right hand side? 

Eventually, yes, we'd just want it to really match the cc branding, which can be hard to come up with, and we don't have the resources for our designer to design something right now.

2020-11-16 16:00 UTC, zackkrida approved these changes

2020-11-17 20:25 UTC, kgodey commented
I recommend removing the Why Vocabulary section, it takes up a lot of space and doesn't add much information. All CC projects are required to use Vocabulary for brand consistency so it's not really a choice...

2020-11-17 20:40 UTC, zackkrida commented
@kgodey Agreed, but I think we still need a section design-wise to break up the package cards and the stats cards. Perhaps we just deemphasize the section; something like this?

![cc-vocab-draft surge sh_](https://user-images.githubusercontent.com/6351754/99445104-35b84500-28c1-11eb-9344-386d47dc90ac.png)

Also @nimishbongale please make sure the 'multiple ways to use' section has a `container` inside of it, it looks like it's contents expand to full-width right now.

2020-11-18 16:44 UTC, nimishbongale commented
Here's how it looks now. I've redeployed it as well.

![screencapture-cc-vocab-draft-surge-sh-2020-11-18-22_09_15](https://user-images.githubusercontent.com/43414361/99559957-57155000-29eb-11eb-9535-f9ecc7032f61.png)

2020-11-18 18:27 UTC, kgodey commented
Looks good, I would reduce the whitespace in the Why Vocabulary section similar to @zackkrida's mockup.

2020-11-19 18:02 UTC, nimishbongale commented
> Looks good, I would reduce the whitespace in the Why Vocabulary section similar to @zackkrida's mockup.

Done! I've redeployed it, do have a look! 😄

- https://cc-vocab-draft.surge.sh

2020-11-25 03:31 UTC, merged

2020-11-25 03:32 UTC, zackkrida commented
It's merged! 🎊 
Thank you so much @nimishbongale — I will let you know when i've deployed and set things up on Netlify.

2020-11-25 03:59 UTC, nimishbongale commented
🎊 🎊

@dhruvkb @zackkrida @kgodey @panchovm @Dhruvi16 @obulat 

A big thank you to everyone for all their support and guidance! 👏  

It's for sure a wonderful feeling! 😄

2020-11-25 12:26 UTC, panchovm commented
Thank you @nimishbongale 🙌