Fixed card-layout
cc-archive/vocabulary-legacy pull request #755
Opened 2020-11-02 16:07 UTC by Yashs911

## Fixes

Fixes #753  by @obulat 

## Description

Added overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-11-03 05:30 UTC, dhruvkb requested changes
Out of the 3 lines, two should be discarded as they are either aliases or deprecated.

2020-11-03 05:30 UTC, dhruvkb commented on packages/vocabulary/src/styles/card.scss
> +            word-break: break-word;
This is deprecated now, in favour of `overflow-wrap: break-word`.

2020-11-03 05:30 UTC, dhruvkb commented on packages/vocabulary/src/styles/card.scss
> +            word-wrap: break-word;
This is just an alias for `overflow-wrap`.

2020-11-03 05:38 UTC, zackkrida requested changes

2020-11-03 05:38 UTC, zackkrida commented on packages/vocabulary/src/styles/card.scss
> +            word-break: break-word;
```suggestion
            overflow-wrap: break-word;
```

2020-11-03 05:38 UTC, zackkrida commented on packages/vocabulary/src/styles/card.scss
> +            word-break: break-word;
`overflow-wrap` is the only property needed.

2020-11-03 05:47 UTC, Yashs911 commented on packages/vocabulary/src/styles/card.scss
> +            word-break: break-word;
@zackkrida overflow-wrap: break-word; doesn't work for horizontal cards
![cards](https://user-images.githubusercontent.com/64412143/97953287-059f7b00-1dc6-11eb-8611-b34621152849.JPG)

2020-11-03 05:50 UTC, Yashs911 commented on packages/vocabulary/src/styles/card.scss
> +            word-wrap: break-word;
@dhruvkb according to this document overflow-wrap doesn't work on some browser.
![card](https://user-images.githubusercontent.com/64412143/97953471-98401a00-1dc6-11eb-99bb-004338ee8a37.JPG)

2020-11-03 06:17 UTC, obulat commented on packages/vocabulary/src/styles/card.scss
> +            word-wrap: break-word;
It was implemented in Firefox v49, so you can leave only one line as Zack suggested. 
Note: Css-tricks, whose article I linked to in the issue, is a great site, but some articles are dated, apparently. It's always useful to check mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap. They have a table of browser compatibility in the bottom.
Sorry for the incomplete lead, @Yashs911!

2020-11-03 06:22 UTC, Yashs911 commented on packages/vocabulary/src/styles/card.scss
> +            word-wrap: break-word;
@obulat But overflow-wrap: break-word; does not work for horizontal cards. So should I use both overflow-wrap: break-word; and word-break: break-word; ?

2020-11-03 06:33 UTC, Yashs911 commented on packages/vocabulary/src/styles/card.scss
> +            word-break: break-word;
@zackkrida Using **overflow-wrap: anywhere;** solves the problem.

2020-11-04 17:19 UTC, zackkrida approved these changes
👍

2020-11-04 17:19 UTC, merged