Add tooltip to vocabulary
cc-archive/vocabulary-legacy pull request #777
Opened 2020-11-10 14:04 UTC by Dhruvi16

## Fixes

Fixes #769 by  @Audiosutras

## Description

Add tooltip to Vocabulary

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-11-19 21:58 UTC, obulat commented
Are you currently working on this, Dhruvi? @Dhruvi16 This looks like a good start. I guess the next steps should be:
1. Center the tooltip in relation to the tooltip opener.
2. Adjust the border on the triangle: 
![image](https://user-images.githubusercontent.com/15233243/99729038-2f67cb80-2a6f-11eb-8a68-409e6fbe69d3.png)
3. Add a modifier class to open the tooltip on the top, bottom, left, and right sides of the opener.

2020-11-23 05:02 UTC, Dhruvi16 commented
On it!

2020-11-23 10:29 UTC, Dhruvi16 commented
@obulat @zackkrida Check this out.

2020-11-27 09:04 UTC, obulat requested changes
The alignment of the tooltip's tip is still a tiny bit off: 
![2020-11-27_09-54-01](https://user-images.githubusercontent.com/15233243/100430950-54020b80-304c-11eb-88ec-18f94bcb3aec.png)

I wonder if the distance of the tip from the side of the tooltip should be in percentages, or fixed, @panchovm ?

2020-11-27 09:04 UTC, obulat commented on packages/vocabulary/src/styles/tooltip.scss
> +    @extend .padding-horizontal-small;
We have recently had a PR that removed all @extends from Vocabulary, because they make managing dependencies (mainly bulma) more difficult (you can read more about the reasons [here](https://github.com/creativecommons/vocabulary/issues/781)). So, please, rewrite these without @extend.

2020-11-27 12:17 UTC, panchovm commented
I would say fixed. Although I agree with you that looks odd. I also noticed that the tip has some pixels visible in the white background.

<img width="179" alt="Screen Shot 2020-11-27 at 09 11 22" src="https://user-images.githubusercontent.com/895819/100448124-9a795980-3090-11eb-9cfe-d5670d4477dd.png">

The tooltip component in [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=9101%3A112&viewport=-2234%2C-251%2C1.8238146305084229) has a margin from the closest side of `24px`. Here the example that you're showing

![Screen Capture on 2020-11-27 at 09-14-12](https://user-images.githubusercontent.com/895819/100448571-41f68c00-3091-11eb-81c5-a75fcd77ceab.gif)

2020-11-29 04:07 UTC, Dhruvi16 commented
![Screenshot from 2020-11-29 09-35-35](https://user-images.githubusercontent.com/34674462/100533091-7cddf880-3226-11eb-887a-9a4f606613cf.png)
The tooltip looks different on my screen.

2020-11-29 04:17 UTC, Dhruvi16 commented
> I would say fixed. Although I agree with you that looks odd. I also noticed that the tip has some pixels visible in the white background.
> 
> <img alt="Screen Shot 2020-11-27 at 09 11 22" width="179" src="https://user-images.githubusercontent.com/895819/100448124-9a795980-3090-11eb-9cfe-d5670d4477dd.png">
> 
> The tooltip component in [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=9101%3A112&viewport=-2234%2C-251%2C1.8238146305084229) has a margin from the closest side of `24px`. Here the example that you're showing
> 
> ![Screen Capture on 2020-11-27 at 09-14-12](https://user-images.githubusercontent.com/895819/100448571-41f68c00-3091-11eb-81c5-a75fcd77ceab.gif)

This fixed 24px might work in some cases but when the beak is on the left or right side and the height of the tooltip is shorter than it will break.

2020-11-30 12:35 UTC, panchovm commented
@Dhruvi16 Right. Then it makes sense to define minimum values for height and width.

2020-12-15 09:13 UTC, dhruvkb requested changes
I think a lot of the (somewhat repetitive) rules and calculations for `.top`, `.right`, `.bottom` and `.left` could be simplified using SCSS list, map and math features.

2021-09-15 07:30 UTC, closed without merging