guidelines_updated_for_npm@7
cc-archive/vocabulary-legacy pull request #784
Opened 2020-11-12 15:37 UTC by neeraj-2

## Fixes

Fixes #780 by @neeraj-2 

## Description

It updates our `Readme` for npm@7

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-11-12 18:12 UTC, nimishbongale commented on README.md
> +npm run storybook --legacy-peer-deps
Are you sure this option needs to be passed to all the steps? Or just the installation ones? Can you check?

2020-11-12 19:44 UTC, neeraj-2 commented on README.md
> +npm run storybook --legacy-peer-deps
@nimishbongale, when I discussed this problem, I added the tag "--legacy-peer-deps" with all commands. And I noted that everything was running fine. But I rechecked it now as u said, then after the installation command, when I ran "npm run build --legacy-peer-deps",
I got these errors  🤔 : 


![image](https://user-images.githubusercontent.com/56186425/98988294-7294dc80-254d-11eb-9e8f-1782ff8e090b.png)

2020-11-12 19:58 UTC, obulat commented on README.md
> +npm run storybook --legacy-peer-deps
Could you try updating npm to 7.0.9 or 7.0.10? It seems that they've fixed the need for administrator privileges about 6 days ago, by using junctions instead of symlinks.

2020-11-13 01:58 UTC, zackkrida requested changes
Looks good, I'm going to resolve the issue with passing the option to all steps and merge. Thank you!

2020-11-13 01:58 UTC, zackkrida commented on README.md
> +npm run storybook --legacy-peer-deps
This would only need to be added to `npm install`, none of the other steps.

2020-11-13 01:58 UTC, zackkrida commented on README.md
> +npm run storybook --legacy-peer-deps
```suggestion
npm run setup # (optional for npm v7 & above)
npm run build
npm run storybook
```

2020-11-13 01:58 UTC, zackkrida commented on README.md
> +npm run storybook --legacy-peer-deps
```suggestion
npm run build
npm run storybook
```

Only needed for the install step.

2020-11-13 01:59 UTC, zackkrida approved these changes

2020-11-13 02:00 UTC, merged