Replacement of @extends
cc-archive/vocabulary-legacy pull request #793
Opened 2020-11-17 08:23 UTC by neeraj-2

## Fixes

Fixes #781 by @zackkrida 

## Description

This PR replaces the use of  `@extends ` in .scss files of **Vocabulary Package**

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-11-17 10:38 UTC, nimishbongale commented on packages/vocabulary/src/styles/button.scss
> +
Maybe this extra line space can be removed?
```suggestion
```

2020-11-17 10:38 UTC, nimishbongale commented on packages/vocabulary/src/styles/button.scss
> +
Here as well, to match the spacing in the rest of the sections.
```suggestion
```

2020-11-18 13:01 UTC, obulat approved these changes
Looks good, great job, @neeraj-2 !

2020-11-18 13:01 UTC, obulat commented on packages/vocabulary/src/styles/card.scss
> +                    padding: none;
Padding should be set to 0.

2020-11-18 13:22 UTC, neeraj-2 commented on packages/vocabulary/src/styles/card.scss
> +                    padding: none;
thanks, @obulat for reviewing it, ok I will make the required changes. And in files (button. scss, image. scss,sidebar_menu.scss,), I did the same mistake, so should I change them too?

2020-11-18 20:19 UTC, zackkrida requested changes
The one thing I want to confirm: There's several places where `.padding-horizontal-*` was replaced with `padding-left: *`. Wouldn't that need to set `padding-right: *` too? Same for `padding-horizontal-*` with top and bottom. 

I might be mistaken/missing something.

2020-11-18 20:19 UTC, zackkrida commented on packages/vocabulary/src/styles/notification.scss
> +      padding-top: $space-normal;
Wouldn't `.padding-vertical-normal` set the top _and bottom_ padding?

2020-11-18 20:19 UTC, zackkrida commented on packages/vocabulary/src/styles/image.scss
> +      padding-left: $space-small;
Wouldn't `.padding-horizontal-small` set the left _and right_ padding?

2020-11-19 07:38 UTC, obulat commented on packages/vocabulary/src/styles/image.scss
> +      padding-left: $space-small;
Definitely! I missed that.

2020-11-19 08:46 UTC, neeraj-2 commented on packages/vocabulary/src/styles/image.scss
> +      padding-left: $space-small;
I will update

2020-11-20 18:36 UTC, zackkrida approved these changes
Great!

2020-11-20 18:44 UTC, neeraj-2 commented
> Great!

Thanks, @zackkrida, and @obulat 😊!

2020-11-20 18:48 UTC, merged