Add 'main' to package.json to make Vue package installable
cc-archive/vocabulary-legacy pull request #803
Opened 2020-11-22 09:13 UTC by obulat

## Fixes

Fixes #801 by @obulat 

## Description

This PR makes it possible to import and use Vue Vocabulary in other projects. 

## Technical details

By default, when you install a library using npm and try to import it, it looks for its 'index.js' inside the 'node_modules'. So, when we install vue-vocabulary, 'node_modules' contains a folder with the following files:
```
 node_modules
LICENSE
package.json
README
vue-vocabulary.common.js
vue-vocabulary.css.js
vue-vocabulary.umd.js
```
When we import it in an App as  `import VueVocabulary from '@creativecommons/vue-vocabulary'`, we actually import default from the '@creativecommons/vue-vocabulary/index.js' file. "main" key in `package.json` overrides this behavior, so that the '@creativecommons/vue-vocabulary/<value of package.json[main]>' file is used as the import.

Now, we can use Vue Vocabulary in two ways:
1. import it  `import VueVocabulary from @creativecommons/vue-vocabulary` and register all components with the Vue app by using `vue.use(VueVocabulary)` inside 'main.js' file, and use necessary components in other components without importing or registering them individually.
2. import specific component inside an app component (e.g. Chooser's 'Stepper.vue'): `import { VButton } from @creativecommons/vue-vocabulary` and register it inside the 'components' object: `components: { VButton, ... }`.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-11-22 09:15 UTC, obulat commented
My ide also added some linting changes...

2020-11-23 05:27 UTC, nimishbongale commented
Maybe as a part of this PR, we could also update the [corresponding docs](https://github.com/creativecommons/vocabulary/blob/master/packages/vue-vocabulary/.storybook/meta/usage.stories.mdx#installation-1 ) to something like:

```html
<script type="text/javascript" src="https://unpkg.com/@creativecommons/vue-vocabulary/vue-vocabulary.umd.min.js"></script>
```
OR
```html
<script type="module" src="https://unpkg.com/@creativecommons/vue-vocabulary"></script>
```
I don't know if this is a norm or not, but JS libraries tend to have a src URL ending with a `.js`. Just like how vocabulary does.

2020-11-24 04:26 UTC, dhruvkb requested changes
The change to `package.json` is fine. Can we have the refactoring in a separate PR, as PRs should be atomic?

2020-11-24 20:36 UTC, obulat commented
> The change to `package.json` is fine. Can we have the refactoring in a separate PR, as PRs should be atomic?

Sure, I will revert the changes!

2020-11-25 03:18 UTC, zackkrida requested changes

2020-11-25 03:18 UTC, zackkrida commented on packages/vue-vocabulary/package.json
> +  "main": "vue-vocabulary.umd.min.js",
```suggestion
  "main": "vue-vocabulary.common.js",
  "unpkg": "vue-vocabulary.umd.min.js",  
```

I would recommend we default to the `cjs` modules, but specify `unpkg` uses the `umd` build.

We can assume most non-cdn consumers of vocabulary are using the library in an app where their code is being compiled by a a build step.

2020-11-25 05:44 UTC, obulat commented
> Maybe as a part of this PR, we could also update the [corresponding docs](https://github.com/creativecommons/vocabulary/blob/master/packages/vue-vocabulary/.storybook/meta/usage.stories.mdx#installation-1) 
Thank you for these suggestions! I added the necessary documentation (and checked unpkg and jsdelivr sites to see if it works)

2020-11-25 05:47 UTC, obulat commented on packages/vue-vocabulary/package.json
> +  "main": "vue-vocabulary.umd.min.js",
I added the requested changes.

I wonder what is the reason for using `cjs` modules? At first, I thought it was probably the size, but `umd`, and especially `umd.min`, are not larger. Is it more performant?

2020-11-25 07:25 UTC, zackkrida commented on packages/vue-vocabulary/package.json
> +  "main": "vue-vocabulary.umd.min.js",
Let's chat about modules on our next call. Could be fun. There's a lot going on there—a bit too much for a message here. I will say, there's nothing _wrong_ about using `umd` as the `main`...right now, it's mostly just a _convention_ to use `cjs` in the main field.

2020-11-25 07:29 UTC, zackkrida requested changes
Small tweaks :)

2020-11-25 07:29 UTC, zackkrida commented on packages/vue-vocabulary/.storybook/meta/usage.stories.mdx
> +<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@creativecommons/vue-vocabulary/vue-vocabulary.umd.min.js"></script>
These links should actually stay `https://unpkg.com/@creativecommons/vue-vocabulary`; that unpkg package.json field i gave you will make these links resolve automatically to the umd file.

2020-11-25 07:29 UTC, zackkrida commented on packages/vue-vocabulary/package.json
> +  "browser": "vue-vocabulary.umd.min.js",
```suggestion
```

The `browser` field should actually only be used if there _isn't_ a `main` field.

2020-11-25 07:55 UTC, nimishbongale commented on packages/vue-vocabulary/.storybook/meta/usage.stories.mdx
> +<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@creativecommons/vue-vocabulary/vue-vocabulary.umd.min.js"></script>
I'm sure it would, but I was just thinking maybe it is a convention to have the URL's ending with a `.js`?

2020-12-02 02:01 UTC, zackkrida approved these changes

2020-12-02 02:01 UTC, merged