Added small caption and the H6 Header B to typography.scss and updated the docs to reflect the change
cc-archive/vocabulary-legacy pull request #827
Opened 2020-12-12 07:26 UTC by akshayprabhu200

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Technical details

## Tests

## Screenshots

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-12-12 10:32 UTC, dhruvkb requested changes
Please don't commit changes to `package.json` and `package-lock.json` in PRs.

2020-12-12 11:53 UTC, akshayprabhu200 commented
@dhruvkb I have deleted the file from the commit in the new commit. Is that correct?

2020-12-12 12:02 UTC, dhruvkb requested changes
Don't delete `package-lock.json` from the repo, just don't commit it to your PR. See instructions on [this StackOverflow answer](https://stackoverflow.com/a/44355701/2601645). Also there are 3 `package-lock.json` files in the PR, remove all of them.

2020-12-12 12:47 UTC, akshayprabhu200 commented
Updated the latest PR to match the required changes. Only two changes made, any idea why the deploy is failing though?

2020-12-12 18:56 UTC, obulat requested changes
There are many formatting changes (extra semicolon, removed newlines, etc. ), @akshayprabhu200 . I guess you ran a linter on the files, could you revert those changes, too, and leave only the changes you've made? It is really difficult to see what you've actually changed this way.
Also, could you add the h6 header style to the storybook? I've added comments inline.

2020-12-12 18:56 UTC, obulat commented on packages/vocabulary/src/stories/typography.stories.mdx
> +`;
h6 title example should be added here.

2020-12-12 18:56 UTC, obulat commented on packages/vocabulary/src/stories/typography.stories.mdx
>  <p class="subtitle is-5">Subtitle 5</p>
h6 subtitle should also be added here.

2020-12-13 11:36 UTC, akshayprabhu200 commented
@obulat added the changes you requested in the stories and reversed Prettier's formatting, it was enabled by default in my VScode config.

2020-12-16 12:21 UTC, akshayprabhu200 commented
Hi, any update on this?

2021-01-04 18:13 UTC, obulat requested changes

2021-01-04 18:13 UTC, obulat commented on packages/vocabulary/src/stories/typography.stories.mdx
> +<p class="title is-5">Title 6</p>
Classname for Title 6 should probably be `is-6`, not `is-5`.

2021-01-04 18:19 UTC, obulat commented
Hi, @akshayprabhu200 , sorry for the late review, today is the first day after the winter shutdown for CC.
I've left a couple of notes inline. Also, please, revert the changes to the `package.json` and `package-lock.json` files.

2021-01-05 03:57 UTC, akshayprabhu200 commented
@obulat made the changes you requested in the title (and found the subtitle had the same issue, fixed that too). As for the `package.json` and it's been added by [this commit ](https://github.com/creativecommons/vocabulary/pull/827/commits/3603a3a6e5e131cb51f92b19db5b23b1d22aeeee) which was added to fix update dependencies. Should I reverse that?

2021-01-05 04:59 UTC, obulat commented
> @obulat made the changes you requested in the title (and found the subtitle had the same issue, fixed that too). As for the `package.json` and it's been added by [this commit ](https://github.com/creativecommons/vocabulary/pull/827/commits/3603a3a6e5e131cb51f92b19db5b23b1d22aeeee) which was added to fix update dependencies. Should I reverse that?

Oh, sorry about that 🤦 I completely forgot about it: I was reviewing your PR and then forgot to change the branch before pushing this change. Yes, please, could you reverse that commit?

2021-01-05 06:38 UTC, akshayprabhu200 commented
@obulat Done 👍

2021-01-05 06:40 UTC, obulat approved these changes

2021-09-15 07:30 UTC, closed without merging