Fixed header compact and getting started page bug
cc-archive/vocabulary-legacy pull request #829
Opened 2020-12-12 16:56 UTC by darkshredder

## Fixes
Fixes #828 

## Description
I have changed color of navbar-item to default as grey-dark earlier it was white

## Screenshots
![Screenshot from 2020-12-12 22-24-07](https://user-images.githubusercontent.com/52625656/101989787-cae40900-3cc8-11eb-8b0a-a3a9f22f5a98.png)

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ x My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-12-12 18:38 UTC, obulat commented
Thank you for your PR, @darkshredder ! The color you used, $grey-dark, is a color name from Bulma. Vocabulary uses its own color set, and the color used in the header is `$color-dark-gray`: https://github.com/creativecommons/vocabulary/blob/960dc85ba776f47ab49d3428772a6030162a339a/packages/vocabulary/src/styles/color.scss#L17
Can you change the color name?

2020-12-12 19:39 UTC, darkshredder commented
> Thank you for your PR, @darkshredder ! The color you used, $grey-dark, is a color name from Bulma. Vocabulary uses its own color set, and the color used in the header is `$color-dark-gray`:
> 
> https://github.com/creativecommons/vocabulary/blob/960dc85ba776f47ab49d3428772a6030162a339a/packages/vocabulary/src/styles/color.scss#L17
> 
> Can you change the color name?

Done

2020-12-13 05:55 UTC, dhruvkb requested changes
We use spaces, not tabs, for indentation. Also please fix the extra space in the indentation.

2020-12-13 05:55 UTC, dhruvkb commented on packages/vocabulary/src/styles/header.scss
> +	  margin-left: $space-large;
Indentation is off by one space here.

2020-12-13 06:35 UTC, darkshredder commented on packages/vocabulary/src/styles/header.scss
> +	  margin-left: $space-large;
I have used spaced but when I committed it was automatically formatted in this way

2020-12-13 17:35 UTC, darkshredder commented
> We use spaces, not tabs, for indentation. Also please fix the extra space in the indentation.

Done

2021-02-05 17:31 UTC, zackkrida requested changes
Just a small whitespace change needed to fix this.

2021-02-05 17:31 UTC, zackkrida commented on packages/vocabulary/src/styles/header.scss
> +	color: $color-dark-gray;
```suggestion
      margin-left: $space-large;
      color: $color-dark-gray;
```

This looks great, it just needs to be spaces instead of tabs.

2021-02-05 17:43 UTC, Cronus1007 commented on packages/vocabulary/src/styles/header.scss
> +	color: $color-dark-gray;
@zackkrida Shall I implement this change.But I have to open a new PR since I can't pass commits to the PR.

2021-02-05 17:47 UTC, zackkrida commented on packages/vocabulary/src/styles/header.scss
> +	color: $color-dark-gray;
We can wait for the original contributor to revise their work, thank you!

2021-02-05 18:00 UTC, darkshredder commented on packages/vocabulary/src/styles/header.scss
> +	color: $color-dark-gray;
Done

2021-02-05 18:08 UTC, zackkrida approved these changes
Thanks!

2021-09-15 07:30 UTC, closed without merging