Typo-fix
cc-archive/vocabulary-legacy pull request #838
Opened 2020-12-25 21:24 UTC by SingingApple

## Related to typo
Fixed a typo in **gettingstarted.stories.mdx**

## Description
Changed _compoents_ to _components_ in **gettingstarted.stories.mdx** at line 157.

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-12-26 05:04 UTC, nimishbongale reviewed
Thanks for this! 👍 

There are a lot more changes than just fixing the typo (some dealing with code formatting), so that needs to be taken into account as well.

Suggested a few changes, please have a look!

2020-12-26 05:04 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/gettingstarted.stories.mdx
If you have a look at the other meta stories for Vocabulary, you'll notice we use single quotes for the import paths.

2020-12-26 05:04 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/gettingstarted.stories.mdx
> +The blog site looks a bit empty right now. Maybe we should add in a few more components!
Good find! 👍

2020-12-26 05:04 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/gettingstarted.stories.mdx
> +></iframe>
We may switch this out for CodePen prefill embeds (#837) but thanks for this anyways!

2020-12-26 15:21 UTC, SingingApple commented on packages/vocabulary/.storybook/meta/gettingstarted.stories.mdx
I've resolved this in the newer commit.

2020-12-27 07:16 UTC, nimishbongale approved these changes
LGTM 👍

2020-12-27 15:33 UTC, zackkrida requested changes
Thank you @SingingApple; while you're here could you spell check this entire page `gettingstarted.stories.mdx`? I noticed `personal` is spelled as `peronal` in a few places too.

2020-12-27 15:40 UTC, nimishbongale commented
> I noticed `personal` is spelled as `peronal` in a few places too.

Whops! Fixed it 😄

2020-12-27 17:52 UTC, SingingApple commented
@zackkrida I'll have a look and will make the changes if I find some by tomorrow.

2021-01-02 16:24 UTC, SingingApple commented
@zackkrida Couldn't find any typos on this page!

2021-01-20 22:17 UTC, zackkrida approved these changes
Thank you! FYI, your pull request contained _formatting changes_ to a few files, likely caused by prettier + vscode automatically formatting the files you opened. If you are working on a lot of open source projects I would recommend _this_ vscode setting:

<img width="565" alt="2021-01-20-106" src="https://user-images.githubusercontent.com/6351754/105247849-86465b80-5b19-11eb-9e1b-282b642fa2f3.png">

2021-01-20 22:18 UTC, merged