Add blocks for copying specific version link and latest version link individually
cc-archive/vocabulary-legacy pull request #851
Opened 2021-02-18 18:02 UTC by abhi14nexu

## Fixes

Fixes #[849](https://github.com/creativecommons/vocabulary/issues/849) by @[abhi14nexu](https://www.github.com/abhi14nexu)

## Description

This PR adds the feature of copying a specific version link(`v2020.11.1` in Stylesheets and `1.0.0-beta.6`

 in the Javascript section) and the latest version link individually by keeping both the links in individual blocks.

## Screenshots

![Screenshot from 2021-02-18 23-20-39](https://user-images.githubusercontent.com/56607134/108400531-4fab5000-7241-11eb-91e3-ca563f5eb382.png)
![Screenshot from 2021-02-18 23-21-01](https://user-images.githubusercontent.com/56607134/108400539-52a64080-7241-11eb-9364-6448fd250cad.png)
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-02-21 18:38 UTC, nimishbongale requested changes
Good start @abhi14nexu!

A few suggested changes, please do look into them. 👍

2021-02-21 18:38 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/usage.stories.mdx
> +####
Not quite sure what an empty #### does? Is there a better way to space it out?

2021-02-21 18:38 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/usage.stories.mdx
> +###### 1.0.0-beta.6 Version
Kindly change all the beta links to more recent ones.

2021-02-21 18:38 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/usage.stories.mdx
> +###### Latest Version
A line break in between 82 & 83 might make it a little better?

2021-02-23 19:27 UTC, abhi14nexu commented on packages/vocabulary/.storybook/meta/usage.stories.mdx
> +###### 1.0.0-beta.6 Version
@nimishbongale Can you please tell me which links are the recent ones as I am unable to find them?

2021-02-24 05:04 UTC, zackkrida requested changes
This looks good once @nimishbongale's changes are made. This is a very nice addition, thank you!

2021-02-24 18:11 UTC, nimishbongale commented on packages/vocabulary/.storybook/meta/usage.stories.mdx
> +###### 1.0.0-beta.6 Version
Sample unpkg link (v2020.11.3):

- https://unpkg.com/@creativecommons/vocabulary@2020.11.3/

Sample jsdelivr link (v2020.11.3):

- https://cdn.jsdelivr.net/npm/@creativecommons/vocabulary@2020.11.3/

2021-09-13 09:33 UTC, brylie commented
@abhi14nexu, thank you so much for the contribution.

I'm going to close this pull request without merging the changes since it is stale and there are unresolved review comments. Please feel free to re-open the pull request if you have the time to continue the task :smiley:

2021-09-13 09:33 UTC, closed without merging