Change root directory from monorepo to Vue CLI project
cc-archive/vocabulary-legacy pull request #933
Opened 2021-07-18 11:35 UTC by dhruvkb

## Fixes

Fixes #905 by @brylie 

## Description
This PR rearchitects the project to make it more maintainable.

## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-07-18 16:43 UTC, dhruvkb commented
The Storybook is up and the story about the SVG icon font has been completely rewritten to use Storybook's built in icon gallery. It looks fantastic!

2021-07-19 09:40 UTC, brylie commented
This looks good so far. Quite a lot of cleanup!

2021-07-19 12:19 UTC, dhruvkb commented
@brylie due to time constraints, I'll only be able to work further on this during the weekend. In the meantime feel free to push commits to the branch 👍!

2021-07-19 13:12 UTC, brylie commented
OK, thanks @dhruvkb. No hurry :smiley:

2021-07-21 12:35 UTC, dhruvkb commented
Assimilated Vocabulary stories into Storybook. A lot of things are broken because of broken paths but they should be fixed pretty soon. It's cool that most stories are visible now.

2021-07-21 14:13 UTC, dhruvkb commented
I've fixed two component stories in 56e2706. @brylie if you have some time, could you replicate this across the other broken components?

2021-09-07 08:31 UTC, brylie commented
@sadn1ck has expressed interest in helping us get this pull request to the finish line :checkered_flag: :1st_place_medal:  

@dhruvkb would you kindly help @sadn1ck with any code-related difficulties they might face? :man_technologist: 

As was mentioned, [commit `56e2706` serves as a recipe to follow](https://github.com/creativecommons/vocabulary/commit/56e27069ad50f6a544d51b25df255c954687e51e) for fixing the remaining few broken components. I have added a checklist :ballot_box_with_check: to this [pull request description :information_source:](https://github.com/creativecommons/vocabulary/pull/933) listing all of the components so we can get an idea of which ones remain to be fixed.

@sadn1ck, to get started, you can:

1. fork this repository
2. check out the `restructure` branch
3. create a new branch based on the `restructure` branch
4. commit your changes to the new branch
5. open a pull request from your branch against the `restructure` branch

I am available to assist if any of the above steps present problems.

2021-09-07 08:43 UTC, brylie commented
@sadn1ck, also feel free to contact me on the [Creative Commons Community Slack](https://slack-signup.creativecommons.org/). If you'd like, you are also welcome to attend this month's [Creative Commons Open Source Community Call](https://codebuddies.org/hangout/3fFKNPEjr2EdyERGz) to discuss this and other projects.

2021-09-07 08:47 UTC, sadn1ck commented
> @sadn1ck, also feel free to contact me on the [Creative Commons Community Slack](https://slack-signup.creativecommons.org/). If you'd like, you are also welcome to attend this month's [Creative Commons Open Source Community Call](https://codebuddies.org/hangout/3fFKNPEjr2EdyERGz) to discuss this and other projects.

Yes I have joined the Slack, will contact you there if I have any issues!

2021-09-07 09:02 UTC, brylie commented
> Yes I have joined the Slack, will contact you there if I have any issues!

Very cool! By the way, I see that you have made a considerable amount of contributions to projects on GitHub. Please excuse me for making the "getting started" checklist above, if all of those steps are familiar to you. :smiley:

2021-09-07 10:54 UTC, sadn1ck commented
> > Yes I have joined the Slack, will contact you there if I have any issues!
> 
> Very cool! By the way, I see that you have made a considerable amount of contributions to projects on GitHub. Please excuse me for making the "getting started" checklist above, if all of those steps are familiar to you. 😃

haha not at all! :D 

I have made a WIP PR https://github.com/creativecommons/vocabulary/pull/940 here, can you do a small review when you have time? Thanks!

2021-10-01 08:18 UTC, brylie requested changes
We should probably locate the files `fonts.json`, `vocabulary.json`, and `vue-vocabulary.json`, since they are needed for their respective `package.json` during the build process.

2021-10-01 08:18 UTC, brylie commented on scripts/build_fonts.sh
> +cp packages/fonts.json dist/fonts/package.json
This causes an error:

> Copying meta files...cp: cannot stat 'packages/fonts.json': No such file or directory

2021-10-01 08:18 UTC, brylie commented on scripts/build_vocabulary.sh
> +cp packages/vocabulary.json dist/vocabulary/package.json
Error here:

> Copying meta files...cp: cannot stat 'packages/vocabulary.json': No such file or directory

2021-10-01 08:18 UTC, brylie commented on scripts/build_vue_vocabulary.sh
> +cp packages/vue-vocabulary.json dist/vue-vocabulary/package.json
Error here:

> Copying meta files...cp: cannot stat 'packages/vue-vocabulary.json': No such file or directory

2021-10-01 08:49 UTC, brylie commented
@dhruvkb this pull request is nearly finished :smiley: I've just made a few small changes, so please remember to sync your local branch.

Would you please help resolve the few changes requested?

2021-10-01 12:28 UTC, sadn1ck commented
I don't think we need the custom build scripts now since everything is combined, we can use the `build:storybook` command in package.json to output the built files into a directory (`-o`, `docs/` as of now) and statically serve that. You can try that locally, it works for me right now.

```bash
# install deps and stuff

$ npm run build:storybook
$ cd docs
$ npx serve .

# go to displayed localhost URL
```


---

Also, a small issue which I somehow missed

<details>

<summary>Due to the parser text output and some of our custom css having the same class `.value`, some parts of the code have become way too large haha</summary>

![image](https://user-images.githubusercontent.com/16396161/135619519-7fa6cf1d-80db-40ce-8f1f-e6d24b598827.png)


</details>

2021-10-02 07:03 UTC, brylie commented
> I don't think we need the custom build scripts now since everything is combined

We still need to build and publish the packages independently.

2021-10-02 07:03 UTC, brylie commented
What would be a good solution for the text size issue?

2021-10-02 08:05 UTC, sadn1ck commented
> We still need to build and publish the packages independently.

Ah yes, my bad

> What would be a good solution for the text size issue?

Probably need to update the .value class to something like .custom-value and change wherever it is used 🤔 The styles of `value` class in the code of a component is generated by storybook, I think.

Let's wait for Dhruv's take 😄

2021-10-05 09:54 UTC, brylie commented
I'm in favor of deferring the font-size fix until after this pull request is merged. This is already a huge undertaking and we are converging on work in related projects that depend on vocabulary.

@dhruvkb, could you review and approve this pull request if there are no major concerns remaining?

2021-10-05 11:10 UTC, dhruvkb commented
I agree with @brylie on fixing the font-size separately. Since it's my own PR I cannot approve it but I've un-drafted it to let it be merged.

2021-10-05 11:18 UTC, brylie approved these changes

2021-10-05 11:18 UTC, merged