Fix npm build bugs for bash scripts on windows environments
cc-archive/vocabulary-legacy pull request #960
Opened 2021-10-12 04:28 UTC by MuluhGodson

## Fixes

Fixes #958  by @emmaxy07
Fixes #959  by @Akpjunior94

## Description
Most of these commands run without issues on Linux but in windows due to path issues, these commands were breaking. This fix corrects the path issues making these scripts do their functions on both Linux and windows development environments.
Another issue I found was how windows handles linebreaks (LF or CRLF) for its bash environment. This causes the scripts to break during execution but a simple fix will be to add the fix option to the script command. Example instead of running `npm run build:fonts` do `npm run build:fonts --fix` and the error will be auto-resolved. I have already documented this in `README.md` file.

This fix will enable our windows developers to be able to compile successfully.
The following commands should work:
[x] `npm run serve`
[x] `npm run build:fonts` or `npm run build:fonts --fix` for windows devs
[x] `npm run build:vocabulary` or `npm run build:vocabulary --fix` 
[x] `npm run build:vue-vocabulary` or `npm run build:vue-vocabulary --fix`
[x] `npm run lint`

## Tests
Those who faced this issue, can test this features so we can be sure it works in their setups. Run the various build commands:
```bash
npm run build:fonts --fix
npm run build:vocabulary --fix
npm run build:vue-vocabulary --fix
```

## Screenshots

### Problem
![image](https://user-images.githubusercontent.com/40151808/136891028-0cc24fa6-325a-47da-8084-80b36a5df4df.png)

### Solution
![image](https://user-images.githubusercontent.com/40151808/136890963-ce29572c-fd0e-41b4-af9b-fc0c674d2e15.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-10-12 04:37 UTC, Akpjunior94 commented
Great work @MuluhGodson

2021-10-12 06:47 UTC, emmaxy07 commented
Nice one @MuluhGodson

On Tue, Oct 12, 2021, 5:38 AM Akpan Abraham ***@***.***>
wrote:

> Great work @MuluhGodson <https://github.com/MuluhGodson>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/vocabulary/pull/960#issuecomment-940651705>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOYX4RTXGQMBOGKM4IPC3FDUGO3SZANCNFSM5FZTQTHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-12 08:03 UTC, brylie requested changes

2021-10-12 08:03 UTC, brylie commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
I think we should restore this `package.json` since it has project metadata.

2021-10-12 08:03 UTC, brylie commented on README.md
> +```
This should be moved to a "Build and publish" section of the guide since it is related to building packages for publication.

2021-10-12 08:03 UTC, brylie commented on scripts/build_vocabulary.sh
> +#cp packages/vocabulary.json dist/vocabulary/package.json
Let's restore this file rather than commenting out the line.

2021-10-12 08:03 UTC, brylie commented on scripts/build_vue_vocabulary.sh
> +#cp packages/vue-vocabulary.json dist/vue-vocabulary/package.json
Let's restore this file rather than commenting out the line.

2021-10-12 08:12 UTC, MuluhGodson commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
Okay, Let me restore the packages/fonts.json and run some more test

2021-10-12 08:16 UTC, MuluhGodson commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
@brylie I restored the folder but the file it's supposed to copy `fonts.json` doesn't exist in that folder. Looking at the configuration in the `package.json` file of that packages folder suggest that it used to be compiled using webpack

2021-10-12 08:16 UTC, MuluhGodson commented on README.md
> +```
Okay got it.

2021-10-12 08:18 UTC, brylie commented on README.md
> +```
I realize this project is missing some key context. Thank you for helping us to improve the documentation and development process. :-)

2021-10-12 08:20 UTC, MuluhGodson commented on README.md
> +```
The heading for this section is ##Building the packages

2021-10-12 08:23 UTC, brylie commented on README.md
> +```
Yes, with a space after the hash marks "## Building the packages"

2021-10-12 08:24 UTC, brylie commented on README.md
> +```
Ah my bad. Sorry. I didn't notice the collapsed code. Resolving this conversation.

2021-10-12 08:27 UTC, brylie commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
OK, let's just set up some default package.json files with `name` and `version` fields for now.

<details>

<summary>example fonts/package.json</summary>

```json
{
    "name": "cc-vocabulary-fonts",
    "version": "1.0.0"
}
```

</details>

2021-10-12 08:31 UTC, MuluhGodson commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
This will be the best option

2021-10-12 08:34 UTC, brylie commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
The version number should be our latest release:

![image](https://user-images.githubusercontent.com/17307/136921438-b4ad1764-0714-4697-a111-25f106d730f5.png)

2021-10-12 08:49 UTC, MuluhGodson commented on scripts/build_fonts.sh
> +#cp packages/fonts.json dist/fonts/package.json
@brylie I have done this in the latest commit

2021-10-12 08:51 UTC, brylie requested changes

2021-10-12 08:51 UTC, brylie commented on scripts/build_fonts.sh
> +cp packages/fonts/package.json dist/fonts/package.json
This doesn't have the leading `./`. If it works without the `./` we should remove `./` from the other files. Otherwise, add `./` for consistency.

2021-10-12 08:54 UTC, MuluhGodson commented on scripts/build_fonts.sh
> +cp packages/fonts/package.json dist/fonts/package.json
Oh I missed that. I think preferably it should be removed since it works without.

2021-10-12 08:56 UTC, brylie approved these changes

2021-10-12 09:20 UTC, MuluhGodson commented
The most recent commit here should fix #961 #962 #963 #964

2021-10-12 09:22 UTC, brylie requested changes

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-fonts.yml
> +        run: bash scripts/build_fonts.sh
We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-vocabulary.yml
> +        run: bash scripts/build_vocabulary.sh
We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
We actually need to restore the `deploy.sh`, since building the package is only one step in the deployment process.

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-fonts.yml
> +        run: bash scripts/build_fonts.sh
https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/deploy.sh

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-vocabulary.yml
> +        run: bash scripts/build_vocabulary.sh
https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/deploy.sh

2021-10-12 09:22 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/deploy.sh

2021-10-12 09:23 UTC, brylie commented
@MuluhGodson, let's not add too much more in this pull request. Subsequent issues can be resolved with distinct pull requests.

2021-10-12 09:24 UTC, brylie commented
> The most recent commit here should fix #961 #962 #963 #964

Go ahead and use the GitHub keywords to link this pull request to those issues.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

2021-10-12 09:24 UTC, MuluhGodson commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
Okay I see. Yeah it makes more sense to have a different deploy script

2021-10-12 09:31 UTC, brylie commented
For clarification, the scope of this pull request should remain "Fix npm build bugs for bash scripts on windows environments." Let's continue other tasks in separate pull requests.

2021-10-12 09:32 UTC, MuluhGodson commented
closes #958 
closes #959

2021-10-12 09:34 UTC, brylie commented
Add those "Closes #..." messages to the pull request description.

2021-10-12 10:24 UTC, brylie commented
@MuluhGodson, let's finish this pull request before starting another. There are a few out-of-scope changes in this pull request. Would you please revert changes related to #956 and #957 by removing/reverting the code and committing those changes?

2021-10-12 10:32 UTC, brylie requested changes

2021-10-12 10:32 UTC, brylie commented on .github/workflows/cd-fonts.yml
> +        run: bash scripts/build_fonts.sh
Revert this change
```suggestion
        run: bash deploy.sh
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/cd-vocabulary.yml
> +        working-directory: "/"
Revert this change
```suggestion
        working-directory: "packages/vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/cd-vocabulary.yml
> +        run: bash scripts/build_vocabulary.sh
Revert this change
```suggestion
        run: bash deploy.sh
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        working-directory: "/"
Revert this change
```suggestion
        working-directory: "packages/vue-vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
Revert this change
```suggestion
        run: bash deploy.sh
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/fonts/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/fonts/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/fonts"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/fonts"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> -
Revert

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/fonts"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-fonts.yml
> +        run: npm run build:fonts
Revert
```suggestion
        run: npm run build
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/vocabulary/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/vocabulary/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> -
Revert

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> +        run: npm run build:vocabulary
Revert
```suggestion
        run: npm run build
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/vue-vocabulary/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +      - "scripts/**"
Revert
```suggestion
      - "packages/vue-vocabulary/**"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> -
Revert

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +        working-directory: "/"
Revert
```suggestion
        working-directory: "packages/vue-vocabulary"
```

2021-10-12 10:32 UTC, brylie commented on .github/workflows/ci-vue.yml
> +        run: npm run build:vue-vocabulary
Revert
```suggestion
        run: npm run build
```

2021-10-12 10:34 UTC, brylie commented
@MuluhGodson, as far as possible, I've gone through and flagged code to be reverted with suggestions. That way, you can click "Commit suggestion" or "add suggestion to batch" in order to easily make the suggested changes. However, there are some deleted blocks of code that will need to be manually restored. They shouldn't be deleted in this or any other issue, as we just need to fix them to work correctly.

2021-10-12 10:43 UTC, MuluhGodson commented
@brylie That was very helpful. I noticed it was the last commit I made. So I reverted the commit.

2021-10-12 10:58 UTC, brylie approved these changes

2021-10-12 10:59 UTC, merged

2021-10-12 13:46 UTC, emmaxy07 commented
npm run build:fonts --fix command still returning previous error on windows

On Tue, Oct 12, 2021, 11:59 AM Brylie Christopher Oxley <
***@***.***> wrote:

> Merged #960 <https://github.com/creativecommons/vocabulary/pull/960> into
> main.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/vocabulary/pull/960#event-5448722590>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOYX4RX5U6EEIK4LIHOSSKLUGQIILANCNFSM5FZTQTHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-12 13:52 UTC, MuluhGodson commented
@emmaxy07 
Did you install all the dependencies: 
`npm install --legacy-peer-deps`

The fix above I tested it on two different windows setups (where it previously failed before the fix) and it worked before I opened the PR. 
The npm version on the windows setup is `8.0.0.0` and the node version is `v16.11.0`

I want to emphasize that Prior to this fix the scripts didn't run, but now they do.

2021-10-12 14:20 UTC, emmaxy07 commented
I just installed all the dependencies with
npm install --legacy-peer-deps



On Tue, Oct 12, 2021, 2:52 PM MuluhGodson ***@***.***> wrote:

> @emmaxy07 <https://github.com/emmaxy07>
> Did you install all the dependencies:
> npm install --legacy-peer-deps
>
> The fix above I tested it on two different windows setups (where it
> previously failed before the fix) and it worked before I opened the PR.
> The npm version on the windows setup is 8.0.0.0 and the node version is
> v16.11.0
>
> I want to emphasize that Prior to this fix the scripts didn't run, but now
> they do.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/vocabulary/pull/960#issuecomment-941034145>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOYX4RVHEKPQLTFHDB2ONGLUGQ4STANCNFSM5FZTQTHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-12 14:20 UTC, emmaxy07 commented
npm run build:fonts is still not working

On Tue, Oct 12, 2021, 3:20 PM Emmanuel Iyare ***@***.***>
wrote:

> I just installed all the dependencies with
> npm install --legacy-peer-deps
>
>
>
> On Tue, Oct 12, 2021, 2:52 PM MuluhGodson ***@***.***>
> wrote:
>
>> @emmaxy07 <https://github.com/emmaxy07>
>> Did you install all the dependencies:
>> npm install --legacy-peer-deps
>>
>> The fix above I tested it on two different windows setups (where it
>> previously failed before the fix) and it worked before I opened the PR.
>> The npm version on the windows setup is 8.0.0.0 and the node version is
>> v16.11.0
>>
>> I want to emphasize that Prior to this fix the scripts didn't run, but
>> now they do.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/creativecommons/vocabulary/pull/960#issuecomment-941034145>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOYX4RVHEKPQLTFHDB2ONGLUGQ4STANCNFSM5FZTQTHQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-10-13 07:29 UTC, brylie commented
@emmaxy07 what error are you getting? What are your versions of npm and node? `npm --version` and `node --version`

2021-10-13 07:32 UTC, MuluhGodson commented
@brylie The errors @emmaxy07 and @Akpjunior94 were facing were already resolved. They just had to `git pull`.