Restore publishing scripts for continuous delivery
cc-archive/vocabulary-legacy pull request #966
Opened 2021-10-12 09:54 UTC by MuluhGodson

## Fixes

Closes #964  by @brylie 

## Description

This PR restores the scripts used to deploy the packages to NPM.  The `sed` command, I left it in place after testing and previewing a verbose output of what it does, which is ensuring that for each package deployed, there is a README.md file in the dist folder. 

Closes #964 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-10-12 10:08 UTC, brylie requested changes

2021-10-12 10:08 UTC, brylie commented on .github/workflows/cd-fonts.yml
> +        run: bash scripts/build_fonts.sh
Please pay close attention to the linked files in issue https://github.com/creativecommons/vocabulary/issues/964

The `build` and `deploy` scripts have different purposes.

Here, we need to actually restore the [`deploy` script](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/deploy.sh) and change the name to `publish/fonts.sh` to make the purpose more clear.

2021-10-12 10:08 UTC, brylie commented on .github/workflows/cd-vocabulary.yml
> +        run: bash scripts/build_vocabulary.sh
Please pay close attention to the linked files in issue https://github.com/creativecommons/vocabulary/issues/964

The `build` and `deploy` scripts have different purposes.

Here, we need to actually restore the [`deploy` script](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/deploy.sh) and change the name to `publish/vocabulary.sh` to make the purpose more clear.

2021-10-12 10:08 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
Please pay close attention to the linked files in issue https://github.com/creativecommons/vocabulary/issues/964

The `build` and `deploy` scripts have different purposes.

Here, we need to actually restore the [`deploy` script](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/deploy.sh) and change the name to `publish/vue-vocabulary.sh` to make the purpose more clear.

2021-10-12 10:15 UTC, brylie requested changes

2021-10-12 10:15 UTC, brylie commented on README.md
> +@creativecommons/vue-vocabulary    | Vue component library powered by the main CSS library  | [![install size](https://packagephobia.com/badge?p=@creativecommons/vue-vocabulary)](https://packagephobi
These changes should only be made in pull-request #960

2021-10-12 10:15 UTC, brylie commented on README.md
> +```
These changes should only be made in pull-request #960

2021-10-12 10:15 UTC, brylie commented on deploy.sh
> +#!/bin/bash
Let's move/rename this file as `publish/fonts.sh`

2021-10-12 10:15 UTC, brylie commented on deploy.sh
> +sed -i -e 's/say, fonts/here, vue-vocabulary/' -e 's/cd packages\/fonts/cd packages\/vue-vocabulary/' dist/README.md
I'm not sure that this line will work any longer. We may need to fix the paths at the least.

2021-10-12 10:15 UTC, brylie commented on package.json
> +    "build:vue-vocabulary": "bash ./scripts/build_vue_vocabulary.sh"
These changes should only be made in pull-request #960

2021-10-12 10:15 UTC, brylie commented on publish.sh
> +#!/bin/bash
This should be renamed to `publish/fonts.js` but it is a duplicate of the previous file.

Notice that we have three sub-packages so we will need a `publish/<package-name>.sh` for each one. That way, we can publish each package to NPM independently.

2021-10-12 10:16 UTC, brylie requested changes
Let's please take care to work on only a single task or at most a couple of tasks in a single pull request. We are including changes from too many issues here, so the pull request is losing focus.

2021-10-12 10:17 UTC, MuluhGodson commented on package.json
> +    "build:vue-vocabulary": "bash ./scripts/build_vue_vocabulary.sh"
Okay I think I created a new branch to work on this issue with the commits from the other branch already included. Since the commits were not merged I think that's why it moved over to this branch. I will need guidance on how to remove the commits from this branch, but I don't know if it could cause an issue in the git logs

2021-10-12 10:22 UTC, brylie commented on package.json
> +    "build:vue-vocabulary": "bash ./scripts/build_vue_vocabulary.sh"
It is probably easiest to just start a new branch directly from `develop`. Then, claim a _single_ issue by commenting on GitHub and resolve only that issue by a single pull request. Let's slow down a bit to avoid these and similar mistakes :smiley:

2021-10-12 10:55 UTC, MuluhGodson commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
@brylie  I have a question.
If you look at the deploy script in all the different packages fonts, vocabulary and vue vocabulary, all of them are the same.

```bash

set -o errexit
set -o errtrace
set -o nounset

trap '_es=${?};
    _lo=${LINENO};
    _co=${BASH_COMMAND};
    echo "${0}: line ${_lo}: \"${_co}\" exited with a status of ${_es}";
    exit ${_es}' ERR

npm run build
rm dist/demo.html
cp package.json dist/
cp ../../README.md dist/
sed -i -e 's/say, fonts/here, vue-vocabulary/' -e 's/cd packages\/fonts/cd packages\/vue-vocabulary/' dist/README.md
cp LICENSE dist/

cd dist
npm publish --access public
```

The only line that changes for each file is the `sed` line
for vocabulary it is:
 `sed -i -e 's/say, fonts/here, vocabulary/' -e 's/cd packages\/fonts/cd packages\/vocabulary/' dist/README.md`
for fonts it is:
 `sed -i -e 's/say, fonts/here, fonts/' dist/README.md`
and for vue-vocabulary it is:
 `sed -i -e 's/say, fonts/here, vue-vocabulary/' -e 's/cd packages\/fonts/cd packages\/vue-vocabulary/' dist/README.md`

The `sed` command used here is used to replace occurrences of the given words in the README.md files that are copied to each of the directories created at build time.

So with regards to the issue at hand, would it suffice to duplicate this `deploy.sh` file for each of the packages?

2021-10-12 11:01 UTC, brylie requested changes
Please fix the checklist items in the pull request description. There should be no space before or after the "x". It is possible to just click the checkmark rather than manually entering the "x" within the square brackets.

![image](https://user-images.githubusercontent.com/17307/136943899-073fe776-f4ad-4774-a0c4-e8fee64a25c6.png)

2021-10-12 11:02 UTC, brylie commented
I'm converting this pull request to draft status since there is still work in progress. :smiley: 

Please request a review once the previous review issues are resolved.

2021-10-12 11:05 UTC, MuluhGodson commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
did you happen to see this?

2021-10-12 11:12 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
I just saw this. To the extent possible, it would be good to reduce duplicate code. What would be your recommendation?

2021-10-12 11:13 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
To the best of my knowledge, we want to maintain separate publishing scripts so the packages can be published independently. However, we don't need to duplicate 90% of the code just to have one `sed` command difference.

2021-10-12 11:18 UTC, MuluhGodson commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
Okay, would you prefer that the deploy script be separated, and then another script for each package that does what the sed command does, since it involves changing some words in the README files that are copied to each packages build folder. I will do more research and examine previous commits from months back to see what would be the best fit.

2021-10-12 11:20 UTC, brylie commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
For now, we can just have three separate files with 90% duplication. Once we have restored the basic publishing workflow, we can optimize the code a bit more. What are your thoughts?

2021-10-12 11:28 UTC, MuluhGodson commented on .github/workflows/cd-vue.yml
> +        run: bash scripts/build_vue_vocabulary.sh
I think this will be the best option. It retains the consistency of the code from how it was previously and gives us enough room to be able to look deeper into optimization as a whole.

2021-10-13 06:24 UTC, MuluhGodson commented on .github/workflows/cd-fonts.yml
> +        run: bash scripts/build_fonts.sh
I just went through all the files again.
You were very correct. The build scripts work differently from the deploy scripts. 
The deploy script is what publishes these packages to NPM. I must have gotten confused by the naming. I understand why you recommended I separate them into their respective folders. :-)

2021-10-13 08:19 UTC, brylie requested changes

2021-10-13 08:19 UTC, brylie commented on publish/fonts.sh
> +npm publish --access public
Add newline at end of file
```suggestion
npm publish --access public

```

2021-10-13 08:19 UTC, brylie commented on publish/vocabulary.sh
> +npm publish --access public
Add newline at end of file
```suggestion
npm publish --access public

```

2021-10-13 08:19 UTC, brylie commented on publish/vue-vocabulary.sh
> +npm publish --access public
Add newline at end of file
```suggestion
npm publish --access public

```

2021-10-13 08:22 UTC, brylie requested changes
Since the scope of issue #964 is limited to deployment/publication scripts, this pull request should only include changes that are related to the "continuous delivery" files `cd-*.yml`

Let's move changes related to continuous integration (`ci-*.yml`) to a separate pull request after claiming the relevant issue.

In this way, our work is a bit easier to follow and less error-prone. It will also be clear to other contributors who is working on which task(s).

2021-10-13 08:23 UTC, brylie commented on .github/workflows/ci-fonts.yml
> -
After CI changes are removed from this branch, we will want to make sure the unit tests are still included in the CI task. So, we won't want to delete these lines, but rather restore the unit tests as per #965

2021-10-13 08:24 UTC, brylie commented on .github/workflows/ci-vocabulary.yml
> -
This deletion is not needed, as we want to restore unit tests #965

2021-10-13 08:28 UTC, brylie requested changes

2021-10-13 08:28 UTC, brylie commented on .github/workflows/ci-fonts.yml
>  on:
Changes to CI scripts are out-of-scope for this pull request since it should only pertain to issue #964

2021-10-13 08:28 UTC, brylie commented on .github/workflows/ci-vue.yml
>  on:
Changes to CI scripts are out-of-scope for this pull request since it should only pertain to issue #964

2021-10-13 08:28 UTC, brylie commented on deploy.sh
> +#!/bin/bash
Is this file made redundant by `publish/vue-vocabulary.sh`?

2021-10-13 08:28 UTC, brylie commented on publish.sh
> +#!/bin/bash
Is this file made redundant by `publish/vue-vocabulary.sh`?

2021-10-13 08:30 UTC, MuluhGodson commented on deploy.sh
> +#!/bin/bash
yes, the `deploy.sh` file is made redundant

2021-10-13 08:33 UTC, brylie commented
@MuluhGodson, great work so far. I'm just commenting mainly to keep things slightly more separated since some of the tasks have different sizes and goals.

2021-10-13 08:33 UTC, MuluhGodson commented on .github/workflows/ci-vue.yml
>  on:
I just reverted all the changes.

2021-10-13 08:34 UTC, MuluhGodson commented
@brylie thank you. It's my pleasure

2021-10-13 08:40 UTC, brylie approved these changes

2021-10-13 08:41 UTC, merged