Modify class names
cc-archive/vocabulary-legacy pull request #97
Opened 2020-01-31 17:36 UTC by hugosolar

**Description**
Class names modification in order to be more explicit and less general

**Type of PR** 
This PR is a refactor.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

2020-02-04 17:12 UTC, brenoferreira requested changes

2020-02-04 17:12 UTC, brenoferreira commented on src/styles/form.scss
> +.input-text {
`.input` is a Bulma class https://bulma.io/documentation/form/input/. We just modify those base styles here a bit

2020-02-04 17:15 UTC, brenoferreira approved these changes

2020-02-05 16:30 UTC, brenoferreira requested changes

2020-02-05 16:30 UTC, brenoferreira commented on src/styles/typography.scss
> +.font-caption {
I think this is better as `.caption`. `.font-caption` looks a bit weird as class name.

2020-02-05 16:30 UTC, brenoferreira commented on src/styles/typography.scss
> +.font-value {
Same here. I think this is better as `.value`. `.font-value` looks a bit weird as class name.

`.value` and `.caption` are the same as in the Figma designs

2020-02-05 17:20 UTC, hugosolar commented on src/styles/typography.scss
> +.font-value {
Yes but it seems to be a little bit wide and general maybe we can give it some context.

2020-02-05 21:27 UTC, brenoferreira commented on src/styles/typography.scss
> +.font-value {
`number-value` maybe? `caption` seems a bit obvious, but maybe `element-caption` is more clear. What do you think?

2020-02-22 14:57 UTC, hugosolar commented on src/styles/typography.scss
> +.font-caption {
I'm going to resume this discussion. We should define a prefix for font-sizes and avoid class names who can lead to confusion. Also, we have to think these classes will be available to websites which will contain other class names and we should avoid future conflicts or trying to give some context for instance `.element .specific-class`

2020-02-22 15:04 UTC, hugosolar commented on src/styles/typography.scss
> +.font-value {
same thing, I think it would be easier to standardize a prefix for font-sizes/properties this will be helpful to anyone who wants to work with the framework
, for instance, we can use the Bulma's naming convention for [font styles](https://bulma.io/documentation/modifiers/typography-helpers/#font-family)
But makes much more sense that way

2020-03-10 00:51 UTC, closed without merging