Added Unit testing for all vue-vocabulary package
cc-archive/vocabulary-legacy pull request #978
Opened 2021-10-13 16:17 UTC by MuluhGodson

## Fixes

Closes #965  by @brylie 
Closes #962  by @brylie 

## Description
Reinstated test for @vue-vocabulary package.

So, for contributing, each time a new core module is added, or an existing module is refactored, a test should be written for that module in the package and run using the unit's test.

To summarize, task completed include:
- [x]  added a test unit for Vue-vocabulary
- [x]  added test script for vue-vocabulary
- [x]  added a general test script
- [x]  updated README.md to reflect changes made 

## Technical details
Packages installed include:
```bash
    vue/cli-plugin-unit-jest": "~4.5.0
    jest": "^27.2.5
    vue/test-utils": "^1.0.3
```

## Tests
Run the following commands to test each package individually
```bash
npm run test:vue-vocabulary
```
To run a general test, run this command
```bash
npm run test:unit
```

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-10-13 16:49 UTC, brylie requested changes
Just a couple of minor lint issues.

2021-10-13 16:49 UTC, brylie commented on packages/vue-vocabulary/tests/unit/Dummy.spec.js
> +  })
Lint
```suggestion
  })

```

2021-10-13 16:49 UTC, brylie commented on packages/vue-vocabulary/tests/unit/VCheckbox.spec.js
> +})
Lint
```suggestion
})

```

2021-10-13 16:49 UTC, brylie commented on packages/vue-vocabulary/tests/unit/jest.config.js
> +};
Lint
```suggestion
};

```

2021-10-13 16:49 UTC, brylie commented on scripts/test_unit.sh
> +npm run test:vue-vocabulary
lint
```suggestion
npm run test:vue-vocabulary

```

2021-10-13 16:49 UTC, brylie commented on scripts/test_unit.sh
> +npm run test:vocabulary
Do we still need these tests?

2021-10-13 16:49 UTC, brylie commented on scripts/test_unit.sh
> +echo "Testing all packages"
We can probably delete this file, if there is only one test suite (`test:vocabulary`).

2021-10-13 16:50 UTC, brylie commented
Overall, the `*.scss` tests don't strike me as very meaningful. They are essentially diffing files, which is done as part of code review already.

2021-10-13 16:51 UTC, brylie requested changes
Let's move the project tests into a `/tests/` directory in the project root, rather than in `packages/<package-name>/`

2021-10-13 16:54 UTC, MuluhGodson commented on scripts/test_unit.sh
> +npm run test:vocabulary
Okay I think I will remove them

2021-10-13 16:57 UTC, MuluhGodson commented on scripts/test_unit.sh
> +echo "Testing all packages"
You mean `test:vue-vocabulary`
It's the test that doesn't check the `*.scss` files

2021-10-13 17:00 UTC, brylie requested changes

2021-10-13 17:00 UTC, brylie commented on packages/vue-vocabulary/tests/unit/Dummy.spec.js
> +  })
Check indentation.

2021-10-13 17:01 UTC, MuluhGodson commented
to clarify, moving project tests into a `/tests/` directory in the project root
will the structure now be `<root_folder>\tests\<package_name>\tests` ?

2021-10-13 17:02 UTC, MuluhGodson commented
also, should I delete the tests folders for `fonts` and `vocabulary` since the commands will also be removed for now?

2021-10-13 17:02 UTC, brylie commented on scripts/test_unit.sh
> +echo "Testing all packages"
I think we can delete the `scripts/test_unit.sh` since we only intend to keep `test:vue-vocabulary`, correct?

2021-10-13 17:03 UTC, brylie commented
> also, should I delete the tests folders for fonts and vocabulary since the commands will also be removed for now?

Yes. Let's clean up any unused folders, code, etc. as we develop.

2021-10-13 17:05 UTC, brylie commented
> will the structure now be `<root_folder>\tests\<package_name>\tests`?

I'm not sure we need to include the `<package-name>` in the path, since there is only one package (`vue-vocabulary`) that we will be testing. What do you suggest?

Also, the second `tests/` is redundant.

2021-10-13 17:10 UTC, MuluhGodson commented
I think that is the best option. To avoid redundancy. If in future subsequent test are written for the other packages, then the structure can be updated then.

2021-10-14 07:22 UTC, brylie approved these changes

2021-10-14 07:27 UTC, brylie requested changes
Since this pull request intends to close #965, please ensure that all of the checklist items in #965 are complete here.

![image](https://user-images.githubusercontent.com/17307/137271127-94688c19-adc5-4169-87d6-004b822ed990.png)

2021-10-14 07:29 UTC, MuluhGodson commented
Hello @brylie 
A PR was merged yesterday that seperated the CI files. we no longer have a ci-fonts etc. we have just `ci-build.yml`, `ci-lint.yml` and `ci-test.yml`

2021-10-14 07:31 UTC, MuluhGodson commented
also, you had recommended yesterday that since we have just a test for `vue-vocabulary` we should just place the test files in the root `test` folder, with no `<package_name>` sub-folders.

https://github.com/creativecommons/vocabulary/pull/978#issuecomment-942527511

2021-10-14 07:40 UTC, brylie commented
@MuluhGodson, good points. The project structure has changed since the checklist was complete. I'm mainly concerned about deleting unused code and files. Are there any unused scripts or code remaining in the project related to this pull request?

2021-10-14 07:41 UTC, brylie commented on tests/unit/Dummy.spec.js
> +describe('Dummy', () => {
We can probably delete this Dummy spec, unless you think it might be useful.

2021-10-14 07:43 UTC, MuluhGodson commented on tests/unit/Dummy.spec.js
> +describe('Dummy', () => {
oh yes. I just used that for initial testing. it's deleted now.

2021-10-14 07:44 UTC, MuluhGodson commented
- [x] restore testing code in a `tests/` directory in the root of this project
  - [x] tests/vue-vocabulary see https://github.com/creativecommons/vocabulary/pull/978#issuecomment-942527511
- [x] ensure we have script(s) defined in package.json to invoke test suites `npm run test:unit` and `npm run test:vue-vocabulary` while both test will do the same things now I made a decision to leave them because the `npm run test:unit` is used by the CI pipeline to run a general test and when future test are included, this command will be relevant and it is a good idea to have the `npm run test:vue-vocabulary` solely for running test for the `vue-vocabulary` if test for the others are subsequently added.
- [x] update CI test runners to invoke restored test
   - [x] `ci-vue.yml` A PR merge yesterday changed all test files to just `ci-test.yml`.
- [x] remove fonts test, since `sass-jest` is no longer maintained.
  - [x] delete `ci-fonts.yml` see https://github.com/creativecommons/vocabulary/pull/977
  - [x] delete `ci-vocabulary.yml` see https://github.com/creativecommons/vocabulary/pull/977
- [x] delete all unused scripts and code after refactoring

2021-10-14 07:45 UTC, brylie commented
I just browsed the code on your branch and it seems fairly clean. So, I acknowledge that I was mistaken with the comment above. Thanks also for revising the checklist :smile: 

I did notice there are two `jest.config.js` files. Can we consolidate those files so there is only one Jest configuration?

2021-10-14 07:45 UTC, brylie approved these changes

2021-10-14 07:46 UTC, brylie commented
In any case, I've approved this pull request. I'll just wait for your response about the double Jest configs.

2021-10-14 07:49 UTC, brylie commented
It's going to be great to have our CI scripts up and running again :smiley: Thank you for your excellent work in this regard!

2021-10-14 07:52 UTC, MuluhGodson commented
@brylie oh yes, removing the `jest.config.js` found in the `test` folder has no effect so i think it's a good idea to delete it. I think i used it when i still ran the test using `jest -c jest.config.js` but now the test are run using `vue-cli` so it's not needed any further.
but the `jest.config.js` in the <root> folder is necessary so that the `jest` test written for `vue-vocabulary` will be run with `vue-cli`

2021-10-14 07:53 UTC, MuluhGodson commented
@brylie sorry I erroneously closed this with a comment. it's reopened now.

2021-10-14 07:56 UTC, brylie commented
OK, let's delete the extra `jest.config.js`. Are there any config settings that should be merged into the remaining `jest.config.js`?

2021-10-14 07:57 UTC, brylie commented
If not, I'll go ahead and merge this PR.

2021-10-14 07:58 UTC, MuluhGodson commented
No. i think the configs that were in the deleted `jest.config.js` are not useful in this context. It was for a previous setup I experimented with but was not happy with the results.

2021-10-14 07:58 UTC, merged